const char *strings[] = {
	"flause",
	"",
	" kode ",
	"  plante og alge",
	"",
	" musikk",
	"  slc av kvasigen",
	"",
	" mye hjelp fra veileder",
	"  sirkel",
	"   nb  sistnevnte tar",
	"       foroevrig intet",
	"       ansvar for",
	"       introens innhold",
	"",
	"",
	"greets til",
	" ilmari",
	" hash scene dot no",
	" outsiders",
	" alle som stemmer flause",
	"",
	" obtw tg rewler vilt"
};
