@echo off
cls
cmodtsr freedom.mod 47
cls
echo                                 NOOOONE
cls
echo                                 NOOOONE
cls
echo                                 NOOOONE
cls
echo                                 NOOOONE
cls
cls
cls
echo                                 NOOOONE
cls
echo                                 NOOOONE
cls
echo                                 NOOOONE
cls
echo                                 NOOOONE
cls
cls
cls
echo                                 NOOOONE
cls
echo                                 NOOOONE
cls
echo                                 NOOOONE
cls
echo                                 NOOOONE
cls
cls
cls
echo           NOOOONE
cls
echo           NOOOONE
cls
echo           NOOOONE
cls
echo           NOOOONE
cls
cls
cls
echo           NOOOONE
cls
echo           NOOOONE
cls
echo           NOOOONE
cls
echo           NOOOONE
cls
cls
cls
echo           NOOOONE
cls
echo           NOOOONE
cls
echo           NOOOONE
cls
echo           NOOOONE
cls
cls
cls
echo                                                   NOOOONE
cls
echo                                                   NOOOONE
cls
echo         					       NOOOONE
cls
echo          					       NOOOONE
cls
cls
cls
echo                                                   NOOOONE
cls
echo                                                   NOOOONE
cls
echo         					       NOOOONE
cls
echo          					       NOOOONE
cls
cls
cls
echo                                                   NOOOONE
cls
echo                                                   NOOOONE
cls
echo         					       NOOOONE
cls
echo          					       NOOOONE
cls
cls
cls
echo                       NOOOONE
cls
echo                       NOOOONE
cls
echo                       NOOOONE
cls
echo                       NOOOONE
cls
cls
cls
echo                       NOOOONE
cls
echo                       NOOOONE
cls
echo                       NOOOONE
cls
echo                       NOOOONE
cls
cls
cls
echo                       NOOOONE
cls
echo                       NOOOONE
cls
echo                       NOOOONE
cls
echo                       NOOOONE
cls
cls
echo                                 presents
cls
cls
cls
echo                                 presents
cls
echo                                 presents
cls
echo                                 presents
cls
echo                                 presents
cls
echo                                 presents
cls
echo                                 presents
cls
echo                                 presents
cls
echo                                 presents
cls
echo                                 presents
cls
cls
echo                            F R E e  D 0 /\/\
cls
echo                            F R E e  D 0 /\/\
cls
echo                            F R E e  D 0 /\/\
cls
echo                            F R E e  D 0 /\/\
cls
echo                            F R E e  D 0 /\/\
cls
echo                            F R E e  D 0 /\/\
cls
echo                            F R E e  D 0 /\/\
cls
echo                            F R E e  D 0 /\/\
cls
echo                            F R E e  D 0 /\/\
cls
echo                            F R E e  D 0 /\/\
cls
echo                            F R E e  D 0 /\/\
cls
cls
echo                            F R E e  D 0 /\/\
cls
echo                            F R E e  D 0 /\/\
cls
echo                            F R E e  D 0 /\/\
cls
echo                            F R E e  D 0 /\/\
cls
echo                            F R E e  D 0 /\/\
cls
echo                            F R E e  D 0 /\/\
cls
echo                            F R E e  D 0 /\/\
cls
echo                            F R E e  D 0 /\/\
cls
echo                            F R E e  D 0 /\/\
cls
echo                            F R E e  D 0 /\/\
cls
echo                            F R E e  D 0 /\/\
cls
cls
echo                                                                          
cls
echo                                                                         U
cls
echo                                                                        Uw
cls
echo                                                                       Uwo
cls
echo                                                                      Uwol
cls
echo                                                                     Uwoln
cls
echo                                                                    Uwolni
cls
echo                                                                   Uwolnic 
cls
echo                                                                  Uwolnic w
cls
echo                                                                 Uwolnic ws
cls
echo                                                                Uwolnic wsz
cls
echo                                                               Uwolnic wszy
cls
echo                                                              Uwolnic wszys
cls
echo                                                             Uwolnic wszyst
cls
echo                                                            Uwolnic wszystk
cls
echo                                                           Uwolnic wszystki
cls
echo                                                          Uwolnic wszystkie
cls
echo                                                         Uwolnic wszystkie 
cls
echo                                                        Uwolnic wszystkie m
cls
echo                                                       Uwolnic wszystkie mr
cls
echo                                                      Uwolnic wszystkie mro
cls
echo                                                     Uwolnic wszystkie mroz
cls
echo                                                    Uwolnic wszystkie mrozo
cls
echo                                                   Uwolnic wszystkie mrozon
cls
echo                                                  Uwolnic wszystkie mrozone
cls
echo                                                 Uwolnic wszystkie mrozone 
cls
echo                                                Uwolnic wszystkie mrozone t
cls
echo                                               Uwolnic wszystkie mrozone tr
cls
echo                                              Uwolnic wszystkie mrozone tru
cls
echo                                             Uwolnic wszystkie mrozone trus
cls
echo                                            Uwolnic wszystkie mrozone trusk
cls
echo                                           Uwolnic wszystkie mrozone truska
cls
echo                                          Uwolnic wszystkie mrozone truskaw
cls
echo                                         Uwolnic wszystkie mrozone truskawk
cls
echo                                        Uwolnic wszystkie mrozone truskawki
cls
echo                                       Uwolnic wszystkie mrozone truskawki 
cls
echo                                      Uwolnic wszystkie mrozone truskawki !
cls
echo                                     Uwolnic wszystkie mrozone truskawki !!
cls
echo                                    Uwolnic wszystkie mrozone truskawki !!!
cls
echo                                   Uwolnic wszystkie mrozone truskawki !!!
cls
echo                                  Uwolnic wszystkie mrozone truskawki !!!
cls
echo                                 Uwolnic wszystkie mrozone truskawki !!!
cls
echo                                Uwolnic wszystkie mrozone truskawki !!!
cls
echo                               Uwolnic wszystkie mrozone truskawki !!!
cls
echo                              Uwolnic wszystkie mrozone truskawki !!!
cls
echo                             Uwolnic wszystkie mrozone truskawki !!!
cls
echo                            Uwolnic wszystkie mrozone truskawki !!!
cls
echo                           Uwolnic wszystkie mrozone truskawki !!!
cls
echo                          Uwolnic wszystkie mrozone truskawki !!!
cls
echo                         Uwolnic wszystkie mrozone truskawki !!!
cls
echo                        Uwolnic wszystkie mrozone truskawki !!!
cls
echo                       Uwolnic wszystkie mrozone truskawki !!!
cls
echo                      Uwolnic wszystkie mrozone truskawki !!!
cls
echo                     Uwolnic wszystkie mrozone truskawki !!!
cls
echo                    Uwolnic wszystkie mrozone truskawki !!!
cls
echo                   Uwolnic wszystkie mrozone truskawki !!!
cls
echo                  Uwolnic wszystkie mrozone truskawki !!!
cls
echo                 Uwolnic wszystkie mrozone truskawki !!!
cls
echo                Uwolnic wszystkie mrozone truskawki !!!
cls
echo               Uwolnic wszystkie mrozone truskawki !!!
cls
echo              Uwolnic wszystkie mrozone truskawki !!!
cls
echo             Uwolnic wszystkie mrozone truskawki !!!
cls
echo            Uwolnic wszystkie mrozone truskawki !!!
cls
echo           Uwolnic wszystkie mrozone truskawki !!!
cls
echo          Uwolnic wszystkie mrozone truskawki !!!
cls
echo         Uwolnic wszystkie mrozone truskawki !!!
cls
echo        Uwolnic wszystkie mrozone truskawki !!!
cls
echo       Uwolnic wszystkie mrozone truskawki !!!
cls
echo      Uwolnic wszystkie mrozone truskawki !!!
cls
echo     Uwolnic wszystkie mrozone truskawki !!!
cls
echo    Uwolnic wszystkie mrozone truskawki !!!
cls
echo   Uwolnic wszystkie mrozone truskawki !!!
cls
echo  Uwolnic wszystkie mrozone truskawki !!!
cls
echo Uwolnic wszystkie mrozone truskawki !!!
cls
echo wolnic wszystkie mrozone truskawki !!!
cls
echo olnic wszystkie mrozone truskawki !!!
cls
echo lnic wszystkie mrozone truskawki !!!
cls
echo nic wszystkie mrozone truskawki !!!
cls
echo ic wszystkie mrozone truskawki !!!
cls
echo c wszystkie mrozone truskawki !!!
cls
echo  wszystkie mrozone truskawki !!!
cls
echo wszystkie mrozone truskawki !!!
cls
echo szystkie mrozone truskawki !!!
cls
echo zystkie mrozone truskawki !!!
cls
echo ystkie mrozone truskawki !!!
cls
echo stkie mrozone truskawki !!!
cls
echo tkie mrozone truskawki !!!
cls
echo kie mrozone truskawki !!!
cls
echo ie mrozone truskawki !!!
cls
echo e mrozone truskawki !!!
cls
echo mrozone truskawki !!!
cls
echo rozone truskawki !!!
cls
echo ozone truskawki !!!
cls
echo zone truskawki !!!
cls
echo one truskawki !!!
cls
echo ne truskawki !!!
cls
echo e truskawki !!!
cls
echo  truskawki !!!
cls
echo truskawki !!!
cls
echo ruskawki !!!
cls
echo uskawki !!!
cls
echo skawki !!!
cls
echo kawki !!!
cls
echo awki !!!
cls
echo wki !!!
cls
echo ki !!!
cls
echo i !!!
cls
echo  !!!
cls
echo !!!
cls
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
echo !!
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
echo !!
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
echo !!
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
echo Now it's time for some vectors ...
cls
cls
echo     /------/I
echo    /      / I
echo    -------  I
echo    I      I / 
echo    --------/
cls
echo     /------/I
echo    /      / I
echo    -------  I
echo    I      I / 
echo    --------/
cls
echo     /------/I
echo    /      / I
echo    -------  I
echo    I      I / 
echo    --------/
cls
echo    /------/I
echo    ------- I
echo    I     I I
echo    ------- I
echo    \------\I 
cls
echo    /------/I
echo    ------- I
echo    I     I I
echo    ------- I
echo    \------\I 
cls
echo    /------/I
echo    ------- I
echo    I     I I
echo    ------- I
echo    \------\I 
cls
echo    I\-----\
echo    I \-----\
echo    I I     I 
echo    I I     I
echo    \ I------
cls
echo    I\-----\
echo    I \-----\
echo    I I     I 
echo    I I     I
echo    \ I------
cls
echo    I\-----\
echo    I \-----\
echo    I I     I 
echo    I I     I
echo    \ I------
cls
echo    /------/I
echo    ------- I
echo    I     I I
echo    ------- I
echo    \------\I 
cls
echo    /------/I
echo    ------- I
echo    I     I I
echo    ------- I
echo    \------\I 
cls
echo    /------/I
echo    ------- I
echo    I     I I
echo    ------- I
echo    \------\I 
cls
echo     /------/I
echo    /      / I
echo    -------  I
echo    I      I / 
echo    --------/
cls
echo     /------/I
echo    /      / I
echo    -------  I
echo    I      I / 
echo    --------/
cls
echo     /------/I
echo    /      / I
echo    -------  I
echo    I      I / 
echo    --------/
cls
echo    /------/I
echo    ------- I
echo    I     I I
echo    ------- I
echo    \------\I 
cls
echo    /------/I
echo    ------- I
echo    I     I I
echo    ------- I
echo    \------\I 
cls
echo    /------/I
echo    ------- I
echo    I     I I
echo    ------- I
echo    \------\I 
cls
echo    I\-----\
echo    I \-----\
echo    I I     I 
echo    I I     I
echo    \ I------
cls
echo    I\-----\
echo    I \-----\
echo    I I     I 
echo    I I     I
echo    \ I------
cls
echo    I\-----\
echo    I \-----\
echo    I I     I 
echo    I I     I
echo    \ I------
cls
echo    /------/I
echo    ------- I
echo    I     I I
echo    ------- I
echo    \------\I 
cls
echo    /------/I
echo    ------- I
echo    I     I I
echo    ------- I
echo    \------\I 
cls
echo    /------/I
echo    ------- I
echo    I     I I
echo    ------- I
echo    \------\I 
cls
echo     /------/I
echo    /      / I
echo    -------  I
echo    I      I / 
echo    --------/
cls
echo     /------/I
echo    /      / I
echo    -------  I
echo    I      I / 
echo    --------/
cls
echo     /------/I
echo    /      / I
echo    -------  I
echo    I      I / 
echo    --------/
cls
echo    /------/I
echo    ------- I
echo    I     I I
echo    ------- I
echo    \------\I 
cls
echo    /------/I
echo    ------- I
echo    I     I I
echo    ------- I
echo    \------\I 
cls
echo    /------/I
echo    ------- I
echo    I     I I
echo    ------- I
echo    \------\I 
cls
echo    I\-----\
echo    I \-----\
echo    I I     I 
echo    I I     I
echo    \ I------
cls
echo    I\-----\
echo    I \-----\
echo    I I     I 
echo    I I     I
echo    \ I------
cls
echo    I\-----\
echo    I \-----\
echo    I I     I 
echo    I I     I
echo    \ I------
cls
echo    /------/I
echo    ------- I
echo    I     I I
echo    ------- I
echo    \------\I 
cls
echo    /------/I
echo    ------- I
echo    I     I I
echo    ------- I
echo    \------\I 
cls
echo    /------/I
echo    ------- I
echo    I     I I
echo    ------- I
echo    \------\I 
cls
cls
cls
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
echo And now some textured !
cls
cls
cls
echo   ≤≤≤≤≤
echo  €€€€€±
echo  €€€€€±
cls
echo   ≤≤≤≤≤
echo  €€€€€±
echo  €€€€€±
cls
echo   ≤≤≤≤≤
echo  €€€€€±
echo  €€€€€±
cls
echo  ≤≤≤≤≤≤∞
echo  ≤≤≤≤≤≤∞
echo  €€€€€€∞
cls
echo  ≤≤≤≤≤≤∞
echo  ≤≤≤≤≤≤∞
echo  €€€€€€∞
cls
echo  ≤≤≤≤≤≤∞
echo  ≤≤≤≤≤≤∞
echo  €€€€€€∞
cls
echo  ±±±±∞∞∞
echo  ±±±±∞∞∞
echo  €€€€€€€
cls
echo  ±±±±∞∞∞
echo  ±±±±∞∞∞
echo  €€€€€€€
cls
echo  ±±±±∞∞∞
echo  ±±±±∞∞∞
echo  €€€€€€€
cls
echo  ≤≤≤≤≤≤∞
echo  ≤≤≤≤≤≤∞
echo  €€€€€€∞
cls
echo  ≤≤≤≤≤≤∞
echo  ≤≤≤≤≤≤∞
echo  €€€€€€∞
cls
echo  ≤≤≤≤≤≤∞
echo  ≤≤≤≤≤≤∞
echo  €€€€€€∞
cls
echo   ≤≤≤≤≤
echo  €€€€€±
echo  €€€€€±
cls
echo   ≤≤≤≤≤
echo  €€€€€±
echo  €€€€€±
cls
echo   ≤≤≤≤≤
echo  €€€€€±
echo  €€€€€±
cls
echo  ≤≤≤≤≤≤∞
echo  ≤≤≤≤≤≤∞
echo  €€€€€€∞
cls
echo  ≤≤≤≤≤≤∞
echo  ≤≤≤≤≤≤∞
echo  €€€€€€∞
cls
echo  ≤≤≤≤≤≤∞
echo  ≤≤≤≤≤≤∞
echo  €€€€€€∞
cls
echo  ±±±±∞∞∞
echo  ±±±±∞∞∞
echo  €€€€€€€
cls
echo  ±±±±∞∞∞
echo  ±±±±∞∞∞
echo  €€€€€€€
cls
echo  ±±±±∞∞∞
echo  ±±±±∞∞∞
echo  €€€€€€€
cls
echo  ≤≤≤≤≤≤∞
echo  ≤≤≤≤≤≤∞
echo  €€€€€€∞
cls
echo  ≤≤≤≤≤≤∞
echo  ≤≤≤≤≤≤∞
echo  €€€€€€∞
cls
echo  ≤≤≤≤≤≤∞
echo  ≤≤≤≤≤≤∞
echo  €€€€€€∞
cls
echo   ≤≤≤≤≤
echo  €€€€€±
echo  €€€€€±
cls
echo   ≤≤≤≤≤
echo  €€€€€±
echo  €€€€€±
cls
echo   ≤≤≤≤≤
echo  €€€€€±
echo  €€€€€±
cls
echo  ≤≤≤≤≤≤∞
echo  ≤≤≤≤≤≤∞
echo  €€€€€€∞
cls
echo  ≤≤≤≤≤≤∞
echo  ≤≤≤≤≤≤∞
echo  €€€€€€∞
cls
echo  ≤≤≤≤≤≤∞
echo  ≤≤≤≤≤≤∞
echo  €€€€€€∞
cls
echo  ±±±±∞∞∞
echo  ±±±±∞∞∞
echo  €€€€€€€
cls
echo  ±±±±∞∞∞
echo  ±±±±∞∞∞
echo  €€€€€€€
cls
echo  ±±±±∞∞∞
echo  ±±±±∞∞∞
echo  €€€€€€€
cls
echo  ≤≤≤≤≤≤∞
echo  ≤≤≤≤≤≤∞
echo  €€€€€€∞
cls
echo  ≤≤≤≤≤≤∞
echo  ≤≤≤≤≤≤∞
echo  €€€€€€∞
cls
echo  ≤≤≤≤≤≤∞
echo  ≤≤≤≤≤≤∞
echo  €€€€€€∞
cls
echo   ≤≤≤≤≤
echo  €€€€€±
echo  €€€€€±
cls
echo   ≤≤≤≤≤
echo  €€€€€±
echo  €€€€€±
cls
echo   ≤≤≤≤≤
echo  €€€€€±
echo  €€€€€±
cls
echo  ≤≤≤≤≤≤∞
echo  ≤≤≤≤≤≤∞
echo  €€€€€€∞
cls
echo  ≤≤≤≤≤≤∞
echo  ≤≤≤≤≤≤∞
echo  €€€€€€∞
cls
echo  ≤≤≤≤≤≤∞
echo  ≤≤≤≤≤≤∞
echo  €€€€€€∞
cls
echo  ±±±±∞∞∞
echo  ±±±±∞∞∞
echo  €€€€€€€
cls
echo  ±±±±∞∞∞
echo  ±±±±∞∞∞
echo  €€€€€€€
cls
echo  ±±±±∞∞∞
echo  ±±±±∞∞∞
echo  €€€€€€€
cls
echo  ≤≤≤≤≤≤∞
echo  ≤≤≤≤≤≤∞
echo  €€€€€€∞
cls
echo  ≤≤≤≤≤≤∞
echo  ≤≤≤≤≤≤∞
echo  €€€€€€∞
cls
echo  ≤≤≤≤≤≤∞
echo  ≤≤≤≤≤≤∞
echo  €€€€€€∞
cls
cls
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!
cls
echo And finally PHONG BALL !!!!!!!!!!!

cls
cls
cls
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                   * ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)
cls
echo                                    ----It's here ! (1024x780)

cls
cls
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cls
echo Code,gfx,music by Morbus&Panna Migotka/Muminki
cmodtsr

