char random_text[] = {
"                            Treating for Shock                                  "
"                                                                                "
"     The following material may assist you in treating a victim for shock.      "
"This information is derived from Advanced First Aid & Emergency Care, 2nd       "
"edition, by the American Red Cross. To obtain a copy of this book and to        "
"take instruction in first aid, please contact the local office of the           "
"American Red Cross. They are listed in the white pages of your telephone        "
"book.                                                                           "
"                                                                                "
"                     =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=                          "
"                                                                                "
"Define what is shock                                                            "
"                                                                                "
"                                                                                "
"          Shock is a condition resulting from a depressed state of many         "
"     vital body functions. It can threaten life even though the injuries or     "
"     conditions that caused the depression may not otherwise be fatal. The      "
"     body's vital functions are depressed when there is a loss of blood         "
"     volume, a reduced rate of blood flow or an insufficient supply of          "
"     oxygen. Injury-related shock, commonly referred to as traumatic shock,     "
"     is decidedly different from electric shock, insulin shock, and other       "
"     special forms of shock.                                                    "
"                                                                                "
"          The degrees of shock is increased by abnormal changes in body         "
"     temperature, by poor resistance of the victim to stress, by pain, by       "
"          ____                                                                  "
"         <WW>>>                                                                 "
"        /WWWI; \\                  ____                                          "
"       /WWWWII; \\=====;          /WI; \\                 /\\_                     "
"      /WWWWWII;..      \\_    ___/WI;:. \\              _/M; \\                    "
"     /WWWWWIIIIi;..      \\__/WWWIIII:.. \\____        /MMI:  \\                   "
"   _/WWWWWIIIi;;;:...:   ;\\WWWWWWIIIII;.     \\     /MMWII;   \\                  "
"  /WWWWWIWIiii;;;.:.. :   ;\\WWWWWIII;;;::     \\___/MMWIIII;   \\                 "
" /WWWWWIIIIiii;;::.... :   ;|WWWWWWII;;::.:      :;IMWIIIII;:   \\___            "  
"/WWWWWWWWWIIIIIWIIii;;::;..;\\WWWWWWIII;;;:::...    ;IMIII;;     ::  \\           "
"WWWWWWWWWIIIIIIIIIii;;::.;..;\\WWWWWWWWIIIII;;..  :;IMIII;:::     :    \\         "
"WWWWWWWWWWWWWIIIIIIii;;::..;..;\\WWWWWWWWIIII;::; :::::::::.....::       \\       "
"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%XXXXXXXX"
"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%XXXXXXXXXXX"
"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%XXXXXXXXXXXXXX"
};

unsigned char thea[] = {
"                                                                                " 
"                                %%%%%%%%%%%%%%%%%                               "
"                            %%%%%%%%%%%%%%%/==%%%%%                             "
"                         %%%%%%%%%%%%%%%$$/====;;%%%%                           "
"                       %%%%%%%%%%%%%%qq$$/qqqqq=;%%%%%%                         "
"                      %%%%%%%%%%%%%qqqqq/qqqqqqq;.%%%%%%                        "
"                     %%%|%%%%%%q%qqq_,/'qqqqqqqqq;q%%%%%%                       "
"                    %%%%#\\qqqqqq\\qqqqqqqqqqqqqqqqq;q;%%%%%                      "
"                    /%%,.q\\qqqqqqqqqqqqqqqqqqqqqqqq;q;%%%%%                     "
"                   |%%%,,qqqqqqqqqqqqqqqqqqqqqqqqqqq;qq;%%%%                    "
"                  /.%.,qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq%%%                    "
"                  /%qqqqq_.--==qqqqqqqqqqqqqqqqq==--._qqqq%%%                   "
"               .-|%%'qq/`qqqqqqqqqqqqqqqqqqqqqqqqqqqqq`\\qqq%%|-.                "
"              /qq|%%qq;qqq,,.-..,qqqq/`~`\\qqqq,..-.,,qqq;qq%%|qq\\               "
"              |qq||%qqqq,'q;q(_)q'\\-`qqqqq`-/'q;q(_)q`,qqqq%%|qq|               "
"              |qqq--/---qqqq\\___/qq|\\qqqqqq|qqqq\\___/qq------qqq|               "
"              |qqq|%\\___\\.qqqqqqq_/qq|qqqqqq\\_qqqqqqq./qqqqq|qqq|               "
"              |qqq|qqqqqqq`''-''`qqqq|qqqqqqqq`''-''`qqqqqqq|qqq|               "
"               `'-|qqqqqqqqqqqqqqqqqq|qqqqqqqqqqqqqqqqqqqqqq|_'`                "
"                  \\qqqqqqqqqqqqqqqqq/.qqqqqqqqqqqqqqqqqqqqqq/                   "
"                   |.qqqqqqqqqqqqqq/.qqqqqqqqqqqqqqqqqqqqq.|                    "
"                    ;qqqqqqqqqqqqq|.qqqqqqqqqqqqqqqqqqqqqq;                     "
"                     ;qqqqqqqqqqqq|.qqqqqqqqqqqqqqqqqqqqq;                      "
"                      \\qqqqqqqqqqqq']qqqq[qqqqqqqqqqqqqq/                       "
"                       `;qqqqqqqqqqqqqqqqqqqqqqqqqqqqq;`                        "
"                         '_qqqqqqqqqqqqqqqqqqqqqqqqq_'                          "
"                           \\qqqqqqqqqqqqqqqqqq_qqqq/                            "
"                            ;qqqqq========'''`qqqq;                             "
"                             `.qqqqqqqqqqqqqqqqq.'                              "
"                               ;qqqqqqqqqqqqqqq;                                "
"                                \\.qqqqqqqqqqqq/                                 "
"                                  `--______--`                                  " 
};

unsigned char just_eyes[] = {
"                          ,,.-..,    /`~`\\    ,..-.,,                           "
"                        ,'q;q(_)q'\\-`     `-/'q;q(_)q`,                         "
"                  --/---qqqq\\___/qq|       |qqqq\\___/qq------                   "
"                    \\___\\.qqqqqqq_/         \\_qqqqqqq./                         "
"                          `''-''`             `''-''`                           "
};


char screen0_0[] = {
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"             _____________                                                      "
"           /`             `\\                                                    "
"         .'                 `.                                                  "
"       .`                     `.             ASCII-----                         "
"    ===_                       _===                                             "
"    .`  ```;;;,         ,;;;```  `.          ----by                             "
"   /   ____    `;;;;;;;'    ____   \\                                            "
"  {  /`    `\\  \\       /  /`    `\\  }               SigFlup                     "
"  { |   (0)  |  ;     ;  |   (0)  | }                                           "
"   \\ `-,__,-`] .       . [`-,__,-` /                                            "
"    ?z     /' /         \\ '\\     z?                                             "
"     |`   `  >           <  `   `|         Not the mountains though, that       "
"     |      ;             ;      |               was done by Chris              "
"     |      ,             ,      |                                              "
"     `\\      ,  8o   o8  ,      /`                                              "
"       ;,     \\ `8   8` /     ,;                                                "
"       | \\     \"       \"     / |                                                "
"       `, `                 ` ,`                                                "
"        1  ``=============``  1                                                 "
"         ;      `------`     ;                                                  "
"          `-,_____________,-`                                                   "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"	                                                                         "
};

char screen0_1[] = {
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                        o8o                     "
"                                                       O8`8O                    "
"               Programming by SigFlup                oO8` `8Oo                  "
"                                                     `d`E E`d`                  "
"                                                      1  -  1                   "
"                                                      q`---`q                   "
"                                                    /`       `\\                 "
"                                                   |-----------|                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
"                                                                                "
};

char outer_fucking_space[] = {
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"

 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq-(*)-qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"

 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq__qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq| E|q{@@}q|S |qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq\\/qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"

 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq_qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqq_____qqqqq/` `\\qqqqq_____qqqqqqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqq| OTR |qqq|() ()|qqq| SPE |qqqqqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqq-----qqqqq\\ \" /qqqqq-----qqqqqqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq`+`qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"


 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq ___qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq/`   `\\qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqq_________qqqq|(@) (@)|qqqq_________qqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqq|  OUTER  |qqq|   \"   |qqq|  SPACE  |qqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqq`-------`qqqqq;  _  ;qqqqq`-------`qqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq`._.`qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
};


char bio_back[] = {
 "   .!!``!!.     "
 " .!!`    `!!.   " 
 "!!`  .!!.   !!.."
 ";   !!!!!!   ;!!"
 "!!.  `!!`  .!!``"
 " `!!.    .!!`   "
 "   `!!..!!`     "
 "     ;!!;       "
};



// Sept '06 

char bio[] = {
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq_.-------.qqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq,=``             .qqqqqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq`                  `.qqqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq;          ` -- ._  _ Aqqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq'        .-..__       _|qqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq|        ;      ```-v-`|qqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq|        a             |qqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq --    __|            |qqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq|  |__| ..--._    ..--|qqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq| @       =_) `  ` ( ).qqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq\\               |     .qqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq|               |     'qqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq|         .    |''   qqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq;|      ,`  `-.`   ;qqqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq'  |    ;=_       .`qqqqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq`   |'.      `====|qqqqqqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq|  .'   '          '---__qqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqqqqooo88 -`           ----88888888o--qqqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqqqqo888888888oo---___--oo0000000000000000oqqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqqo88888888888888888/8888888888888888888888o|qqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqqqo88888888888888888|088888888888888888888888oqqqqqqqqqqqqqqq"
 "qqqqqqqqqqqqqqqqqqqq|888888888888888888|8888888888888888888888888qqqqqqqqqqqqqqq"
 "================================================================================"
};

char bio_bio[] = {
 "                                                                                "
 "  Biohertz was a regular at our mn2600 meetings since the beginning.            "
 "  Funniest mook on this side of the planet, I'm tellin' ya. It was a great      "
 "  pleasure having him. He was kind to everyone who came and we miss him.        "
 "                                                                                "
 "  In September 2006 we lost him to heart-failure do to diabetes, he died at the "
 "  young age of 22.                                                              "
 "                                                                                "
 "  It isn't much but with this demo we hope that his memory may live on. Rest    "
 "  In Peace, BIO.                                                                "
 "                                                                                "
 "  /\\    /\\    /\\    /\\    /\\    /\\    /\\    /\\    /\\    /\\    /\\    /\\    /\\    "
 " /  \\  /  \\  /  \\  /  \\  /  \\  /  \\  /  \\  /  \\  /  \\  /  \\  /  \\  /  \\  /  \\  /" 
 "/    \\/    \\/    \\/    \\/    \\/    \\/    \\/    \\/    \\/    \\/    \\/    \\/    \\/ "
};

char mountains[] = {
 "qqqqqqqqqq____qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqqq<WW>>>qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqqq/WWWI; \\qqqqqqqqqqqqqqqqqq____qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
 "qqqqqqq/WWWWII; \\=====;qqqqqqqqqq/WI; \\qqqqqqqqqqqqqqqqq/\\_qqqqqqqqqqqqqqqqqqqqq"
 "qqqqqq/WWWWWII;..      \\_qqqq___/WI;:. \\qqqqqqqqqqqqqq_/M; \\qqqqqqqqqqqqqqqqqqqq"
 "qqqqq/WWWWWIIIIi;..      \\__/WWWIIII:.. \\____qqqqqqqq/MMI:  \\qqqqqqqqqqqqqqqqqqq"
 "qqq_/WWWWWIIIi;;;:...:   ;\\WWWWWWIIIII;.     \\qqqqq/MMWII;   \\qqqqqqqqqqqqqqqqqq"
 "qq/WWWWWIWIiii;;;.:.. :   ;\\WWWWWIII;;;::     \\___/MMWIIII;   \\qqqqqqqqqqqqqqqqq"
 "q/WWWWWIIIIiii;;::.... :   ;|WWWWWWII;;::.:      :;IMWIIIII;:   \\___qqqqqqqqqqqq"  
 "/WWWWWWWWWIIIIIWIIii;;::;..;\\WWWWWWIII;;;:::...    ;IMIII;;     ::  \\qqqqqqqqqqq"
 "WWWWWWWWWIIIIIIIIIii;;::.;..;\\WWWWWWWWIIIII;;..  :;IMIII;:::     :    \\qqqqqqqqq"
 "WWWWWWWWWWWWWIIIIIIii;;::..;..;\\WWWWWWWWIIII;::; :::::::::.....::       \\qqqqqqq"
 "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%XXXXXXXX"
 "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%XXXXXXXXXXX"
 "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%XXXXXXXXXXXXXX"
};

#define ALPHA_WIDTH 	8
#define ALPHA_HEIGHT	8
#define ALPHA_SIZE  (ALPHA_WIDTH * ALPHA_HEIGHT)	

int screen1_current_message;

char screen1_messages[][11] = {
 "GOOD@HELLO@",
 "BLOCKPARTY@",
 "@THIS@@@IS@",
 "@UNDER@a_K@"
};

char alphabet[][ALPHA_SIZE] = {
{
  "@@@@@@@@"
  "@@@@@@@@"
  "@@@@@@@@"
  "@@@@@@@@"
  "@@@@@@@@"
  "@@@@@@@@"
  "@@@@@@@@"
  "@@@@@@@@"
 },{
  "@______@"
  "|   _  |"
  "|.  1  |"
  "|.  _  |"
  "|:  |  |"
  "|::.|: |"
  "`---@--'"
  "@@@@@@@@"
 },{
  "@_____@@"
  "|   _ \\@"
  "|.  1 /@"
  "|.  _ \\@"
  "|:  1  \\"
  "|::..  /"
  "`-----'@"
  "@@@@@@@@"
 },{
  "@______@"
  "|   _  |"
  "|.  1__|"
  "|.  |__@"
  "|:  1  |"
  "|::..  |"
  "`------'"
  "@@@@@@@@"
 },{
  "@_____@@"
  "|   _ \\@" 
  "|.  |  ,"
  "|.  |  |"
  "|:  1  |"
  "|::... '"
  "`-----'@"
  "@@@@@@@@"
 },{
  "@______@"
  "|   _  |"
  "|.  1__|"
  "|.  __)@"
  "|:  1  |"
  "|::.. .|"
  "`------'"
  "@@@@@@@@"
 },{
  "@______@"
  "|   _  |"
  "|.  1__|"
  "|.  __)@"
  "|:  |@@@"
  "|::.|@@@"
  "`---'@@@"
  "@@@@@@@@"
 },{
  "@______@"
  "|   _  |"
  "|.  |__|"
  "|.  |  |"
  "|:  1  |"
  "|::.. .|"
  "`------'"
  "@@@@@@@@"
 },{
  "@___@__@"
  "|   Y  |"
  "|.  1  |"
  "|.  _  |"
  "|:  |  |"
  "|::.|:.|"
  "`---@--'"
  "@@@@@@@@"
 },{
  "@___@@@@"
  "|   |@@@"
  "|.  |@@@"
  "|.  |@@@"
  "|:  |@@@"
  "|::.|@@@"
  "`---'@@@"
  "@@@@@@@@"
 },{
  "@______@"
  "|   _  |"
  "|___|  |"
  "|.  |  |"
  "|:  1  |"
  "|::.. .|"
  "`------'"
  "@@@@@@@@"
 },{
  "@___@__@"
  "|   Y  )"
  "|.  1 /@"
  "|.  _ \\@"
  "|:  |  '"
  "|::.|  |"
  "`---@--'"
  "@@@@@@@@"
 },{
  "@___@@@@"
  "|   |@@@"
  "|.  |@@@"
  "|.  |__@"
  "|:  1  |"
  "|::.. .|"
  "`------'"
  "@@@@@@@@"
 },{
  "@___@__@"
  "|   Y  |"
  "|.     |"
  "|. \\_/ |"
  "|:  |  |"
  "|::.|:.|"
  "`---@--'"
  "@@@@@@@@"
 },{
  "@_____@@"
  "|   _ \\@" 
  "|.  |  |"
  "|.  |  |"
  "|:  |  |"
  "|::.|  |"
  "`---@--'"
  "@@@@@@@@"
 },{
  "@______@"   
  "|   _  |"
  "|.  |  |"
  "|.  |  |"
  "|:  1  |"
  "|::.. .|"
  "`------'"
  "@@@@@@@@"
 },{
  "@______@"
  "|   _  |"
  "|.  1  |"
  "|.  ___|"
  "|:  |@@@"
  "|::.|@@@"
  "`---'@@@"
  "@@@@@@@@"
 },{
  "@______@"
  "|   _  |"
  "|.  |  |"
  "|.  |  |"
  "|:  1  |"
  "|::..\\ |"
  "`-----`'"
  "@@@@@@@@"
 },{
  "@______@"
  "|   _  \\"
  "|.  l  /"
  "|.  _  1"
  "|:  |  |"
  "|::.|:.|"
  "`---@--'"
  "@@@@@@@@"
 },{
  "@______@"
  "|   _  |"
  "|   1__|"
  "|____  |"
  "|:  1  |"
  "|::.. .|"
  "`------'"
  "@@@@@@@@"
 },{
  "@______@"
  "|      |"
  "|.|  | |"
  "`-|. |-'"
  "@@|: |@@"
  "@@|:.|@@"
  "@@`--'@@"
  "@@@@@@@@"
 },{
  "@___@__@"
  "|   Y  |"
  "|.  |  |"
  "|.  |  |"
  "|:  1  |"
  "|::.. .|"
  "`------'"
  "@@@@@@@@"
 },{
  "@___@__@"
  "|   Y  |"
  "|.  |  |"
  "|.  |  |"
  "|:  1  |"
  "@\\:. ./@"
  "@@`--'@@"
  "@@@@@@@@"
 },{
  "@___@__@"
  "|   Y  |"
  "|.  |  |"
  "|. / \\ |"
  "|:     |"
  "|::.|:.|"
  "`---@--'"
  "@@@@@@@@"
 },{
  "@___@__@"
  "(   Y  )"
  "@\\  1 /@"
  "@/  _ \\@"
  ";:  |  ;"
  "|:. |: |"
  "`---@--'"
  "@@@@@@@@"
 },{
  "@___@__@"
  "|   Y  |"
  "|   1  |"
  "@\\_  _/@"
  "@@|: |@@"
  "@@|:.|@@"
  "@@`--'@@"
  "@@@@@@@@"
 },{
  "@______@"
  "|   _  |"
  "|___|  |"
  "@/  __/@"
  "|:  1 \\@"
  "|::..  |"
  "`------'"
  "@@@@@@@@"
 },{
  "@______@"
  "|   _  |"
  "|.  |  |"
  "|.  |  |"
  "|:  1  |"
  "|::.. .|"
  "`------'"
  "@@@@@@@@"
 },{
  "@_____@@"
  "| _   |@"
  "|.|   |@"
  "`-|.  |@"
  "@@|:  |@"
  "@@|::.|@"
  "@@`---'@"
  "@@@@@@@@"
 },{
  "@______@"
  "|      |"
  "|___|  |"
  "@/  __/@"
  "|:  1 \\@"
  "|::..  |"
  "`------'"
  "@@@@@@@@"
 },{
  "@______@"
  "|   _  |"
  "|___|  |"
  "@_(__  |"
  "|:  1  |"
  "|::.. .|"
  "`------'"
  "@@@@@@@@"
 },{
  "@___@__@"
  "|   Y  |"
  "|   |  |"
  "|____  |"
  "@@@@|: |"
  "@@@@|:.|"
  "@@@@`--'"
  "@@@@@@@@"
 },{
  "@______@"
  "|   _  |"
  "|   1__|"
  "|____  |"
  "|:  1  |"
  "|::.. .|"
  "`------'"
  "@@@@@@@@"
 },{
  "@______@"
  "|   _  |"
  "|   1__|"
  "|.    \\@"
  "|:  1  |"
  "|::..  |"
  "`------'"
  "@@@@@@@@"
 },{
  "@______@"
  "|   _  |"
  "|___|  |"
  "@@@/  /@"
  "@@|  |@@"
  "@@|  |@@"
  "@@`--'@@"
  "@@@@@@@@"
 },{
  "@______@"
  "|   _  |"
  "|.  |  |"
  "|.  _  |"
  "|:  1  |"
  "|::.. .|"
  "`------'"
  "@@@@@@@@"
 },{
  "@______@"
  "|   _  |"
  "|   |  |"
  "@\\___  |"
  "|:  1  |"
  "|::.. .|"
  "`------'"
  "@@@@@@@@"                                     
 }
};

