static const char *g_shader_geom_default = ""
#if defined(USE_LD)
"default.geom.glsl"
#else
"layout(points)in;"
"layout(triangle_strip,max_vertices=42)out;"
"in g"
"{"
"vec3 i;"
"vec3 a;"
"vec3 r;"
"vec3 c;"
"vec4 e;"
"float v;"
"float o;"
"mat4 t;"
"}"
"e[1];"
"out g"
"{"
"vec2 e;"
"vec4 c;"
"float t;"
"flat int o;"
"}"
"c;"
"void main()"
"{"
"float o=e[0].e.a*.0001+e[0].o*sin(e[0].e.a)*t[5].r*.00000000006;"
"vec3 v=(cos(o)*e[0].i+sin(o)*e[0].a)*e[0].e.r,i=(cos(o)*e[0].a-sin(o)*e[0].i)*e[0].e.g;"
"c.c=e[0].e;"
"c.t=e[0].v;"
"c.o=int(e[0].o);"
"for(float t=-1;"
"t<=1;"
"t+=.1)"
"{"
"float o=cos(t*1.5)*e[0].o*.0001,a=e[0].e.g/e[0].e.r;"
"c.e=vec2(-1,t*a);"
"gl_Position=e[0].t*vec4(e[0].c+v*(c.e.r+o)+i*t,1);"
"EmitVertex();"
"c.e=vec2(1,t*a);"
"gl_Position=e[0].t*vec4(e[0].c+v*(c.e.r+o)+i*t,1);"
"EmitVertex();"
"}"
"}"
#endif
"";
