v.1.1
         ş Votesheet for issue #1 ş             ÜÜ                     ÜÜÜ
                                              Üß  ş                 Üßß
      Ü²ÛÛÛÛÛÛ°Ü  Ü²Û°ß  Û   Ü²Û°  Ü²ÛÛÛÛÛÛ°Ü şÜ°  ±Û°Ü  Ü²ÛÛÛÛÛÛ°Ü ş Ü²ßß±Û°Ü
     ²ÛÛ°  ±ÛÛ°  ²ÛÛ°   Üß  ²ÛÛ°  ²ÛÛ°  ±ÛÛ°  ²Û°  ±Û°  ²ÛÛ°  ±ÛÛ°   ²Û°  ±Û°
    ²ÛÛ°  ßßßß  ²ÛÛ°  şÜß  ²ÛÛ°  ²ÛÛ°  ßßßß  ²ÛÛÜÜßßß  ²ÛÛ°  ßßßß   ²ÛÛÜÜßßß
   ²ÛÛÛÛ°Ü şÜ  ²ÛÛÛİ ÜÜ   ²ÛÛÛ° ²ÛÛÛÛİ ÜÜÜ  ²ÛÛ°ßß°ÜÜ   ²ÛÛ°ß  ÜÜ  ²ÛÛ°ßß°ÜÜ
  ²ÛÛÛ°    Üß ²ÛÛÛ°ÜÛÛ°ß ²ÛÛÛ°  ²ÛÛÛ°Ü±ÛÛ°ß ²ÛÛ° ±ÛÛ°ß ş²ÛÛÛ°Ü±Û°ß ²ÛÛ° ±ÛÛ°ß
 ßßßßß ÜÜßß  ßßßßßßßßßß ßßßßß    ßßßßßßßßß   ßßß  ßßß Û  ßßßßßßßß   ßßß  ßßß
   ßßßß                                                ßßÜÜ áïç/­p› (`99)
               F L I C K E R - charts magazine

ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
                                   ÜÜÜÜÜ
                      ÜÜ şßßßßßßßßß ÜÜ ²ÛÛÛÜÜ
                     Ş±ß rules      ßß ÛÛÛÜÜÛ±
                      ÛÜ Ü ÜÜÜÜÜÜÜ ÜÛÛÛÛÛ°ßßß

 1. Don't vote for your group, yourself or any other member of your group
 2. Don't vote for Korozone
 3. Don't vote more than one time!
 4. You don't have to fill all entries
                                   ÜÜÜÜÜ
                      ÜÜ şßßßßßßßßß ÜÜ ²ÛÛÛÜÜ
                     Ş±ß about you  ßß ÛÛÛÜÜÛ±
                      ÛÜ Ü ÜÜÜÜÜÜÜ ÜÛÛÛÛÛ°ßßß

                     nickname:      ..................
                     Group(s):      ..................
                     Function(s):   ..................
                     Email Address: ..................

                                   ÜÜÜÜÜ
                      ÜÜ şßßßßßßßßß ÜÜ ²ÛÛÛÜÜ
                     Ş±ß charts pol ßß ÛÛÛÜÜÛ±
                      ÛÜ Ü ÜÜÜÜÜÜÜ ÜÛÛÛÛÛ°ßßß

       F I L L     I F     Y O U ' R E     P O L I S H     D U D E !


 úù:ş Best Polish Group ş:ùú                 úù:ş Best Polish Demo ş:ùú

 1.                                          1.
 2.                                          2.
 3.                                          3.
 4.                                          4.
 5.                                          5.

 úù:ş Best Polish Intro ş:ùú                 úù:ş Best Polish Coder ş:ùú

 1.                                          1.
 2.                                          2.
 3.                                          3.
 4.                                          4.
 5.                                          5.

 úù:ş Best Polish Musician ş:ùú              úù:ş Best Polish Graphician ş:ùú

 1.                                          1.
 2.                                          2.
 3.                                          3.
 4.                                          4.
 5.                                          5.

 úù:ş Best Polish Raytracer ş:ùú             úù:ş Best Polish Swapper ş:ùú

 1.                                          1.
 2.                                          2.
 3.                                          3.
 4.                                          4.
 5.                                          5.

 úù:ş Best Polish Ascii-Maker ş:ùú           úù:ş Best Polish Magazine ş:ùú

 1.                                          1.
 2.                                          2.
 3.                                          3.
 4.                                          4.
 5.                                          5.

 úù:ş Best Polish Text-Writter ş:ùú          úù:ş Best Polish Editor ş:ùú

 1.                                          1.
 2.                                          2.
 3.                                          3.
 4.                                          4.
 5.                                          5.

 úù:ş Best Polish Scene BBS/FTP ş:ùú         úù:ş Best Polish Party ş:ùú

 1.                                          1.
 2.                                          2.
 3.                                          3.
 4.                                          4.
 5.                                          5.

                                   ÜÜÜÜÜ
                      ÜÜ şßßßßßßßßß ÜÜ ²ÛÛÛÜÜ
                     Ş±ß charts ger ßß ÛÛÛÜÜÛ±
                      ÛÜ Ü ÜÜÜÜÜÜÜ ÜÛÛÛÛÛ°ßßß

       F I L L     I F     Y O U ' R E     G E R M A N     D U D E !


 úù:ş Best German Group ş:ùú                 úù:ş Best German Demo ş:ùú

 1.                                          1.
 2.                                          2.
 3.                                          3.
 4.                                          4.
 5.                                          5.

 úù:ş Best German Intro ş:ùú                 úù:ş Best German Coder ş:ùú

 1.                                          1.
 2.                                          2.
 3.                                          3.
 4.                                          4.
 5.                                          5.

 úù:ş Best German Musician ş:ùú              úù:ş Best German Graphician ş:ùú

 1.                                          1.
 2.                                          2.
 3.                                          3.
 4.                                          4.
 5.                                          5.

 úù:ş Best German Raytracer ş:ùú             úù:ş Best German Swapper ş:ùú

 1.                                          1.
 2.                                          2.
 3.                                          3.
 4.                                          4.
 5.                                          5.

 úù:ş Best German Ascii-Maker ş:ùú           úù:ş Best German Magazine ş:ùú

 1.                                          1.
 2.                                          2.
 3.                                          3.
 4.                                          4.
 5.                                          5.

 úù:ş Best German Text-Writter ş:ùú          úù:ş Best German Editor ş:ùú

 1.                                          1.
 2.                                          2.
 3.                                          3.
 4.                                          4.
 5.                                          5.

 úù:ş Best German Scene BBS/FTP ş:ùú         úù:ş Best German Party ş:ùú

 1.                                          1.
 2.                                          2.
 3.                                          3.
 4.                                          4.
 5.                                          5.

                                  ÜÜÜÜÜ
                      ÜÜ şßßßßßßßßßßß ÜÜ ²ÛÛÛÜÜ
                     Ş±ß charts world ßß ÛÛÛÜÜÛ±
                      ÛÜ Ü ÜÜÜÜÜÜÜÜÜ ÜÛÛÛÛÛ°ßßß

                        F I L L     I T !


 úù:ş Best World Group ş:ùú                 úù:ş Best World Demo ş:ùú

 1.                                          1.
 2.                                          2.
 3.                                          3.
 4.                                          4.
 5.                                          5.

 úù:ş Best World Intro ş:ùú                 úù:ş Best World Coder ş:ùú

 1.                                          1.
 2.                                          2.
 3.                                          3.
 4.                                          4.
 5.                                          5.

 úù:ş Best World Musician ş:ùú              úù:ş Best World Graphician ş:ùú

 1.                                          1.
 2.                                          2.
 3.                                          3.
 4.                                          4.
 5.                                          5.

 úù:ş Best World Raytracer ş:ùú             úù:ş Best World Swapper ş:ùú

 1.                                          1.
 2.                                          2.
 3.                                          3.
 4.                                          4.
 5.                                          5.

 úù:ş Best World Ascii-Maker ş:ùú           úù:ş Best World Magazine ş:ùú

 1.                                          1.
 2.                                          2.
 3.                                          3.
 4.                                          4.
 5.                                          5.

 úù:ş Best World Text-Writter ş:ùú          úù:ş Best World Editor ş:ùú

 1.                                          1.
 2.                                          2.
 3.                                          3.
 4.                                          4.
 5.                                          5.

 úù:ş Best World Scene BBS/FTP ş:ùú         úù:ş Best World Party ş:ùú

 1.                                          1.
 2.                                          2.
 3.                                          3.
 4.                                          4.
 5.                                          5.


                      ÜÜ şßßßßßßßßß ÜÜ ²ÛÛÛÜÜ
                     Ş±ß adverts    ßß ÛÛÛÜÜÛ±
                      ÛÜ Ü ÜÜÜÜÜÜÜ ÜÛÛÛÛÛ°ßßß

    U S E     A S     M U C H     S P A C E     A S     Y O U     N E E D




                                   ÜÜÜÜÜ
                      ÜÜ şßßßßßßßßß ÜÜ ²ÛÛÛÜÜ
                     Ş±ß news       ßß ÛÛÛÜÜÛ±
                      ÛÜ Ü ÜÜÜÜÜÜÜ ÜÛÛÛÛÛ°ßßß

    U S E     A S     M U C H     S P A C E     A S     Y O U     N E E D

                          N O      R U M O R S




                                   ÜÜÜÜÜ
                      ÜÜ şßßßßßßßßß ÜÜ ²ÛÛÛÜÜ
                     Ş±ß messages   ßß ÛÛÛÜÜÛ±
                      ÛÜ Ü ÜÜÜÜÜÜÜ ÜÛÛÛÛÛ°ßßß

    U S E     A S     M U C H     S P A C E     A S     Y O U     N E E D




                                   ÜÜÜÜÜ
                      ÜÜ şßßßßßßßßß ÜÜ ²ÛÛÛÜÜ
                     Ş±ß collectors ßß ÛÛÛÜÜÛ±
                      ÛÜ Ü ÜÜÜÜÜÜÜ ÜÛÛÛÛÛ°ßßß


 [ş] SNAIL MAIL

     Binar/Korozone [MAIN EDITOR]          Drif/Korozone [CO-EDITOR]
     Krzysztof Jagoda                      Marek Nowak
     Rakowska 10/43                        Heinz-K”ster
     42-2oo Czestochowa                    Strasse 2a
     POLAND                                24-539 Neumnster
                                           GERMANY
 [ş] E-MAIL

     Binar/Korozone                         Deekay/Grinders^fRC
     binar@kki.net.pl                       deekay@promail.pl

                                   ÜÜÜÜÜ
                      ÜÜ şßßßßßßßßß ÜÜ ²ÛÛÛÜÜ
                     Ş±ß the end    ßß ÛÛÛÜÜÛ±
                      ÛÜ Ü ÜÜÜÜÜÜÜ ÜÛÛÛÛÛ°ßßß