#define AEND    0
#define AWAIT   1
#define AJMP    2
#define AFADE   3
#define ASIZE   4
#define APROC   5
#define AADJUST 6
#define ANODDIR 7
#define ANODPOS 8
#define ANODOFS 9
#define ADIR    10
#define APOS    11
#define AOFS    12
#define ADDIR   13
#define ADPOS   14
#define ADOFS   15
#define AQUIT   16

#define MMOVEX   1000
#define MMOVEY   1001
#define MMOVEZ   1002
#define MMIRRORX 0
#define MMIRRORY 2
#define MMIRRORZ 4
#define MVERTEX  1
#define MQUIT    3
#define MQUITS   7
#define MNEW     11
#define MNEWS    15

#define P3       1
#define P33      2
#define P4       3
