



   ÜßßÛßßßßßÜ                      Û          Û
      Û      Û                     Û          Û   ß
      Û     Û   ÜßßßÜ  ÜßßßÜ  ÛßßÜ  Û  Û   Û ßßÛß Û    ÛßßÜ  ÛÜßßÜ
       ÛßßÛß   Û Üßß    ßÜÜ  Û    Û Û  ßÜ  ßÜ  Û  ßÜ  Û    Û ßÜ   Û
       Û  ßÜ  Ü Û    Ü Ü   ßÜ Û   Û Û   Û   Û  Û   Û   Û   Û  Û   Û
      ß ß   ßß   ßßßß   ßßßß   ßßß   ßß  ßßß ß  ßß  ßß  ßßß   ß    ß

                            PùRùEùSùEùNùTùS

                                   A

                            Contribution to

                               EXE Party

                         4K intro  competition

                           T H E   M O U S E

                                  by

                               Cameron

                       ------------------------

                       Requirements : - 386dx/33
                                      - VGA
                                      - 384k RAM
                                      - good taste

                       ------------------------







