; HSC fm playey, ya know, the one by chicken! :)
; this just defines the externs for using it, see HSCTRACK.DOC ok??
; Done 18th Dec 1993 - Phil C.

EXTRN HSCPLAYER:FAR       ; Define the playing function

;I wont do the other data stuff! (unless its here, in which case I lied!)

;EXTRN HSC_Equalizer:byte  ; Dont think this will work.....
EXTRN HSC_Playing:byte
EXTRN HSC_Track:byte
EXTRN HSC_Position:byte

