; instrument data: program, volume
instrm  db      44,7Fh		; rythm instrument at beginning and end
	db      38,7Fh		; bass for background
	db      21,5Fh		; choir
	db      21,4Fh		; softer choir
	db      50,4Fh		; fast part chords
	db      80,7Fh		; fast part melody
	db      80,7Fh          ; and with vibrato
	db      80,7Fh		; slower part melody
	db      80,7Fh		; slower part other melody
	db      0,7Fh           ; PowerRythm
