; instrument data: program, volume
instrm  db      48,7Fh          ; rythm instrument at beginning and end
        db      90,5Fh          ; bass for background
        db      52,5Fh          ; choir
        db      52,4Fh          ; softer choir
        db      51,5Fh          ; fast part chords
	db      80,7Fh		; fast part melody
        db      80,7Fh          ; and with vibrato
	db	81,7Fh		; slower part melody
	db	62,7Fh		; slower part other melody
	db	16,7Fh	    	; PowerRythm
