kenny_body_sec  db sElipse,122,155,98,61
                db sRectangle,0,0,250,210
                db sElipse,122,238,67,110
                db sRectangle,48,180,68,255
                db SRectangle,176,180,228,255
                db sRectangle,0,0,255,157
                db sElipse,68,197,18,18
                db sFill,1,68,197
                db sElipse,178,197,18,18
                db sFill,1,178,197

                db sVLine,209,224,82
                db sVLine,209,224,163

                db sLine,78,224,168,224
                db sLine,78,225,168,225

                db sFill,1,122,220
                db sVLine,215,225,122

                db sElipse,156,105,28,22
                db sElipse,95,104,26,20
                db sRectangle,58,75,99,129
                db sRectangle,144,75,185,130




                db sElipse,77,106,74,46
                db sElipse,166,107,74,46
                db sRectangle,0,0,255,70
                db sRectangle,0,144,255,155
                db sRectangle,0,0,40,255
                db sRectangle,201,0,255,255

;	//datos para kenny
;	// 0 elipse borde negro
;	// 1 rectangulo relleno blanco
;	// 2 relleno de color
;	// 3 linea vertical negra
;	// 4 linea arbitraria negra
;	// 5 punto negro
;	// 6 termina
;			5,99,123-offy,
;			5,98,123-offy,

		db sElipse,122,108,68,68
		db sElipse,122,108,67,67
		db sElipse,122,112,51,43
		db sElipse,121,107,45,38

		db sFill ,1,122,190
		db sFill ,1,122,170
		db sFill ,1,122,150

		db sFill ,2,85,110
		db sFill ,2,160,110
		db sFill ,3,122,130

		db sLine ,112,167,121,144
		db sLine ,121,144,124,171
		db sVLine,176,211,122

                db sFill,13,110,105
                db sElipse,110,105,2,2
                db sFill,13,137,105
                db sElipse,137,105,2,2


                db sEnd
                

bocadillo_sec db sElipse,144,69,80,40
              db sFill,12,144,69

              db sElipse,50,104,12,4
              db sFill,12,50,104

              db sElipse,34,112,7,3
              db sFill,12,34,112

              db sElipse,21,118,4,2
              db sFill,12,21,118

              db sEnd


