SetTimer	MACRO
	cli
	mov	al,36h
	out	43h,al
	mov	ax,1193181/182
	out	40h,al
	mov	al,ah
	out	40h,al

	mov	ax,cs
	shl	eax,16
	mov	ax,offset New8h
	xchg	eax,fs:[8*4]
	mov	[Old8h],eax
	sti
ENDM
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ResetTimer	MACRO
	cli
	mov	al,36h
	out	43h,al
	xor	al,al
	out	40h,al
	out	40h,al

	xor	ax,ax
	mov	fs,ax
	mov	eax,Old8h
	mov	fs:[8*4],eax
	sti
ENDM
