#put path to ims here!
imspath=..

dest = imslasse
objects = no87.obj roto.obj wobble.obj fire.obj lrbfiles.obj keyboard.obj fmatrixa.obj polygons.obj polytext.obj spacea.obj texgena.obj tunnel.obj space.obj objgen.obj pal.obj texgen.obj main.obj vector.obj fx.obj
libraries = ims.lib binfile.lib
libpath=$(imspath)

!include $(imspath)\makeexe.mak
