/* Generated by SC2-Tools */
#include "bitmap.h"
extern struct RLEBitmap bmp_coquet;
extern struct RLEBitmap bmp_gargamel;
extern struct RLEBitmap bmp_grand;
extern struct RLEBitmap bmp_knights;
extern struct RLEBitmap bmp_smurfette;
extern struct RLEBitmap bmp_font;
extern struct RLEBitmap bmp_grognon;
extern struct RLEBitmap bmp_title;
extern unsigned char data_module[32187];
