default:
	nasm -f bin -O999 kpara8.asm -o kpara8.bin
	./MakeFloppyImage.exe bochs/test.flp kpara8.bin

mov:
	nasm -f bin -O999 demo.asm -o kpara8.bin
	./MakeFloppyImage.exe bochs/test.flp kpara8.bin
