@echo This intro funguje v dose, trochu vo windozoch (ale moc nie, len chvilu)...
@pause
@tov
@echo subway underground party 1999
@echo 
@echo v pozdravoch nie su uplne vsetci ludia
@echo ak ma niekto zaujem byt tiez pozdravovany
@echo staci sa dopisat na koniec zoznamu do zdrojaku (tov.asm, riadok 220)
@echo zvysit konstantu greetsnum a prekompilovat (odporucam tasm3.1, tlink4.0)
@echo rovnako lahko sa moze kludne napisat ako autor, zmenit nazov intra, zmenit
@echo niektore efekty, dorobit hudbu, podporu 3d kariet, vystup na tlaciaren,
@echo true color a podobne zb!we43!#@4`~.
@pause