copy ..\hge\intro1 intro1
copy ..\hge\intro2 intro2
copy ..\hge\intro7 intro7
copy ..\hge\intro6 intro6
copy ..\hge\intro5 intro5
copy ..\hge\intro9 intro9
copy ..\hge\loppu loppu
copy ..\hge\demotus demotus
copy ..\hge\demotus2 demotus2
raw2h intro1 intro1.h
raw2h intro2 intro2.h
raw2h intro5 intro5.h
raw2h intro6 intro6.h
raw2h intro7 intro7.h
raw2h intro9 intro9.h
raw2h loppu loppu.h
raw2h demotus demotus.h
raw2h demotus2 demotus2.h
raw2h default.hf font.h
raw2h musa.xm musa.h
