@ECHO OFF
PATH=C:\DYRESEX\ANIMALS\ANIM;C:\CHILDSEX\ABUSE;C:\BADBLOCK\;C:\DOS;
ULTRINIT.EXE
SET ULTRADIR=C:\UTILS\ULTRASND
SET BLASTER=A220 I7 D1 T1

REM Dagen derp†. En kort ting af Rasmus (Macaw).
REM Jeg vil gerne. Mon jeg m†? - Jeg tror ikke det er tilladt. 4mb MPG film
REM i en intro. Det er vist ikke helt tilladt. Nej - Det kan vist ikke passe.
REM :) Source kode kommer. Men f›rst n†r den er interessant. Dvs. n†r jeg har
REM kommenteret den (er der nogen der har noget pot?). Jeg ville gerne. Men
REM jeg vil ikke k›be det af S›ren (flower). Hans afkom er d†rligt.
REM Rasmus. (macaw@rebels.org);


REM void object3d::new_engine(init the world as we know it);
REM {
REM     int     neger_ib;
REM     vertex  neger_ib_faetter;
REM     faces   neger_ib_liderlige_kusiner;
REM
REM     while (neger_ibs_faetter_er_dum)
REM     {
REM             faces++; // tilf›j flere unger
REM             rotate(&(*faces)&255);  // jaja, den kan godt kompiles med DASK-WCC8468465.EXE
REM     }
REM }

echo dansk:
echo s‘t tabulator til 10, eller virker det ikke, ›vb›v!
echo.
echo in english:
echo please set tab to 10 spaces. otherwise it wont work. wearmp!



echo.
echo.
echo tribute to anne. 14 years old :)
pause
type acd-sl.nfo|more
acd-sl.exe
cls
echo  __                __ ___________    _________   _________________
echo    \              /  /      __   \      |       |
echo     \            / _/       /     \_    |       |
echo      \          /  |       /       |    |       |
echo       \        /   |      /        |    |       |-----------|
echo        \      /    |_   _/        _|    |       |                _
echo         \    /     _/             \_    |       |                |
echo          \  /      \               /    |       |                |
echo           \/        \_____________/     |       |________________|
echo.
echo.
echo now go and do it.
pause
