# File generated by kdevelop's qmake manager.
# -------------------------------------------
# Subdir relative project main directory: .
# Target is a subdirs project

CONFIG += release \
          ordered
TEMPLATE = subdirs
SUBDIRS += libmapprox \
           kmapprox \
 demo
