#ifndef PARTICLE_CONFH_H
#define PARTICLE_CONFH_H

//#define NUM_LINES	400000
#define NUM_LINES	20000
#define NUM_VERTICES_PER_LINE	16
#define NUM_ADJACENCY_VERTS		2
#define NUM_ADJACENCY_VERTS2	4
#define NUM_ADJACENCY_VERTS2PLUS1	5

#endif
