externdef _imp__AddAtomA@4:PTR pr1
AddAtom equ <_imp__AddAtomA@4>

externdef _imp__AddConsoleAliasA@12:PTR pr3
AddConsoleAlias equ <_imp__AddConsoleAliasA@12>

externdef _imp__AllocConsole@0:PTR pr0
AllocConsole equ <_imp__AllocConsole@0>

externdef _imp__AreFileApisANSI@0:PTR pr0
AreFileApisANSI equ <_imp__AreFileApisANSI@0>

externdef _imp__AssignProcessToJobObject@8:PTR pr2
AssignProcessToJobObject equ <_imp__AssignProcessToJobObject@8>

externdef _imp__BackupRead@28:PTR pr7
BackupRead equ <_imp__BackupRead@28>

externdef _imp__BackupSeek@24:PTR pr6
BackupSeek equ <_imp__BackupSeek@24>

externdef _imp__BackupWrite@28:PTR pr7
BackupWrite equ <_imp__BackupWrite@28>

externdef _imp__BaseAttachCompleteThunk@0:PTR pr0
BaseAttachCompleteThunk equ <_imp__BaseAttachCompleteThunk@0>

externdef _imp__Beep@8:PTR pr2
Beep equ <_imp__Beep@8>

externdef _imp__BeginUpdateResourceA@8:PTR pr2
BeginUpdateResource equ <_imp__BeginUpdateResourceA@8>

externdef _imp__BuildCommDCBA@8:PTR pr2
BuildCommDCB equ <_imp__BuildCommDCBA@8>

externdef _imp__BuildCommDCBAndTimeoutsA@12:PTR pr3
BuildCommDCBAndTimeouts equ <_imp__BuildCommDCBAndTimeoutsA@12>

externdef _imp__CallNamedPipeA@28:PTR pr7
CallNamedPipe equ <_imp__CallNamedPipeA@28>

externdef _imp__CancelIo@4:PTR pr1
CancelIo equ <_imp__CancelIo@4>

externdef _imp__CancelWaitableTimer@4:PTR pr1
CancelWaitableTimer equ <_imp__CancelWaitableTimer@4>

externdef _imp__ClearCommBreak@4:PTR pr1
ClearCommBreak equ <_imp__ClearCommBreak@4>

externdef _imp__ClearCommError@12:PTR pr3
ClearCommError equ <_imp__ClearCommError@12>

externdef _imp__CloseConsoleHandle@4:PTR pr1
CloseConsoleHandle equ <_imp__CloseConsoleHandle@4>

externdef _imp__CloseHandle@4:PTR pr1
CloseHandle equ <_imp__CloseHandle@4>

externdef _imp__CloseProfileUserMapping@0:PTR pr0
CloseProfileUserMapping equ <_imp__CloseProfileUserMapping@0>

externdef _imp__CmdBatNotification@4:PTR pr1
CmdBatNotification equ <_imp__CmdBatNotification@4>

externdef _imp__CommConfigDialogA@12:PTR pr3
CommConfigDialog equ <_imp__CommConfigDialogA@12>

externdef _imp__CompareFileTime@8:PTR pr2
CompareFileTime equ <_imp__CompareFileTime@8>

externdef _imp__CompareStringA@24:PTR pr6
CompareString equ <_imp__CompareStringA@24>

externdef _imp__ConnectNamedPipe@8:PTR pr2
ConnectNamedPipe equ <_imp__ConnectNamedPipe@8>

externdef _imp__ConsoleMenuControl@12:PTR pr3
ConsoleMenuControl equ <_imp__ConsoleMenuControl@12>

externdef _imp__ContinueDebugEvent@12:PTR pr3
ContinueDebugEvent equ <_imp__ContinueDebugEvent@12>

externdef _imp__ConvertDefaultLocale@4:PTR pr1
ConvertDefaultLocale equ <_imp__ConvertDefaultLocale@4>

externdef _imp__ConvertThreadToFiber@4:PTR pr1
ConvertThreadToFiber equ <_imp__ConvertThreadToFiber@4>

externdef _imp__CopyFileA@12:PTR pr3
CopyFile equ <_imp__CopyFileA@12>

externdef _imp__CopyFileExA@24:PTR pr6
CopyFileEx equ <_imp__CopyFileExA@24>

externdef _imp__CreateConsoleScreenBuffer@20:PTR pr5
CreateConsoleScreenBuffer equ <_imp__CreateConsoleScreenBuffer@20>

externdef _imp__CreateDirectoryA@8:PTR pr2
CreateDirectory equ <_imp__CreateDirectoryA@8>

externdef _imp__CreateDirectoryExA@12:PTR pr3
CreateDirectoryEx equ <_imp__CreateDirectoryExA@12>

externdef _imp__CreateEventA@16:PTR pr4
CreateEvent equ <_imp__CreateEventA@16>

externdef _imp__CreateFiber@12:PTR pr3
CreateFiber equ <_imp__CreateFiber@12>

externdef _imp__CreateFileA@28:PTR pr7
CreateFile equ <_imp__CreateFileA@28>

externdef _imp__CreateFileMappingA@24:PTR pr6
CreateFileMapping equ <_imp__CreateFileMappingA@24>

externdef _imp__CreateHardLinkA@12:PTR pr3
CreateHardLink equ <_imp__CreateHardLinkA@12>

externdef _imp__CreateIoCompletionPort@16:PTR pr4
CreateIoCompletionPort equ <_imp__CreateIoCompletionPort@16>

externdef _imp__CreateJobObjectA@8:PTR pr2
CreateJobObject equ <_imp__CreateJobObjectA@8>

externdef _imp__CreateMailslotA@16:PTR pr4
CreateMailslot equ <_imp__CreateMailslotA@16>

externdef _imp__CreateMutexA@12:PTR pr3
CreateMutex equ <_imp__CreateMutexA@12>

externdef _imp__CreateNamedPipeA@32:PTR pr8
CreateNamedPipe equ <_imp__CreateNamedPipeA@32>

externdef _imp__CreatePipe@16:PTR pr4
CreatePipe equ <_imp__CreatePipe@16>

externdef _imp__CreateProcessA@40:PTR pr10
CreateProcess equ <_imp__CreateProcessA@40>

externdef _imp__CreateRemoteThread@28:PTR pr7
CreateRemoteThread equ <_imp__CreateRemoteThread@28>

externdef _imp__CreateSemaphoreA@16:PTR pr4
CreateSemaphore equ <_imp__CreateSemaphoreA@16>

externdef _imp__CreateTapePartition@16:PTR pr4
CreateTapePartition equ <_imp__CreateTapePartition@16>

externdef _imp__CreateThread@24:PTR pr6
CreateThread equ <_imp__CreateThread@24>

externdef _imp__CreateToolhelp32Snapshot@8:PTR pr2
CreateToolhelp32Snapshot equ <_imp__CreateToolhelp32Snapshot@8>

externdef _imp__CreateVirtualBuffer@12:PTR pr3
CreateVirtualBuffer equ <_imp__CreateVirtualBuffer@12>

externdef _imp__CreateWaitableTimerA@12:PTR pr3
CreateWaitableTimer equ <_imp__CreateWaitableTimerA@12>

externdef _imp__DebugActiveProcess@4:PTR pr1
DebugActiveProcess equ <_imp__DebugActiveProcess@4>

externdef _imp__DebugBreak@0:PTR pr0
DebugBreak equ <_imp__DebugBreak@0>

externdef _imp__DefineDosDeviceA@12:PTR pr3
DefineDosDevice equ <_imp__DefineDosDeviceA@12>

externdef _imp__DeleteAtom@4:PTR pr1
DeleteAtom equ <_imp__DeleteAtom@4>

externdef _imp__DeleteCriticalSection@4:PTR pr1
DeleteCriticalSection equ <_imp__DeleteCriticalSection@4>

externdef _imp__DeleteFiber@4:PTR pr1
DeleteFiber equ <_imp__DeleteFiber@4>

externdef _imp__DeleteFileA@4:PTR pr1
DeleteFile equ <_imp__DeleteFileA@4>

externdef _imp__DeviceIoControl@32:PTR pr8
DeviceIoControl equ <_imp__DeviceIoControl@32>

externdef _imp__DisableThreadLibraryCalls@4:PTR pr1
DisableThreadLibraryCalls equ <_imp__DisableThreadLibraryCalls@4>

externdef _imp__DisconnectNamedPipe@4:PTR pr1
DisconnectNamedPipe equ <_imp__DisconnectNamedPipe@4>

externdef _imp__DosDateTimeToFileTime@12:PTR pr3
DosDateTimeToFileTime equ <_imp__DosDateTimeToFileTime@12>

externdef _imp__DuplicateConsoleHandle@16:PTR pr4
DuplicateConsoleHandle equ <_imp__DuplicateConsoleHandle@16>

externdef _imp__DuplicateHandle@28:PTR pr7
DuplicateHandle equ <_imp__DuplicateHandle@28>

externdef _imp__EndUpdateResourceA@8:PTR pr2
EndUpdateResource equ <_imp__EndUpdateResourceA@8>

externdef _imp__EnterCriticalSection@4:PTR pr1
EnterCriticalSection equ <_imp__EnterCriticalSection@4>

externdef _imp__EnumCalendarInfoA@16:PTR pr4
EnumCalendarInfo equ <_imp__EnumCalendarInfoA@16>

externdef _imp__EnumCalendarInfoExA@16:PTR pr4
EnumCalendarInfoEx equ <_imp__EnumCalendarInfoExA@16>

externdef _imp__EnumDateFormatsA@12:PTR pr3
EnumDateFormats equ <_imp__EnumDateFormatsA@12>

externdef _imp__EnumDateFormatsExA@12:PTR pr3
EnumDateFormatsEx equ <_imp__EnumDateFormatsExA@12>

externdef _imp__EnumResourceLanguagesA@20:PTR pr5
EnumResourceLanguages equ <_imp__EnumResourceLanguagesA@20>

externdef _imp__EnumResourceNamesA@16:PTR pr4
EnumResourceNames equ <_imp__EnumResourceNamesA@16>

externdef _imp__EnumResourceTypesA@12:PTR pr3
EnumResourceTypes equ <_imp__EnumResourceTypesA@12>

externdef _imp__EnumSystemCodePagesA@8:PTR pr2
EnumSystemCodePages equ <_imp__EnumSystemCodePagesA@8>

externdef _imp__EnumSystemLocalesA@8:PTR pr2
EnumSystemLocales equ <_imp__EnumSystemLocalesA@8>

externdef _imp__EnumTimeFormatsA@12:PTR pr3
EnumTimeFormats equ <_imp__EnumTimeFormatsA@12>

externdef _imp__EraseTape@12:PTR pr3
EraseTape equ <_imp__EraseTape@12>

externdef _imp__EscapeCommFunction@8:PTR pr2
EscapeCommFunction equ <_imp__EscapeCommFunction@8>

externdef _imp__ExitProcess@4:PTR pr1
ExitProcess equ <_imp__ExitProcess@4>

externdef _imp__ExitThread@4:PTR pr1
ExitThread equ <_imp__ExitThread@4>

externdef _imp__ExitVDM@8:PTR pr2
ExitVDM equ <_imp__ExitVDM@8>

externdef _imp__ExpandEnvironmentStringsA@12:PTR pr3
ExpandEnvironmentStrings equ <_imp__ExpandEnvironmentStringsA@12>

externdef _imp__ExpungeConsoleCommandHistoryA@4:PTR pr1
ExpungeConsoleCommandHistory equ <_imp__ExpungeConsoleCommandHistoryA@4>

externdef _imp__ExtendVirtualBuffer@8:PTR pr2
ExtendVirtualBuffer equ <_imp__ExtendVirtualBuffer@8>

externdef _imp__FatalAppExitA@8:PTR pr2
FatalAppExit equ <_imp__FatalAppExitA@8>

externdef _imp__FatalExit@4:PTR pr1
FatalExit equ <_imp__FatalExit@4>

externdef _imp__FileTimeToDosDateTime@12:PTR pr3
FileTimeToDosDateTime equ <_imp__FileTimeToDosDateTime@12>

externdef _imp__FileTimeToLocalFileTime@8:PTR pr2
FileTimeToLocalFileTime equ <_imp__FileTimeToLocalFileTime@8>

externdef _imp__FileTimeToSystemTime@8:PTR pr2
FileTimeToSystemTime equ <_imp__FileTimeToSystemTime@8>

externdef _imp__FillConsoleOutputAttribute@20:PTR pr5
FillConsoleOutputAttribute equ <_imp__FillConsoleOutputAttribute@20>

externdef _imp__FillConsoleOutputCharacterA@20:PTR pr5
FillConsoleOutputCharacter equ <_imp__FillConsoleOutputCharacterA@20>

externdef _imp__FindAtomA@4:PTR pr1
FindAtom equ <_imp__FindAtomA@4>

externdef _imp__FindClose@4:PTR pr1
FindClose equ <_imp__FindClose@4>

externdef _imp__FindCloseChangeNotification@4:PTR pr1
FindCloseChangeNotification equ <_imp__FindCloseChangeNotification@4>

externdef _imp__FindFirstChangeNotificationA@12:PTR pr3
FindFirstChangeNotification equ <_imp__FindFirstChangeNotificationA@12>

externdef _imp__FindFirstFileA@8:PTR pr2
FindFirstFile equ <_imp__FindFirstFileA@8>

externdef _imp__FindFirstFileExA@24:PTR pr6
FindFirstFileEx equ <_imp__FindFirstFileExA@24>

externdef _imp__FindNextChangeNotification@4:PTR pr1
FindNextChangeNotification equ <_imp__FindNextChangeNotification@4>

externdef _imp__FindNextFileA@8:PTR pr2
FindNextFile equ <_imp__FindNextFileA@8>

externdef _imp__FindResourceA@12:PTR pr3
FindResource equ <_imp__FindResourceA@12>

externdef _imp__FindResourceExA@16:PTR pr4
FindResourceEx equ <_imp__FindResourceExA@16>

externdef _imp__FlushConsoleInputBuffer@4:PTR pr1
FlushConsoleInputBuffer equ <_imp__FlushConsoleInputBuffer@4>

externdef _imp__FlushFileBuffers@4:PTR pr1
FlushFileBuffers equ <_imp__FlushFileBuffers@4>

externdef _imp__FlushInstructionCache@12:PTR pr3
FlushInstructionCache equ <_imp__FlushInstructionCache@12>

externdef _imp__FlushViewOfFile@8:PTR pr2
FlushViewOfFile equ <_imp__FlushViewOfFile@8>

externdef _imp__FoldStringA@20:PTR pr5
FoldString equ <_imp__FoldStringA@20>

externdef _imp__FormatMessageA@28:PTR pr7
FormatMessage equ <_imp__FormatMessageA@28>

externdef _imp__FreeConsole@0:PTR pr0
FreeConsole equ <_imp__FreeConsole@0>

externdef _imp__FreeEnvironmentStringsA@4:PTR pr1
FreeEnvironmentStrings equ <_imp__FreeEnvironmentStringsA@4>

externdef _imp__FreeLibrary@4:PTR pr1
FreeLibrary equ <_imp__FreeLibrary@4>

externdef _imp__FreeLibraryAndExitThread@8:PTR pr2
FreeLibraryAndExitThread equ <_imp__FreeLibraryAndExitThread@8>

externdef _imp__FreeResource@4:PTR pr1
FreeResource equ <_imp__FreeResource@4>

externdef _imp__FreeVirtualBuffer@4:PTR pr1
FreeVirtualBuffer equ <_imp__FreeVirtualBuffer@4>

externdef _imp__GenerateConsoleCtrlEvent@8:PTR pr2
GenerateConsoleCtrlEvent equ <_imp__GenerateConsoleCtrlEvent@8>

externdef _imp__GetACP@0:PTR pr0
GetACP equ <_imp__GetACP@0>

externdef _imp__GetAtomNameA@12:PTR pr3
GetAtomName equ <_imp__GetAtomNameA@12>

externdef _imp__GetBinaryTypeA@8:PTR pr2
GetBinaryType equ <_imp__GetBinaryTypeA@8>

externdef _imp__GetCPInfo@8:PTR pr2
GetCPInfo equ <_imp__GetCPInfo@8>

externdef _imp__GetCPInfoExA@12:PTR pr3
GetCPInfoEx equ <_imp__GetCPInfoExA@12>

externdef _imp__GetCommConfig@12:PTR pr3
GetCommConfig equ <_imp__GetCommConfig@12>

externdef _imp__GetCommMask@8:PTR pr2
GetCommMask equ <_imp__GetCommMask@8>

externdef _imp__GetCommModemStatus@8:PTR pr2
GetCommModemStatus equ <_imp__GetCommModemStatus@8>

externdef _imp__GetCommProperties@8:PTR pr2
GetCommProperties equ <_imp__GetCommProperties@8>

externdef _imp__GetCommState@8:PTR pr2
GetCommState equ <_imp__GetCommState@8>

externdef _imp__GetCommTimeouts@8:PTR pr2
GetCommTimeouts equ <_imp__GetCommTimeouts@8>

externdef _imp__GetCommandLineA@0:PTR pr0
GetCommandLine equ <_imp__GetCommandLineA@0>

externdef _imp__GetCompressedFileSizeA@8:PTR pr2
GetCompressedFileSize equ <_imp__GetCompressedFileSizeA@8>

externdef _imp__GetComputerNameA@8:PTR pr2
GetComputerName equ <_imp__GetComputerNameA@8>

externdef _imp__GetConsoleAliasA@16:PTR pr4
GetConsoleAlias equ <_imp__GetConsoleAliasA@16>

externdef _imp__GetConsoleAliasExesA@8:PTR pr2
GetConsoleAliasExes equ <_imp__GetConsoleAliasExesA@8>

externdef _imp__GetConsoleAliasExesLengthA@0:PTR pr0
GetConsoleAliasExesLength equ <_imp__GetConsoleAliasExesLengthA@0>

externdef _imp__GetConsoleAliasesA@12:PTR pr3
GetConsoleAliases equ <_imp__GetConsoleAliasesA@12>

externdef _imp__GetConsoleAliasesLengthA@4:PTR pr1
GetConsoleAliasesLength equ <_imp__GetConsoleAliasesLengthA@4>

externdef _imp__GetConsoleCP@0:PTR pr0
GetConsoleCP equ <_imp__GetConsoleCP@0>

externdef _imp__GetConsoleCommandHistoryA@12:PTR pr3
GetConsoleCommandHistory equ <_imp__GetConsoleCommandHistoryA@12>

externdef _imp__GetConsoleCommandHistoryLengthA@4:PTR pr1
GetConsoleCommandHistoryLength equ <_imp__GetConsoleCommandHistoryLengthA@4>

externdef _imp__GetConsoleCursorInfo@8:PTR pr2
GetConsoleCursorInfo equ <_imp__GetConsoleCursorInfo@8>

externdef _imp__GetConsoleDisplayMode@4:PTR pr1
GetConsoleDisplayMode equ <_imp__GetConsoleDisplayMode@4>

externdef _imp__GetConsoleFontInfo@16:PTR pr4
GetConsoleFontInfo equ <_imp__GetConsoleFontInfo@16>

externdef _imp__GetConsoleFontSize@8:PTR pr2
GetConsoleFontSize equ <_imp__GetConsoleFontSize@8>

externdef _imp__GetConsoleHardwareState@12:PTR pr3
GetConsoleHardwareState equ <_imp__GetConsoleHardwareState@12>

externdef _imp__GetConsoleInputExeNameA@8:PTR pr2
GetConsoleInputExeName equ <_imp__GetConsoleInputExeNameA@8>

externdef _imp__GetConsoleInputWaitHandle@0:PTR pr0
GetConsoleInputWaitHandle equ <_imp__GetConsoleInputWaitHandle@0>

externdef _imp__GetConsoleKeyboardLayoutNameA@4:PTR pr1
GetConsoleKeyboardLayoutName equ <_imp__GetConsoleKeyboardLayoutNameA@4>

externdef _imp__GetConsoleMode@8:PTR pr2
GetConsoleMode equ <_imp__GetConsoleMode@8>

externdef _imp__GetConsoleOutputCP@0:PTR pr0
GetConsoleOutputCP equ <_imp__GetConsoleOutputCP@0>

externdef _imp__GetConsoleScreenBufferInfo@8:PTR pr2
GetConsoleScreenBufferInfo equ <_imp__GetConsoleScreenBufferInfo@8>

externdef _imp__GetConsoleTitleA@8:PTR pr2
GetConsoleTitle equ <_imp__GetConsoleTitleA@8>

externdef _imp__GetConsoleWindow@0:PTR pr0
GetConsoleWindow equ <_imp__GetConsoleWindow@0>

externdef _imp__GetCurrencyFormatA@24:PTR pr6
GetCurrencyFormat equ <_imp__GetCurrencyFormatA@24>

externdef _imp__GetCurrentConsoleFont@12:PTR pr3
GetCurrentConsoleFont equ <_imp__GetCurrentConsoleFont@12>

externdef _imp__GetCurrentDirectoryA@8:PTR pr2
GetCurrentDirectory equ <_imp__GetCurrentDirectoryA@8>

externdef _imp__GetCurrentProcess@0:PTR pr0
GetCurrentProcess equ <_imp__GetCurrentProcess@0>

externdef _imp__GetCurrentProcessId@0:PTR pr0
GetCurrentProcessId equ <_imp__GetCurrentProcessId@0>

externdef _imp__GetCurrentThread@0:PTR pr0
GetCurrentThread equ <_imp__GetCurrentThread@0>

externdef _imp__GetCurrentThreadId@0:PTR pr0
GetCurrentThreadId equ <_imp__GetCurrentThreadId@0>

externdef _imp__GetDateFormatA@24:PTR pr6
GetDateFormat equ <_imp__GetDateFormatA@24>

externdef _imp__GetDefaultCommConfigA@12:PTR pr3
GetDefaultCommConfig equ <_imp__GetDefaultCommConfigA@12>

externdef _imp__GetDevicePowerState@4:PTR pr1
GetDevicePowerState equ <_imp__GetDevicePowerState@4>

externdef _imp__GetDiskFreeSpaceA@20:PTR pr5
GetDiskFreeSpace equ <_imp__GetDiskFreeSpaceA@20>

externdef _imp__GetDiskFreeSpaceExA@16:PTR pr4
GetDiskFreeSpaceEx equ <_imp__GetDiskFreeSpaceExA@16>

externdef _imp__GetDriveTypeA@4:PTR pr1
GetDriveType equ <_imp__GetDriveTypeA@4>

externdef _imp__GetEnvironmentStringsA@0:PTR pr0
GetEnvironmentStrings equ <_imp__GetEnvironmentStringsA@0>

externdef _imp__GetEnvironmentVariableA@12:PTR pr3
GetEnvironmentVariable equ <_imp__GetEnvironmentVariableA@12>

externdef _imp__GetExitCodeProcess@8:PTR pr2
GetExitCodeProcess equ <_imp__GetExitCodeProcess@8>

externdef _imp__GetExitCodeThread@8:PTR pr2
GetExitCodeThread equ <_imp__GetExitCodeThread@8>

externdef _imp__GetFileAttributesA@4:PTR pr1
GetFileAttributes equ <_imp__GetFileAttributesA@4>

externdef _imp__GetFileAttributesExA@12:PTR pr3
GetFileAttributesEx equ <_imp__GetFileAttributesExA@12>

externdef _imp__GetFileInformationByHandle@8:PTR pr2
GetFileInformationByHandle equ <_imp__GetFileInformationByHandle@8>

externdef _imp__GetFileSize@8:PTR pr2
GetFileSize equ <_imp__GetFileSize@8>

externdef _imp__GetFileTime@16:PTR pr4
GetFileTime equ <_imp__GetFileTime@16>

externdef _imp__GetFileType@4:PTR pr1
GetFileType equ <_imp__GetFileType@4>

externdef _imp__GetFullPathNameA@16:PTR pr4
GetFullPathName equ <_imp__GetFullPathNameA@16>

externdef _imp__GetHandleInformation@8:PTR pr2
GetHandleInformation equ <_imp__GetHandleInformation@8>

externdef _imp__GetLargestConsoleWindowSize@4:PTR pr1
GetLargestConsoleWindowSize equ <_imp__GetLargestConsoleWindowSize@4>

externdef _imp__GetLastError@0:PTR pr0
GetLastError equ <_imp__GetLastError@0>

externdef _imp__GetLocalTime@4:PTR pr1
GetLocalTime equ <_imp__GetLocalTime@4>

externdef _imp__GetLocaleInfoA@16:PTR pr4
GetLocaleInfo equ <_imp__GetLocaleInfoA@16>

externdef _imp__GetLogicalDriveStringsA@8:PTR pr2
GetLogicalDriveStrings equ <_imp__GetLogicalDriveStringsA@8>

externdef _imp__GetLogicalDrives@0:PTR pr0
GetLogicalDrives equ <_imp__GetLogicalDrives@0>

externdef _imp__GetLongPathNameA@12:PTR pr3
GetLongPathName equ <_imp__GetLongPathNameA@12>

externdef _imp__GetMailslotInfo@20:PTR pr5
GetMailslotInfo equ <_imp__GetMailslotInfo@20>

externdef _imp__GetModuleFileNameA@12:PTR pr3
GetModuleFileName equ <_imp__GetModuleFileNameA@12>

externdef _imp__GetModuleHandleA@4:PTR pr1
GetModuleHandle equ <_imp__GetModuleHandleA@4>

externdef _imp__GetNamedPipeHandleStateA@28:PTR pr7
GetNamedPipeHandleState equ <_imp__GetNamedPipeHandleStateA@28>

externdef _imp__GetNamedPipeInfo@20:PTR pr5
GetNamedPipeInfo equ <_imp__GetNamedPipeInfo@20>

externdef _imp__GetNextVDMCommand@4:PTR pr1
GetNextVDMCommand equ <_imp__GetNextVDMCommand@4>

externdef _imp__GetNumberFormatA@24:PTR pr6
GetNumberFormat equ <_imp__GetNumberFormatA@24>

externdef _imp__GetNumberOfConsoleFonts@0:PTR pr0
GetNumberOfConsoleFonts equ <_imp__GetNumberOfConsoleFonts@0>

externdef _imp__GetNumberOfConsoleInputEvents@8:PTR pr2
GetNumberOfConsoleInputEvents equ <_imp__GetNumberOfConsoleInputEvents@8>

externdef _imp__GetNumberOfConsoleMouseButtons@4:PTR pr1
GetNumberOfConsoleMouseButtons equ <_imp__GetNumberOfConsoleMouseButtons@4>

externdef _imp__GetOEMCP@0:PTR pr0
GetOEMCP equ <_imp__GetOEMCP@0>

externdef _imp__GetOverlappedResult@16:PTR pr4
GetOverlappedResult equ <_imp__GetOverlappedResult@16>

externdef _imp__GetPriorityClass@4:PTR pr1
GetPriorityClass equ <_imp__GetPriorityClass@4>

externdef _imp__GetPrivateProfileIntA@16:PTR pr4
GetPrivateProfileInt equ <_imp__GetPrivateProfileIntA@16>

externdef _imp__GetPrivateProfileSectionA@16:PTR pr4
GetPrivateProfileSection equ <_imp__GetPrivateProfileSectionA@16>

externdef _imp__GetPrivateProfileSectionNamesA@12:PTR pr3
GetPrivateProfileSectionNames equ <_imp__GetPrivateProfileSectionNamesA@12>

externdef _imp__GetPrivateProfileStringA@24:PTR pr6
GetPrivateProfileString equ <_imp__GetPrivateProfileStringA@24>

externdef _imp__GetPrivateProfileStructA@20:PTR pr5
GetPrivateProfileStruct equ <_imp__GetPrivateProfileStructA@20>

externdef _imp__GetProcAddress@8:PTR pr2
GetProcAddress equ <_imp__GetProcAddress@8>

externdef _imp__GetProcessAffinityMask@12:PTR pr3
GetProcessAffinityMask equ <_imp__GetProcessAffinityMask@12>

externdef _imp__GetProcessHeap@0:PTR pr0
GetProcessHeap equ <_imp__GetProcessHeap@0>

externdef _imp__GetProcessHeaps@8:PTR pr2
GetProcessHeaps equ <_imp__GetProcessHeaps@8>

externdef _imp__GetProcessPriorityBoost@8:PTR pr2
GetProcessPriorityBoost equ <_imp__GetProcessPriorityBoost@8>

externdef _imp__GetProcessShutdownParameters@8:PTR pr2
GetProcessShutdownParameters equ <_imp__GetProcessShutdownParameters@8>

externdef _imp__GetProcessTimes@20:PTR pr5
GetProcessTimes equ <_imp__GetProcessTimes@20>

externdef _imp__GetProcessVersion@4:PTR pr1
GetProcessVersion equ <_imp__GetProcessVersion@4>

externdef _imp__GetProcessWorkingSetSize@12:PTR pr3
GetProcessWorkingSetSize equ <_imp__GetProcessWorkingSetSize@12>

externdef _imp__GetProfileIntA@12:PTR pr3
GetProfileInt equ <_imp__GetProfileIntA@12>

externdef _imp__GetProfileSectionA@12:PTR pr3
GetProfileSection equ <_imp__GetProfileSectionA@12>

externdef _imp__GetProfileStringA@20:PTR pr5
GetProfileString equ <_imp__GetProfileStringA@20>

externdef _imp__GetQueuedCompletionStatus@20:PTR pr5
GetQueuedCompletionStatus equ <_imp__GetQueuedCompletionStatus@20>

externdef _imp__GetShortPathNameA@12:PTR pr3
GetShortPathName equ <_imp__GetShortPathNameA@12>

externdef _imp__GetStartupInfoA@4:PTR pr1
GetStartupInfo equ <_imp__GetStartupInfoA@4>

externdef _imp__GetStdHandle@4:PTR pr1
GetStdHandle equ <_imp__GetStdHandle@4>

externdef _imp__GetStringTypeA@20:PTR pr5
GetStringType equ <_imp__GetStringTypeA@20>

externdef _imp__GetStringTypeExA@20:PTR pr5
GetStringTypeEx equ <_imp__GetStringTypeExA@20>

externdef _imp__GetSystemDefaultLCID@0:PTR pr0
GetSystemDefaultLCID equ <_imp__GetSystemDefaultLCID@0>

externdef _imp__GetSystemDefaultLangID@0:PTR pr0
GetSystemDefaultLangID equ <_imp__GetSystemDefaultLangID@0>

externdef _imp__GetSystemDirectoryA@8:PTR pr2
GetSystemDirectory equ <_imp__GetSystemDirectoryA@8>

externdef _imp__GetSystemInfo@4:PTR pr1
GetSystemInfo equ <_imp__GetSystemInfo@4>

externdef _imp__GetSystemPowerStatus@4:PTR pr1
GetSystemPowerStatus equ <_imp__GetSystemPowerStatus@4>

externdef _imp__GetSystemTime@4:PTR pr1
GetSystemTime equ <_imp__GetSystemTime@4>

externdef _imp__GetSystemTimeAdjustment@12:PTR pr3
GetSystemTimeAdjustment equ <_imp__GetSystemTimeAdjustment@12>

externdef _imp__GetSystemTimeAsFileTime@4:PTR pr1
GetSystemTimeAsFileTime equ <_imp__GetSystemTimeAsFileTime@4>

externdef _imp__GetTapeParameters@16:PTR pr4
GetTapeParameters equ <_imp__GetTapeParameters@16>

externdef _imp__GetTapePosition@20:PTR pr5
GetTapePosition equ <_imp__GetTapePosition@20>

externdef _imp__GetTapeStatus@4:PTR pr1
GetTapeStatus equ <_imp__GetTapeStatus@4>

externdef _imp__GetTempFileNameA@16:PTR pr4
GetTempFileName equ <_imp__GetTempFileNameA@16>

externdef _imp__GetTempPathA@8:PTR pr2
GetTempPath equ <_imp__GetTempPathA@8>

externdef _imp__GetThreadContext@8:PTR pr2
GetThreadContext equ <_imp__GetThreadContext@8>

externdef _imp__GetThreadLocale@0:PTR pr0
GetThreadLocale equ <_imp__GetThreadLocale@0>

externdef _imp__GetThreadPriority@4:PTR pr1
GetThreadPriority equ <_imp__GetThreadPriority@4>

externdef _imp__GetThreadPriorityBoost@8:PTR pr2
GetThreadPriorityBoost equ <_imp__GetThreadPriorityBoost@8>

externdef _imp__GetThreadSelectorEntry@12:PTR pr3
GetThreadSelectorEntry equ <_imp__GetThreadSelectorEntry@12>

externdef _imp__GetThreadTimes@20:PTR pr5
GetThreadTimes equ <_imp__GetThreadTimes@20>

externdef _imp__GetTickCount@0:PTR pr0
GetTickCount equ <_imp__GetTickCount@0>

externdef _imp__GetTimeFormatA@24:PTR pr6
GetTimeFormat equ <_imp__GetTimeFormatA@24>

externdef _imp__GetTimeZoneInformation@4:PTR pr1
GetTimeZoneInformation equ <_imp__GetTimeZoneInformation@4>

externdef _imp__GetUserDefaultLCID@0:PTR pr0
GetUserDefaultLCID equ <_imp__GetUserDefaultLCID@0>

externdef _imp__GetUserDefaultLangID@0:PTR pr0
GetUserDefaultLangID equ <_imp__GetUserDefaultLangID@0>

externdef _imp__GetVDMCurrentDirectories@8:PTR pr2
GetVDMCurrentDirectories equ <_imp__GetVDMCurrentDirectories@8>

externdef _imp__GetVersion@0:PTR pr0
GetVersion equ <_imp__GetVersion@0>

externdef _imp__GetVersionExA@4:PTR pr1
GetVersionEx equ <_imp__GetVersionExA@4>

externdef _imp__GetVolumeInformationA@32:PTR pr8
GetVolumeInformation equ <_imp__GetVolumeInformationA@32>

externdef _imp__GetWindowsDirectoryA@8:PTR pr2
GetWindowsDirectory equ <_imp__GetWindowsDirectoryA@8>

externdef _imp__GlobalAddAtomA@4:PTR pr1
GlobalAddAtom equ <_imp__GlobalAddAtomA@4>

externdef _imp__GlobalAlloc@8:PTR pr2
GlobalAlloc equ <_imp__GlobalAlloc@8>

externdef _imp__GlobalCompact@4:PTR pr1
GlobalCompact equ <_imp__GlobalCompact@4>

externdef _imp__GlobalDeleteAtom@4:PTR pr1
GlobalDeleteAtom equ <_imp__GlobalDeleteAtom@4>

externdef _imp__GlobalFindAtomA@4:PTR pr1
GlobalFindAtom equ <_imp__GlobalFindAtomA@4>

externdef _imp__GlobalFix@4:PTR pr1
GlobalFix equ <_imp__GlobalFix@4>

externdef _imp__GlobalFlags@4:PTR pr1
GlobalFlags equ <_imp__GlobalFlags@4>

externdef _imp__GlobalFree@4:PTR pr1
GlobalFree equ <_imp__GlobalFree@4>

externdef _imp__GlobalGetAtomNameA@12:PTR pr3
GlobalGetAtomName equ <_imp__GlobalGetAtomNameA@12>

externdef _imp__GlobalHandle@4:PTR pr1
GlobalHandle equ <_imp__GlobalHandle@4>

externdef _imp__GlobalLock@4:PTR pr1
GlobalLock equ <_imp__GlobalLock@4>

externdef _imp__GlobalMemoryStatus@4:PTR pr1
GlobalMemoryStatus equ <_imp__GlobalMemoryStatus@4>

externdef _imp__GlobalMemoryStatusVlm@4:PTR pr1
GlobalMemoryStatusVlm equ <_imp__GlobalMemoryStatusVlm@4>

externdef _imp__GlobalReAlloc@12:PTR pr3
GlobalReAlloc equ <_imp__GlobalReAlloc@12>

externdef _imp__GlobalSize@4:PTR pr1
GlobalSize equ <_imp__GlobalSize@4>

externdef _imp__GlobalUnWire@4:PTR pr1
GlobalUnWire equ <_imp__GlobalUnWire@4>

externdef _imp__GlobalUnfix@4:PTR pr1
GlobalUnfix equ <_imp__GlobalUnfix@4>

externdef _imp__GlobalUnlock@4:PTR pr1
GlobalUnlock equ <_imp__GlobalUnlock@4>

externdef _imp__GlobalWire@4:PTR pr1
GlobalWire equ <_imp__GlobalWire@4>

externdef _imp__Heap32First@12:PTR pr3
Heap32First equ <_imp__Heap32First@12>

externdef _imp__Heap32ListFirst@8:PTR pr2
Heap32ListFirst equ <_imp__Heap32ListFirst@8>

externdef _imp__Heap32ListNext@8:PTR pr2
Heap32ListNext equ <_imp__Heap32ListNext@8>

externdef _imp__Heap32Next@4:PTR pr1
Heap32Next equ <_imp__Heap32Next@4>

externdef _imp__HeapAlloc@12:PTR pr3
HeapAlloc equ <_imp__HeapAlloc@12>

externdef _imp__HeapCompact@8:PTR pr2
HeapCompact equ <_imp__HeapCompact@8>

externdef _imp__HeapCreate@12:PTR pr3
HeapCreate equ <_imp__HeapCreate@12>

externdef _imp__HeapDestroy@4:PTR pr1
HeapDestroy equ <_imp__HeapDestroy@4>

externdef _imp__HeapExtend@16:PTR pr4
HeapExtend equ <_imp__HeapExtend@16>

externdef _imp__HeapFree@12:PTR pr3
HeapFree equ <_imp__HeapFree@12>

externdef _imp__HeapLock@4:PTR pr1
HeapLock equ <_imp__HeapLock@4>

externdef _imp__HeapReAlloc@16:PTR pr4
HeapReAlloc equ <_imp__HeapReAlloc@16>

externdef _imp__HeapSize@12:PTR pr3
HeapSize equ <_imp__HeapSize@12>

externdef _imp__HeapSummary@12:PTR pr3
HeapSummary equ <_imp__HeapSummary@12>

externdef _imp__HeapUnlock@4:PTR pr1
HeapUnlock equ <_imp__HeapUnlock@4>

externdef _imp__HeapUsage@20:PTR pr5
HeapUsage equ <_imp__HeapUsage@20>

externdef _imp__HeapValidate@12:PTR pr3
HeapValidate equ <_imp__HeapValidate@12>

externdef _imp__HeapWalk@8:PTR pr2
HeapWalk equ <_imp__HeapWalk@8>

externdef _imp__InitAtomTable@4:PTR pr1
InitAtomTable equ <_imp__InitAtomTable@4>

externdef _imp__InitializeCriticalSection@4:PTR pr1
InitializeCriticalSection equ <_imp__InitializeCriticalSection@4>

externdef _imp__InitializeCriticalSectionAndSpinCount@8:PTR pr2
InitializeCriticalSectionAndSpinCount equ <_imp__InitializeCriticalSectionAndSpinCount@8>

externdef _imp__InterlockedCompareExchange@12:PTR pr3
InterlockedCompareExchange equ <_imp__InterlockedCompareExchange@12>

externdef _imp__InterlockedDecrement@4:PTR pr1
InterlockedDecrement equ <_imp__InterlockedDecrement@4>

externdef _imp__InterlockedExchange@8:PTR pr2
InterlockedExchange equ <_imp__InterlockedExchange@8>

externdef _imp__InterlockedExchangeAdd@8:PTR pr2
InterlockedExchangeAdd equ <_imp__InterlockedExchangeAdd@8>

externdef _imp__InterlockedIncrement@4:PTR pr1
InterlockedIncrement equ <_imp__InterlockedIncrement@4>

externdef _imp__InvalidateConsoleDIBits@8:PTR pr2
InvalidateConsoleDIBits equ <_imp__InvalidateConsoleDIBits@8>

externdef _imp__IsBadCodePtr@4:PTR pr1
IsBadCodePtr equ <_imp__IsBadCodePtr@4>

externdef _imp__IsBadHugeReadPtr@8:PTR pr2
IsBadHugeReadPtr equ <_imp__IsBadHugeReadPtr@8>

externdef _imp__IsBadHugeWritePtr@8:PTR pr2
IsBadHugeWritePtr equ <_imp__IsBadHugeWritePtr@8>

externdef _imp__IsBadReadPtr@8:PTR pr2
IsBadReadPtr equ <_imp__IsBadReadPtr@8>

externdef _imp__IsBadStringPtrA@8:PTR pr2
IsBadStringPtr equ <_imp__IsBadStringPtrA@8>

externdef _imp__IsBadWritePtr@8:PTR pr2
IsBadWritePtr equ <_imp__IsBadWritePtr@8>

externdef _imp__IsDBCSLeadByte@4:PTR pr1
IsDBCSLeadByte equ <_imp__IsDBCSLeadByte@4>

externdef _imp__IsDBCSLeadByteEx@8:PTR pr2
IsDBCSLeadByteEx equ <_imp__IsDBCSLeadByteEx@8>

externdef _imp__IsDebuggerPresent@0:PTR pr0
IsDebuggerPresent equ <_imp__IsDebuggerPresent@0>

externdef _imp__IsProcessorFeaturePresent@4:PTR pr1
IsProcessorFeaturePresent equ <_imp__IsProcessorFeaturePresent@4>

externdef _imp__IsValidCodePage@4:PTR pr1
IsValidCodePage equ <_imp__IsValidCodePage@4>

externdef _imp__IsValidLocale@8:PTR pr2
IsValidLocale equ <_imp__IsValidLocale@8>

externdef _imp__LCMapStringA@24:PTR pr6
LCMapString equ <_imp__LCMapStringA@24>

externdef _imp__LeaveCriticalSection@4:PTR pr1
LeaveCriticalSection equ <_imp__LeaveCriticalSection@4>

externdef _imp__LoadLibraryA@4:PTR pr1
LoadLibrary equ <_imp__LoadLibraryA@4>

externdef _imp__LoadLibraryExA@12:PTR pr3
LoadLibraryEx equ <_imp__LoadLibraryExA@12>

externdef _imp__LoadModule@8:PTR pr2
LoadModule equ <_imp__LoadModule@8>

externdef _imp__LoadResource@8:PTR pr2
LoadResource equ <_imp__LoadResource@8>

externdef _imp__LocalAlloc@8:PTR pr2
LocalAlloc equ <_imp__LocalAlloc@8>

externdef _imp__LocalCompact@4:PTR pr1
LocalCompact equ <_imp__LocalCompact@4>

externdef _imp__LocalFileTimeToFileTime@8:PTR pr2
LocalFileTimeToFileTime equ <_imp__LocalFileTimeToFileTime@8>

externdef _imp__LocalFlags@4:PTR pr1
LocalFlags equ <_imp__LocalFlags@4>

externdef _imp__LocalFree@4:PTR pr1
LocalFree equ <_imp__LocalFree@4>

externdef _imp__LocalHandle@4:PTR pr1
LocalHandle equ <_imp__LocalHandle@4>

externdef _imp__LocalLock@4:PTR pr1
LocalLock equ <_imp__LocalLock@4>

externdef _imp__LocalReAlloc@12:PTR pr3
LocalReAlloc equ <_imp__LocalReAlloc@12>

externdef _imp__LocalShrink@8:PTR pr2
LocalShrink equ <_imp__LocalShrink@8>

externdef _imp__LocalSize@4:PTR pr1
LocalSize equ <_imp__LocalSize@4>

externdef _imp__LocalUnlock@4:PTR pr1
LocalUnlock equ <_imp__LocalUnlock@4>

externdef _imp__LockFile@20:PTR pr5
LockFile equ <_imp__LockFile@20>

externdef _imp__LockFileEx@24:PTR pr6
LockFileEx equ <_imp__LockFileEx@24>

externdef _imp__LockResource@4:PTR pr1
LockResource equ <_imp__LockResource@4>

externdef _imp__MapViewOfFile@20:PTR pr5
MapViewOfFile equ <_imp__MapViewOfFile@20>

externdef _imp__MapViewOfFileEx@24:PTR pr6
MapViewOfFileEx equ <_imp__MapViewOfFileEx@24>

externdef _imp__MapViewOfFileVlm@28:PTR pr7
MapViewOfFileVlm equ <_imp__MapViewOfFileVlm@28>

externdef _imp__Module32First@8:PTR pr2
Module32First equ <_imp__Module32First@8>

externdef _imp__Module32Next@8:PTR pr2
Module32Next equ <_imp__Module32Next@8>

externdef _imp__MoveFileA@8:PTR pr2
MoveFile equ <_imp__MoveFileA@8>

externdef _imp__MoveFileExA@12:PTR pr3
MoveFileEx equ <_imp__MoveFileExA@12>

externdef _imp__MoveFileWithProgressA@20:PTR pr5
MoveFileWithProgress equ <_imp__MoveFileWithProgressA@20>

externdef _imp__MulDiv@12:PTR pr3
MulDiv equ <_imp__MulDiv@12>

externdef _imp__MultiByteToWideChar@24:PTR pr6
MultiByteToWideChar equ <_imp__MultiByteToWideChar@24>

externdef _imp__OpenEventA@12:PTR pr3
OpenEvent equ <_imp__OpenEventA@12>

externdef _imp__OpenFile@12:PTR pr3
OpenFile equ <_imp__OpenFile@12>

externdef _imp__OpenFileMappingA@12:PTR pr3
OpenFileMapping equ <_imp__OpenFileMappingA@12>

externdef _imp__OpenJobObjectA@12:PTR pr3
OpenJobObject equ <_imp__OpenJobObjectA@12>

externdef _imp__OpenMutexA@12:PTR pr3
OpenMutex equ <_imp__OpenMutexA@12>

externdef _imp__OpenProcess@12:PTR pr3
OpenProcess equ <_imp__OpenProcess@12>

externdef _imp__OpenProfileUserMapping@0:PTR pr0
OpenProfileUserMapping equ <_imp__OpenProfileUserMapping@0>

externdef _imp__OpenSemaphoreA@12:PTR pr3
OpenSemaphore equ <_imp__OpenSemaphoreA@12>

externdef _imp__OpenWaitableTimerA@12:PTR pr3
OpenWaitableTimer equ <_imp__OpenWaitableTimerA@12>

externdef _imp__OutputDebugStringA@4:PTR pr1
OutputDebugString equ <_imp__OutputDebugStringA@4>

externdef _imp__PeekConsoleInputA@16:PTR pr4
PeekConsoleInput equ <_imp__PeekConsoleInputA@16>

externdef _imp__PeekNamedPipe@24:PTR pr6
PeekNamedPipe equ <_imp__PeekNamedPipe@24>

externdef _imp__PostQueuedCompletionStatus@16:PTR pr4
PostQueuedCompletionStatus equ <_imp__PostQueuedCompletionStatus@16>

externdef _imp__PrepareTape@12:PTR pr3
PrepareTape equ <_imp__PrepareTape@12>

externdef _imp__Process32First@8:PTR pr2
Process32First equ <_imp__Process32First@8>

externdef _imp__Process32Next@8:PTR pr2
Process32Next equ <_imp__Process32Next@8>

externdef _imp__PulseEvent@4:PTR pr1
PulseEvent equ <_imp__PulseEvent@4>

externdef _imp__PurgeComm@8:PTR pr2
PurgeComm equ <_imp__PurgeComm@8>

externdef _imp__QueryDosDeviceA@12:PTR pr3
QueryDosDevice equ <_imp__QueryDosDeviceA@12>

externdef _imp__QueryInformationJobObject@20:PTR pr5
QueryInformationJobObject equ <_imp__QueryInformationJobObject@20>

externdef _imp__QueryPerformanceCounter@4:PTR pr1
QueryPerformanceCounter equ <_imp__QueryPerformanceCounter@4>

externdef _imp__QueryPerformanceFrequency@4:PTR pr1
QueryPerformanceFrequency equ <_imp__QueryPerformanceFrequency@4>

externdef _imp__QueryWin31IniFilesMappedToRegistry@16:PTR pr4
QueryWin31IniFilesMappedToRegistry equ <_imp__QueryWin31IniFilesMappedToRegistry@16>

externdef _imp__QueueUserAPC@12:PTR pr3
QueueUserAPC equ <_imp__QueueUserAPC@12>

externdef _imp__RaiseException@16:PTR pr4
RaiseException equ <_imp__RaiseException@16>

externdef _imp__ReadConsoleA@20:PTR pr5
ReadConsole equ <_imp__ReadConsoleA@20>

externdef _imp__ReadConsoleInputA@16:PTR pr4
ReadConsoleInput equ <_imp__ReadConsoleInputA@16>

externdef _imp__ReadConsoleInputExA@20:PTR pr5
ReadConsoleInputEx equ <_imp__ReadConsoleInputExA@20>

externdef _imp__ReadConsoleOutputA@20:PTR pr5
ReadConsoleOutput equ <_imp__ReadConsoleOutputA@20>

externdef _imp__ReadConsoleOutputAttribute@20:PTR pr5
ReadConsoleOutputAttribute equ <_imp__ReadConsoleOutputAttribute@20>

externdef _imp__ReadConsoleOutputCharacterA@20:PTR pr5
ReadConsoleOutputCharacter equ <_imp__ReadConsoleOutputCharacterA@20>

externdef _imp__ReadFile@20:PTR pr5
ReadFile equ <_imp__ReadFile@20>

externdef _imp__ReadFileEx@20:PTR pr5
ReadFileEx equ <_imp__ReadFileEx@20>

externdef _imp__ReadFileScatter@20:PTR pr5
ReadFileScatter equ <_imp__ReadFileScatter@20>

externdef _imp__ReadFileVlm@20:PTR pr5
ReadFileVlm equ <_imp__ReadFileVlm@20>

externdef _imp__ReadProcessMemory@20:PTR pr5
ReadProcessMemory equ <_imp__ReadProcessMemory@20>

externdef _imp__ReadProcessMemoryVlm@20:PTR pr5
ReadProcessMemoryVlm equ <_imp__ReadProcessMemoryVlm@20>

externdef _imp__RegisterConsoleVDM@44:PTR pr11
RegisterConsoleVDM equ <_imp__RegisterConsoleVDM@44>

externdef _imp__RegisterWaitForInputIdle@4:PTR pr1
RegisterWaitForInputIdle equ <_imp__RegisterWaitForInputIdle@4>

externdef _imp__RegisterWowBaseHandlers@4:PTR pr1
RegisterWowBaseHandlers equ <_imp__RegisterWowBaseHandlers@4>

externdef _imp__RegisterWowExec@4:PTR pr1
RegisterWowExec equ <_imp__RegisterWowExec@4>

externdef _imp__ReleaseMutex@4:PTR pr1
ReleaseMutex equ <_imp__ReleaseMutex@4>

externdef _imp__ReleaseSemaphore@12:PTR pr3
ReleaseSemaphore equ <_imp__ReleaseSemaphore@12>

externdef _imp__RemoveDirectoryA@4:PTR pr1
RemoveDirectory equ <_imp__RemoveDirectoryA@4>

externdef _imp__RequestWakeupLatency@4:PTR pr1
RequestWakeupLatency equ <_imp__RequestWakeupLatency@4>

externdef _imp__ResetEvent@4:PTR pr1
ResetEvent equ <_imp__ResetEvent@4>

externdef _imp__ResumeThread@4:PTR pr1
ResumeThread equ <_imp__ResumeThread@4>

externdef _imp__RtlFillMemory@12:PTR pr3
RtlFillMemory equ <_imp__RtlFillMemory@12>

externdef _imp__RtlMoveMemory@12:PTR pr3
RtlMoveMemory equ <_imp__RtlMoveMemory@12>

externdef _imp__RtlUnwind@16:PTR pr4
RtlUnwind equ <_imp__RtlUnwind@16>

externdef _imp__RtlZeroMemory@8:PTR pr2
RtlZeroMemory equ <_imp__RtlZeroMemory@8>

externdef _imp__ScrollConsoleScreenBufferA@20:PTR pr5
ScrollConsoleScreenBuffer equ <_imp__ScrollConsoleScreenBufferA@20>

externdef _imp__SearchPathA@24:PTR pr6
SearchPath equ <_imp__SearchPathA@24>

externdef _imp__SetCommBreak@4:PTR pr1
SetCommBreak equ <_imp__SetCommBreak@4>

externdef _imp__SetCommConfig@12:PTR pr3
SetCommConfig equ <_imp__SetCommConfig@12>

externdef _imp__SetCommMask@8:PTR pr2
SetCommMask equ <_imp__SetCommMask@8>

externdef _imp__SetCommState@8:PTR pr2
SetCommState equ <_imp__SetCommState@8>

externdef _imp__SetCommTimeouts@8:PTR pr2
SetCommTimeouts equ <_imp__SetCommTimeouts@8>

externdef _imp__SetComputerNameA@4:PTR pr1
SetComputerName equ <_imp__SetComputerNameA@4>

externdef _imp__SetConsoleActiveScreenBuffer@4:PTR pr1
SetConsoleActiveScreenBuffer equ <_imp__SetConsoleActiveScreenBuffer@4>

externdef _imp__SetConsoleCP@4:PTR pr1
SetConsoleCP equ <_imp__SetConsoleCP@4>

externdef _imp__SetConsoleCommandHistoryMode@4:PTR pr1
SetConsoleCommandHistoryMode equ <_imp__SetConsoleCommandHistoryMode@4>

externdef _imp__SetConsoleCtrlHandler@8:PTR pr2
SetConsoleCtrlHandler equ <_imp__SetConsoleCtrlHandler@8>

externdef _imp__SetConsoleCursor@8:PTR pr2
SetConsoleCursor equ <_imp__SetConsoleCursor@8>

externdef _imp__SetConsoleCursorInfo@8:PTR pr2
SetConsoleCursorInfo equ <_imp__SetConsoleCursorInfo@8>

externdef _imp__SetConsoleCursorPosition@8:PTR pr2
SetConsoleCursorPosition equ <_imp__SetConsoleCursorPosition@8>

externdef _imp__SetConsoleDisplayMode@12:PTR pr3
SetConsoleDisplayMode equ <_imp__SetConsoleDisplayMode@12>

externdef _imp__SetConsoleFont@8:PTR pr2
SetConsoleFont equ <_imp__SetConsoleFont@8>

externdef _imp__SetConsoleHardwareState@12:PTR pr3
SetConsoleHardwareState equ <_imp__SetConsoleHardwareState@12>

externdef _imp__SetConsoleIcon@4:PTR pr1
SetConsoleIcon equ <_imp__SetConsoleIcon@4>

externdef _imp__SetConsoleInputExeNameA@4:PTR pr1
SetConsoleInputExeName equ <_imp__SetConsoleInputExeNameA@4>

externdef _imp__SetConsoleKeyShortcuts@16:PTR pr4
SetConsoleKeyShortcuts equ <_imp__SetConsoleKeyShortcuts@16>

externdef _imp__SetConsoleMaximumWindowSize@8:PTR pr2
SetConsoleMaximumWindowSize equ <_imp__SetConsoleMaximumWindowSize@8>

externdef _imp__SetConsoleMenuClose@4:PTR pr1
SetConsoleMenuClose equ <_imp__SetConsoleMenuClose@4>

externdef _imp__SetConsoleMode@8:PTR pr2
SetConsoleMode equ <_imp__SetConsoleMode@8>

externdef _imp__SetConsoleNumberOfCommandsA@8:PTR pr2
SetConsoleNumberOfCommands equ <_imp__SetConsoleNumberOfCommandsA@8>

externdef _imp__SetConsoleOutputCP@4:PTR pr1
SetConsoleOutputCP equ <_imp__SetConsoleOutputCP@4>

externdef _imp__SetConsolePalette@12:PTR pr3
SetConsolePalette equ <_imp__SetConsolePalette@12>

externdef _imp__SetConsoleScreenBufferSize@8:PTR pr2
SetConsoleScreenBufferSize equ <_imp__SetConsoleScreenBufferSize@8>

externdef _imp__SetConsoleTextAttribute@8:PTR pr2
SetConsoleTextAttribute equ <_imp__SetConsoleTextAttribute@8>

externdef _imp__SetConsoleTitleA@4:PTR pr1
SetConsoleTitle equ <_imp__SetConsoleTitleA@4>

externdef _imp__SetConsoleWindowInfo@12:PTR pr3
SetConsoleWindowInfo equ <_imp__SetConsoleWindowInfo@12>

externdef _imp__SetCriticalSectionSpinCount@8:PTR pr2
SetCriticalSectionSpinCount equ <_imp__SetCriticalSectionSpinCount@8>

externdef _imp__SetCurrentDirectoryA@4:PTR pr1
SetCurrentDirectory equ <_imp__SetCurrentDirectoryA@4>

externdef _imp__SetDefaultCommConfigA@12:PTR pr3
SetDefaultCommConfig equ <_imp__SetDefaultCommConfigA@12>

externdef _imp__SetEndOfFile@4:PTR pr1
SetEndOfFile equ <_imp__SetEndOfFile@4>

externdef _imp__SetEnvironmentVariableA@8:PTR pr2
SetEnvironmentVariable equ <_imp__SetEnvironmentVariableA@8>

externdef _imp__SetErrorMode@4:PTR pr1
SetErrorMode equ <_imp__SetErrorMode@4>

externdef _imp__SetEvent@4:PTR pr1
SetEvent equ <_imp__SetEvent@4>

externdef _imp__SetFileApisToANSI@0:PTR pr0
SetFileApisToANSI equ <_imp__SetFileApisToANSI@0>

externdef _imp__SetFileApisToOEM@0:PTR pr0
SetFileApisToOEM equ <_imp__SetFileApisToOEM@0>

externdef _imp__SetFileAttributesA@8:PTR pr2
SetFileAttributes equ <_imp__SetFileAttributesA@8>

externdef _imp__SetFilePointer@16:PTR pr4
SetFilePointer equ <_imp__SetFilePointer@16>

externdef _imp__SetFileTime@16:PTR pr4
SetFileTime equ <_imp__SetFileTime@16>

externdef _imp__SetHandleCount@4:PTR pr1
SetHandleCount equ <_imp__SetHandleCount@4>

externdef _imp__SetHandleInformation@12:PTR pr3
SetHandleInformation equ <_imp__SetHandleInformation@12>

externdef _imp__SetInformationJobObject@16:PTR pr4
SetInformationJobObject equ <_imp__SetInformationJobObject@16>

externdef _imp__SetLastConsoleEventActive@0:PTR pr0
SetLastConsoleEventActive equ <_imp__SetLastConsoleEventActive@0>

externdef _imp__SetLastError@4:PTR pr1
SetLastError equ <_imp__SetLastError@4>

externdef _imp__SetLocalTime@4:PTR pr1
SetLocalTime equ <_imp__SetLocalTime@4>

externdef _imp__SetLocaleInfoA@12:PTR pr3
SetLocaleInfo equ <_imp__SetLocaleInfoA@12>

externdef _imp__SetMailslotInfo@8:PTR pr2
SetMailslotInfo equ <_imp__SetMailslotInfo@8>

externdef _imp__SetNamedPipeHandleState@16:PTR pr4
SetNamedPipeHandleState equ <_imp__SetNamedPipeHandleState@16>

externdef _imp__SetPriorityClass@8:PTR pr2
SetPriorityClass equ <_imp__SetPriorityClass@8>

externdef _imp__SetProcessAffinityMask@8:PTR pr2
SetProcessAffinityMask equ <_imp__SetProcessAffinityMask@8>

externdef _imp__SetProcessPriorityBoost@8:PTR pr2
SetProcessPriorityBoost equ <_imp__SetProcessPriorityBoost@8>

externdef _imp__SetProcessShutdownParameters@8:PTR pr2
SetProcessShutdownParameters equ <_imp__SetProcessShutdownParameters@8>

externdef _imp__SetProcessWorkingSetSize@12:PTR pr3
SetProcessWorkingSetSize equ <_imp__SetProcessWorkingSetSize@12>

externdef _imp__SetStdHandle@8:PTR pr2
SetStdHandle equ <_imp__SetStdHandle@8>

externdef _imp__SetSystemPowerState@8:PTR pr2
SetSystemPowerState equ <_imp__SetSystemPowerState@8>

externdef _imp__SetSystemTime@4:PTR pr1
SetSystemTime equ <_imp__SetSystemTime@4>

externdef _imp__SetSystemTimeAdjustment@8:PTR pr2
SetSystemTimeAdjustment equ <_imp__SetSystemTimeAdjustment@8>

externdef _imp__SetTapeParameters@12:PTR pr3
SetTapeParameters equ <_imp__SetTapeParameters@12>

externdef _imp__SetTapePosition@24:PTR pr6
SetTapePosition equ <_imp__SetTapePosition@24>

externdef _imp__SetThreadAffinityMask@8:PTR pr2
SetThreadAffinityMask equ <_imp__SetThreadAffinityMask@8>

externdef _imp__SetThreadContext@8:PTR pr2
SetThreadContext equ <_imp__SetThreadContext@8>

externdef _imp__SetThreadExecutionState@4:PTR pr1
SetThreadExecutionState equ <_imp__SetThreadExecutionState@4>

externdef _imp__SetThreadIdealProcessor@8:PTR pr2
SetThreadIdealProcessor equ <_imp__SetThreadIdealProcessor@8>

externdef _imp__SetThreadLocale@4:PTR pr1
SetThreadLocale equ <_imp__SetThreadLocale@4>

externdef _imp__SetThreadPriority@8:PTR pr2
SetThreadPriority equ <_imp__SetThreadPriority@8>

externdef _imp__SetThreadPriorityBoost@8:PTR pr2
SetThreadPriorityBoost equ <_imp__SetThreadPriorityBoost@8>

externdef _imp__SetTimeZoneInformation@4:PTR pr1
SetTimeZoneInformation equ <_imp__SetTimeZoneInformation@4>

externdef _imp__SetUnhandledExceptionFilter@4:PTR pr1
SetUnhandledExceptionFilter equ <_imp__SetUnhandledExceptionFilter@4>

externdef _imp__SetVDMCurrentDirectories@8:PTR pr2
SetVDMCurrentDirectories equ <_imp__SetVDMCurrentDirectories@8>

externdef _imp__SetVolumeLabelA@8:PTR pr2
SetVolumeLabel equ <_imp__SetVolumeLabelA@8>

externdef _imp__SetWaitableTimer@24:PTR pr6
SetWaitableTimer equ <_imp__SetWaitableTimer@24>

externdef _imp__SetupComm@12:PTR pr3
SetupComm equ <_imp__SetupComm@12>

externdef _imp__ShowConsoleCursor@8:PTR pr2
ShowConsoleCursor equ <_imp__ShowConsoleCursor@8>

externdef _imp__SignalObjectAndWait@16:PTR pr4
SignalObjectAndWait equ <_imp__SignalObjectAndWait@16>

externdef _imp__SizeofResource@8:PTR pr2
SizeofResource equ <_imp__SizeofResource@8>

externdef _imp__Sleep@4:PTR pr1
Sleep equ <_imp__Sleep@4>

externdef _imp__SleepEx@8:PTR pr2
SleepEx equ <_imp__SleepEx@8>

externdef _imp__SuspendThread@4:PTR pr1
SuspendThread equ <_imp__SuspendThread@4>

externdef _imp__SwitchToFiber@4:PTR pr1
SwitchToFiber equ <_imp__SwitchToFiber@4>

externdef _imp__SwitchToThread@0:PTR pr0
SwitchToThread equ <_imp__SwitchToThread@0>

externdef _imp__SystemTimeToFileTime@8:PTR pr2
SystemTimeToFileTime equ <_imp__SystemTimeToFileTime@8>

externdef _imp__SystemTimeToTzSpecificLocalTime@12:PTR pr3
SystemTimeToTzSpecificLocalTime equ <_imp__SystemTimeToTzSpecificLocalTime@12>

externdef _imp__TerminateJobObject@8:PTR pr2
TerminateJobObject equ <_imp__TerminateJobObject@8>

externdef _imp__TerminateProcess@8:PTR pr2
TerminateProcess equ <_imp__TerminateProcess@8>

externdef _imp__TerminateThread@8:PTR pr2
TerminateThread equ <_imp__TerminateThread@8>

externdef _imp__Thread32First@8:PTR pr2
Thread32First equ <_imp__Thread32First@8>

externdef _imp__Thread32Next@8:PTR pr2
Thread32Next equ <_imp__Thread32Next@8>

externdef _imp__TlsAlloc@0:PTR pr0
TlsAlloc equ <_imp__TlsAlloc@0>

externdef _imp__TlsFree@4:PTR pr1
TlsFree equ <_imp__TlsFree@4>

externdef _imp__TlsGetValue@4:PTR pr1
TlsGetValue equ <_imp__TlsGetValue@4>

externdef _imp__TlsSetValue@8:PTR pr2
TlsSetValue equ <_imp__TlsSetValue@8>

externdef _imp__Toolhelp32ReadProcessMemory@20:PTR pr5
Toolhelp32ReadProcessMemory equ <_imp__Toolhelp32ReadProcessMemory@20>

externdef _imp__TransactNamedPipe@28:PTR pr7
TransactNamedPipe equ <_imp__TransactNamedPipe@28>

externdef _imp__TransmitCommChar@8:PTR pr2
TransmitCommChar equ <_imp__TransmitCommChar@8>

externdef _imp__TrimVirtualBuffer@4:PTR pr1
TrimVirtualBuffer equ <_imp__TrimVirtualBuffer@4>

externdef _imp__TryEnterCriticalSection@4:PTR pr1
TryEnterCriticalSection equ <_imp__TryEnterCriticalSection@4>

externdef _imp__UnhandledExceptionFilter@4:PTR pr1
UnhandledExceptionFilter equ <_imp__UnhandledExceptionFilter@4>

externdef _imp__UnlockFile@20:PTR pr5
UnlockFile equ <_imp__UnlockFile@20>

externdef _imp__UnlockFileEx@20:PTR pr5
UnlockFileEx equ <_imp__UnlockFileEx@20>

externdef _imp__UnmapViewOfFile@4:PTR pr1
UnmapViewOfFile equ <_imp__UnmapViewOfFile@4>

externdef _imp__UnmapViewOfFileVlm@4:PTR pr1
UnmapViewOfFileVlm equ <_imp__UnmapViewOfFileVlm@4>

externdef _imp__UpdateResourceA@24:PTR pr6
UpdateResource equ <_imp__UpdateResourceA@24>

externdef _imp__VDMConsoleOperation@8:PTR pr2
VDMConsoleOperation equ <_imp__VDMConsoleOperation@8>

externdef _imp__VDMOperationStarted@4:PTR pr1
VDMOperationStarted equ <_imp__VDMOperationStarted@4>

externdef _imp__VerLanguageNameA@12:PTR pr3
VerLanguageName equ <_imp__VerLanguageNameA@12>

externdef _imp__VerifyConsoleIoHandle@4:PTR pr1
VerifyConsoleIoHandle equ <_imp__VerifyConsoleIoHandle@4>

externdef _imp__VirtualAlloc@16:PTR pr4
VirtualAlloc equ <_imp__VirtualAlloc@16>

externdef _imp__VirtualAllocEx@20:PTR pr5
VirtualAllocEx equ <_imp__VirtualAllocEx@20>

externdef _imp__VirtualAllocVlm@24:PTR pr6
VirtualAllocVlm equ <_imp__VirtualAllocVlm@24>

externdef _imp__VirtualBufferExceptionHandler@12:PTR pr3
VirtualBufferExceptionHandler equ <_imp__VirtualBufferExceptionHandler@12>

externdef _imp__VirtualFree@12:PTR pr3
VirtualFree equ <_imp__VirtualFree@12>

externdef _imp__VirtualFreeEx@16:PTR pr4
VirtualFreeEx equ <_imp__VirtualFreeEx@16>

externdef _imp__VirtualFreeVlm@20:PTR pr5
VirtualFreeVlm equ <_imp__VirtualFreeVlm@20>

externdef _imp__VirtualLock@8:PTR pr2
VirtualLock equ <_imp__VirtualLock@8>

externdef _imp__VirtualProtect@16:PTR pr4
VirtualProtect equ <_imp__VirtualProtect@16>

externdef _imp__VirtualProtectEx@20:PTR pr5
VirtualProtectEx equ <_imp__VirtualProtectEx@20>

externdef _imp__VirtualProtectVlm@24:PTR pr6
VirtualProtectVlm equ <_imp__VirtualProtectVlm@24>

externdef _imp__VirtualQuery@12:PTR pr3
VirtualQuery equ <_imp__VirtualQuery@12>

externdef _imp__VirtualQueryEx@16:PTR pr4
VirtualQueryEx equ <_imp__VirtualQueryEx@16>

externdef _imp__VirtualQueryVlm@16:PTR pr4
VirtualQueryVlm equ <_imp__VirtualQueryVlm@16>

externdef _imp__VirtualUnlock@8:PTR pr2
VirtualUnlock equ <_imp__VirtualUnlock@8>

externdef _imp__WaitCommEvent@12:PTR pr3
WaitCommEvent equ <_imp__WaitCommEvent@12>

externdef _imp__WaitForDebugEvent@8:PTR pr2
WaitForDebugEvent equ <_imp__WaitForDebugEvent@8>

externdef _imp__WaitForMultipleObjects@16:PTR pr4
WaitForMultipleObjects equ <_imp__WaitForMultipleObjects@16>

externdef _imp__WaitForMultipleObjectsEx@20:PTR pr5
WaitForMultipleObjectsEx equ <_imp__WaitForMultipleObjectsEx@20>

externdef _imp__WaitForSingleObject@8:PTR pr2
WaitForSingleObject equ <_imp__WaitForSingleObject@8>

externdef _imp__WaitForSingleObjectEx@12:PTR pr3
WaitForSingleObjectEx equ <_imp__WaitForSingleObjectEx@12>

externdef _imp__WaitNamedPipeA@8:PTR pr2
WaitNamedPipe equ <_imp__WaitNamedPipeA@8>

externdef _imp__WideCharToMultiByte@32:PTR pr8
WideCharToMultiByte equ <_imp__WideCharToMultiByte@32>

externdef _imp__WinExec@8:PTR pr2
WinExec equ <_imp__WinExec@8>

externdef _imp__WriteConsoleA@20:PTR pr5
WriteConsole equ <_imp__WriteConsoleA@20>

externdef _imp__WriteConsoleInputA@16:PTR pr4
WriteConsoleInput equ <_imp__WriteConsoleInputA@16>

externdef _imp__WriteConsoleInputVDMA@16:PTR pr4
WriteConsoleInputVDM equ <_imp__WriteConsoleInputVDMA@16>

externdef _imp__WriteConsoleOutputA@20:PTR pr5
WriteConsoleOutput equ <_imp__WriteConsoleOutputA@20>

externdef _imp__WriteConsoleOutputAttribute@20:PTR pr5
WriteConsoleOutputAttribute equ <_imp__WriteConsoleOutputAttribute@20>

externdef _imp__WriteConsoleOutputCharacterA@20:PTR pr5
WriteConsoleOutputCharacter equ <_imp__WriteConsoleOutputCharacterA@20>

externdef _imp__WriteFile@20:PTR pr5
WriteFile equ <_imp__WriteFile@20>

externdef _imp__WriteFileEx@20:PTR pr5
WriteFileEx equ <_imp__WriteFileEx@20>

externdef _imp__WriteFileGather@20:PTR pr5
WriteFileGather equ <_imp__WriteFileGather@20>

externdef _imp__WriteFileVlm@20:PTR pr5
WriteFileVlm equ <_imp__WriteFileVlm@20>

externdef _imp__WritePrivateProfileSectionA@12:PTR pr3
WritePrivateProfileSection equ <_imp__WritePrivateProfileSectionA@12>

externdef _imp__WritePrivateProfileStringA@16:PTR pr4
WritePrivateProfileString equ <_imp__WritePrivateProfileStringA@16>

externdef _imp__WritePrivateProfileStructA@20:PTR pr5
WritePrivateProfileStruct equ <_imp__WritePrivateProfileStructA@20>

externdef _imp__WriteProcessMemory@20:PTR pr5
WriteProcessMemory equ <_imp__WriteProcessMemory@20>

externdef _imp__WriteProcessMemoryVlm@20:PTR pr5
WriteProcessMemoryVlm equ <_imp__WriteProcessMemoryVlm@20>

externdef _imp__WriteProfileSectionA@8:PTR pr2
WriteProfileSection equ <_imp__WriteProfileSectionA@8>

externdef _imp__WriteProfileStringA@12:PTR pr3
WriteProfileString equ <_imp__WriteProfileStringA@12>

externdef _imp__WriteTapemark@16:PTR pr4
WriteTapemark equ <_imp__WriteTapemark@16>

externdef _imp___hread@12:PTR pr3
_hread equ <_imp___hread@12>

externdef _imp___hwrite@12:PTR pr3
_hwrite equ <_imp___hwrite@12>

externdef _imp___lclose@4:PTR pr1
_lclose equ <_imp___lclose@4>

externdef _imp___lcreat@8:PTR pr2
_lcreat equ <_imp___lcreat@8>

externdef _imp___llseek@12:PTR pr3
_llseek equ <_imp___llseek@12>

externdef _imp___lopen@8:PTR pr2
_lopen equ <_imp___lopen@8>

externdef _imp___lread@12:PTR pr3
_lread equ <_imp___lread@12>

externdef _imp___lwrite@12:PTR pr3
_lwrite equ <_imp___lwrite@12>

externdef _imp__lstrcatA@8:PTR pr2
lstrcat equ <_imp__lstrcatA@8>

externdef _imp__lstrcmpA@8:PTR pr2
lstrcmp equ <_imp__lstrcmpA@8>

externdef _imp__lstrcmpiA@8:PTR pr2
lstrcmpi equ <_imp__lstrcmpiA@8>

externdef _imp__lstrcpyA@8:PTR pr2
lstrcpy equ <_imp__lstrcpyA@8>

externdef _imp__lstrcpynA@12:PTR pr3
lstrcpyn equ <_imp__lstrcpynA@12>

externdef _imp__lstrlenA@4:PTR pr1
lstrlen equ <_imp__lstrlenA@4>

