externdef _imp__ActivateKeyboardLayout@8:PTR pr2
ActivateKeyboardLayout equ <_imp__ActivateKeyboardLayout@8>

externdef _imp__AdjustWindowRect@12:PTR pr3
AdjustWindowRect equ <_imp__AdjustWindowRect@12>

externdef _imp__AdjustWindowRectEx@16:PTR pr4
AdjustWindowRectEx equ <_imp__AdjustWindowRectEx@16>

externdef _imp__AnimateWindow@12:PTR pr3
AnimateWindow equ <_imp__AnimateWindow@12>

externdef _imp__AnyPopup@0:PTR pr0
AnyPopup equ <_imp__AnyPopup@0>

externdef _imp__AppendMenuA@16:PTR pr4
AppendMenu equ <_imp__AppendMenuA@16>

externdef _imp__ArrangeIconicWindows@4:PTR pr1
ArrangeIconicWindows equ <_imp__ArrangeIconicWindows@4>

externdef _imp__AttachThreadInput@12:PTR pr3
AttachThreadInput equ <_imp__AttachThreadInput@12>

externdef _imp__BeginDeferWindowPos@4:PTR pr1
BeginDeferWindowPos equ <_imp__BeginDeferWindowPos@4>

externdef _imp__BeginPaint@8:PTR pr2
BeginPaint equ <_imp__BeginPaint@8>

externdef _imp__BlockInput@4:PTR pr1
BlockInput equ <_imp__BlockInput@4>

externdef _imp__BringWindowToTop@4:PTR pr1
BringWindowToTop equ <_imp__BringWindowToTop@4>

externdef _imp__BroadcastSystemMessageA@20:PTR pr5
BroadcastSystemMessage equ <_imp__BroadcastSystemMessageA@20>

externdef _imp__CallMsgFilterA@8:PTR pr2
CallMsgFilter equ <_imp__CallMsgFilterA@8>

externdef _imp__CallNextHookEx@16:PTR pr4
CallNextHookEx equ <_imp__CallNextHookEx@16>

externdef _imp__CallWindowProcA@20:PTR pr5
CallWindowProc equ <_imp__CallWindowProcA@20>

externdef _imp__CascadeChildWindows@8:PTR pr2
CascadeChildWindows equ <_imp__CascadeChildWindows@8>

externdef _imp__CascadeWindows@20:PTR pr5
CascadeWindows equ <_imp__CascadeWindows@20>

externdef _imp__ChangeClipboardChain@8:PTR pr2
ChangeClipboardChain equ <_imp__ChangeClipboardChain@8>

externdef _imp__ChangeDisplaySettingsA@8:PTR pr2
ChangeDisplaySettings equ <_imp__ChangeDisplaySettingsA@8>

externdef _imp__ChangeDisplaySettingsExA@20:PTR pr5
ChangeDisplaySettingsEx equ <_imp__ChangeDisplaySettingsExA@20>

externdef _imp__ChangeMenuA@20:PTR pr5
ChangeMenu equ <_imp__ChangeMenuA@20>

externdef _imp__CharLowerA@4:PTR pr1
CharLower equ <_imp__CharLowerA@4>

externdef _imp__CharLowerBuffA@8:PTR pr2
CharLowerBuff equ <_imp__CharLowerBuffA@8>

externdef _imp__CharNextA@4:PTR pr1
CharNext equ <_imp__CharNextA@4>

externdef _imp__CharNextExA@12:PTR pr3
CharNextEx equ <_imp__CharNextExA@12>

externdef _imp__CharPrevA@8:PTR pr2
CharPrev equ <_imp__CharPrevA@8>

externdef _imp__CharPrevExA@16:PTR pr4
CharPrevEx equ <_imp__CharPrevExA@16>

externdef _imp__CharToOemA@8:PTR pr2
CharToOem equ <_imp__CharToOemA@8>

externdef _imp__CharToOemBuffA@12:PTR pr3
CharToOemBuff equ <_imp__CharToOemBuffA@12>

externdef _imp__CharUpperA@4:PTR pr1
CharUpper equ <_imp__CharUpperA@4>

externdef _imp__CharUpperBuffA@8:PTR pr2
CharUpperBuff equ <_imp__CharUpperBuffA@8>

externdef _imp__CheckDlgButton@12:PTR pr3
CheckDlgButton equ <_imp__CheckDlgButton@12>

externdef _imp__CheckMenuItem@12:PTR pr3
CheckMenuItem equ <_imp__CheckMenuItem@12>

externdef _imp__CheckMenuRadioItem@20:PTR pr5
CheckMenuRadioItem equ <_imp__CheckMenuRadioItem@20>

externdef _imp__CheckRadioButton@16:PTR pr4
CheckRadioButton equ <_imp__CheckRadioButton@16>

externdef _imp__ChildWindowFromPoint@12:PTR pr3
ChildWindowFromPoint equ <_imp__ChildWindowFromPoint@12>

externdef _imp__ChildWindowFromPointEx@16:PTR pr4
ChildWindowFromPointEx equ <_imp__ChildWindowFromPointEx@16>

externdef _imp__ClientToScreen@8:PTR pr2
ClientToScreen equ <_imp__ClientToScreen@8>

externdef _imp__ClipCursor@4:PTR pr1
ClipCursor equ <_imp__ClipCursor@4>

externdef _imp__CloseClipboard@0:PTR pr0
CloseClipboard equ <_imp__CloseClipboard@0>

externdef _imp__CloseDesktop@4:PTR pr1
CloseDesktop equ <_imp__CloseDesktop@4>

externdef _imp__CloseWindow@4:PTR pr1
CloseWindow equ <_imp__CloseWindow@4>

externdef _imp__CloseWindowStation@4:PTR pr1
CloseWindowStation equ <_imp__CloseWindowStation@4>

externdef _imp__CopyAcceleratorTableA@12:PTR pr3
CopyAcceleratorTable equ <_imp__CopyAcceleratorTableA@12>

externdef _imp__CopyIcon@4:PTR pr1
CopyIcon equ <_imp__CopyIcon@4>

externdef _imp__CopyImage@20:PTR pr5
CopyImage equ <_imp__CopyImage@20>

externdef _imp__CopyRect@8:PTR pr2
CopyRect equ <_imp__CopyRect@8>

externdef _imp__CountClipboardFormats@0:PTR pr0
CountClipboardFormats equ <_imp__CountClipboardFormats@0>

externdef _imp__CreateAcceleratorTableA@8:PTR pr2
CreateAcceleratorTable equ <_imp__CreateAcceleratorTableA@8>

externdef _imp__CreateCaret@16:PTR pr4
CreateCaret equ <_imp__CreateCaret@16>

externdef _imp__CreateCursor@28:PTR pr7
CreateCursor equ <_imp__CreateCursor@28>

externdef _imp__CreateDesktopA@24:PTR pr6
CreateDesktop equ <_imp__CreateDesktopA@24>

externdef _imp__CreateDialogIndirectParamA@20:PTR pr5
CreateDialogIndirectParam equ <_imp__CreateDialogIndirectParamA@20>

externdef _imp__CreateDialogParamA@20:PTR pr5
CreateDialogParam equ <_imp__CreateDialogParamA@20>

externdef _imp__CreateIcon@28:PTR pr7
CreateIcon equ <_imp__CreateIcon@28>

externdef _imp__CreateIconFromResource@16:PTR pr4
CreateIconFromResource equ <_imp__CreateIconFromResource@16>

externdef _imp__CreateIconFromResourceEx@28:PTR pr7
CreateIconFromResourceEx equ <_imp__CreateIconFromResourceEx@28>

externdef _imp__CreateIconIndirect@4:PTR pr1
CreateIconIndirect equ <_imp__CreateIconIndirect@4>

externdef _imp__CreateMDIWindowA@40:PTR pr10
CreateMDIWindow equ <_imp__CreateMDIWindowA@40>

externdef _imp__CreateMenu@0:PTR pr0
CreateMenu equ <_imp__CreateMenu@0>

externdef _imp__CreatePopupMenu@0:PTR pr0
CreatePopupMenu equ <_imp__CreatePopupMenu@0>

externdef _imp__CreateWindowExA@48:PTR pr12
CreateWindowEx equ <_imp__CreateWindowExA@48>

externdef _imp__CreateWindowStationA@16:PTR pr4
CreateWindowStation equ <_imp__CreateWindowStationA@16>

externdef _imp__DdeAbandonTransaction@12:PTR pr3
DdeAbandonTransaction equ <_imp__DdeAbandonTransaction@12>

externdef _imp__DdeAccessData@8:PTR pr2
DdeAccessData equ <_imp__DdeAccessData@8>

externdef _imp__DdeAddData@16:PTR pr4
DdeAddData equ <_imp__DdeAddData@16>

externdef _imp__DdeClientTransaction@32:PTR pr8
DdeClientTransaction equ <_imp__DdeClientTransaction@32>

externdef _imp__DdeCmpStringHandles@8:PTR pr2
DdeCmpStringHandles equ <_imp__DdeCmpStringHandles@8>

externdef _imp__DdeConnect@16:PTR pr4
DdeConnect equ <_imp__DdeConnect@16>

externdef _imp__DdeConnectList@20:PTR pr5
DdeConnectList equ <_imp__DdeConnectList@20>

externdef _imp__DdeCreateDataHandle@28:PTR pr7
DdeCreateDataHandle equ <_imp__DdeCreateDataHandle@28>

externdef _imp__DdeCreateStringHandleA@12:PTR pr3
DdeCreateStringHandle equ <_imp__DdeCreateStringHandleA@12>

externdef _imp__DdeDisconnect@4:PTR pr1
DdeDisconnect equ <_imp__DdeDisconnect@4>

externdef _imp__DdeDisconnectList@4:PTR pr1
DdeDisconnectList equ <_imp__DdeDisconnectList@4>

externdef _imp__DdeEnableCallback@12:PTR pr3
DdeEnableCallback equ <_imp__DdeEnableCallback@12>

externdef _imp__DdeFreeDataHandle@4:PTR pr1
DdeFreeDataHandle equ <_imp__DdeFreeDataHandle@4>

externdef _imp__DdeFreeStringHandle@8:PTR pr2
DdeFreeStringHandle equ <_imp__DdeFreeStringHandle@8>

externdef _imp__DdeGetData@16:PTR pr4
DdeGetData equ <_imp__DdeGetData@16>

externdef _imp__DdeGetLastError@4:PTR pr1
DdeGetLastError equ <_imp__DdeGetLastError@4>

externdef _imp__DdeGetQualityOfService@12:PTR pr3
DdeGetQualityOfService equ <_imp__DdeGetQualityOfService@12>

externdef _imp__DdeImpersonateClient@4:PTR pr1
DdeImpersonateClient equ <_imp__DdeImpersonateClient@4>

externdef _imp__DdeInitializeA@16:PTR pr4
DdeInitialize equ <_imp__DdeInitializeA@16>

externdef _imp__DdeKeepStringHandle@8:PTR pr2
DdeKeepStringHandle equ <_imp__DdeKeepStringHandle@8>

externdef _imp__DdeNameService@16:PTR pr4
DdeNameService equ <_imp__DdeNameService@16>

externdef _imp__DdePostAdvise@12:PTR pr3
DdePostAdvise equ <_imp__DdePostAdvise@12>

externdef _imp__DdeQueryConvInfo@12:PTR pr3
DdeQueryConvInfo equ <_imp__DdeQueryConvInfo@12>

externdef _imp__DdeQueryNextServer@8:PTR pr2
DdeQueryNextServer equ <_imp__DdeQueryNextServer@8>

externdef _imp__DdeQueryStringA@20:PTR pr5
DdeQueryString equ <_imp__DdeQueryStringA@20>

externdef _imp__DdeReconnect@4:PTR pr1
DdeReconnect equ <_imp__DdeReconnect@4>

externdef _imp__DdeSetQualityOfService@12:PTR pr3
DdeSetQualityOfService equ <_imp__DdeSetQualityOfService@12>

externdef _imp__DdeSetUserHandle@12:PTR pr3
DdeSetUserHandle equ <_imp__DdeSetUserHandle@12>

externdef _imp__DdeUnaccessData@4:PTR pr1
DdeUnaccessData equ <_imp__DdeUnaccessData@4>

externdef _imp__DdeUninitialize@4:PTR pr1
DdeUninitialize equ <_imp__DdeUninitialize@4>

externdef _imp__DefDlgProcA@16:PTR pr4
DefDlgProc equ <_imp__DefDlgProcA@16>

externdef _imp__DefFrameProcA@20:PTR pr5
DefFrameProc equ <_imp__DefFrameProcA@20>

externdef _imp__DefMDIChildProcA@16:PTR pr4
DefMDIChildProc equ <_imp__DefMDIChildProcA@16>

externdef _imp__DefWindowProcA@16:PTR pr4
DefWindowProc equ <_imp__DefWindowProcA@16>

externdef _imp__DeferWindowPos@32:PTR pr8
DeferWindowPos equ <_imp__DeferWindowPos@32>

externdef _imp__DeleteMenu@12:PTR pr3
DeleteMenu equ <_imp__DeleteMenu@12>

externdef _imp__DestroyAcceleratorTable@4:PTR pr1
DestroyAcceleratorTable equ <_imp__DestroyAcceleratorTable@4>

externdef _imp__DestroyCaret@0:PTR pr0
DestroyCaret equ <_imp__DestroyCaret@0>

externdef _imp__DestroyCursor@4:PTR pr1
DestroyCursor equ <_imp__DestroyCursor@4>

externdef _imp__DestroyIcon@4:PTR pr1
DestroyIcon equ <_imp__DestroyIcon@4>

externdef _imp__DestroyMenu@4:PTR pr1
DestroyMenu equ <_imp__DestroyMenu@4>

externdef _imp__DestroyWindow@4:PTR pr1
DestroyWindow equ <_imp__DestroyWindow@4>

externdef _imp__DialogBoxIndirectParamA@20:PTR pr5
DialogBoxIndirectParam equ <_imp__DialogBoxIndirectParamA@20>

externdef _imp__DialogBoxParamA@20:PTR pr5
DialogBoxParam equ <_imp__DialogBoxParamA@20>

externdef _imp__DispatchMessageA@4:PTR pr1
DispatchMessage equ <_imp__DispatchMessageA@4>

externdef _imp__DlgDirListA@20:PTR pr5
DlgDirList equ <_imp__DlgDirListA@20>

externdef _imp__DlgDirListComboBoxA@20:PTR pr5
DlgDirListComboBox equ <_imp__DlgDirListComboBoxA@20>

externdef _imp__DlgDirSelectComboBoxExA@16:PTR pr4
DlgDirSelectComboBoxEx equ <_imp__DlgDirSelectComboBoxExA@16>

externdef _imp__DlgDirSelectExA@16:PTR pr4
DlgDirSelectEx equ <_imp__DlgDirSelectExA@16>

externdef _imp__DragDetect@12:PTR pr3
DragDetect equ <_imp__DragDetect@12>

externdef _imp__DragObject@20:PTR pr5
DragObject equ <_imp__DragObject@20>

externdef _imp__DrawAnimatedRects@16:PTR pr4
DrawAnimatedRects equ <_imp__DrawAnimatedRects@16>

externdef _imp__DrawCaption@16:PTR pr4
DrawCaption equ <_imp__DrawCaption@16>

externdef _imp__DrawEdge@16:PTR pr4
DrawEdge equ <_imp__DrawEdge@16>

externdef _imp__DrawFocusRect@8:PTR pr2
DrawFocusRect equ <_imp__DrawFocusRect@8>

externdef _imp__DrawFrame@16:PTR pr4
DrawFrame equ <_imp__DrawFrame@16>

externdef _imp__DrawFrameControl@16:PTR pr4
DrawFrameControl equ <_imp__DrawFrameControl@16>

externdef _imp__DrawIcon@16:PTR pr4
DrawIcon equ <_imp__DrawIcon@16>

externdef _imp__DrawIconEx@36:PTR pr9
DrawIconEx equ <_imp__DrawIconEx@36>

externdef _imp__DrawMenuBar@4:PTR pr1
DrawMenuBar equ <_imp__DrawMenuBar@4>

externdef _imp__DrawStateA@40:PTR pr10
DrawState equ <_imp__DrawStateA@40>

externdef _imp__DrawTextA@20:PTR pr5
DrawText equ <_imp__DrawTextA@20>

externdef _imp__DrawTextExA@24:PTR pr6
DrawTextEx equ <_imp__DrawTextExA@24>

externdef _imp__EditWndProc@16:PTR pr4
EditWndProc equ <_imp__EditWndProc@16>

externdef _imp__EmptyClipboard@0:PTR pr0
EmptyClipboard equ <_imp__EmptyClipboard@0>

externdef _imp__EnableMenuItem@12:PTR pr3
EnableMenuItem equ <_imp__EnableMenuItem@12>

externdef _imp__EnableScrollBar@12:PTR pr3
EnableScrollBar equ <_imp__EnableScrollBar@12>

externdef _imp__EnableWindow@8:PTR pr2
EnableWindow equ <_imp__EnableWindow@8>

externdef _imp__EndDeferWindowPos@4:PTR pr1
EndDeferWindowPos equ <_imp__EndDeferWindowPos@4>

externdef _imp__EndDialog@8:PTR pr2
EndDialog equ <_imp__EndDialog@8>

externdef _imp__EndMenu@0:PTR pr0
EndMenu equ <_imp__EndMenu@0>

externdef _imp__EndPaint@8:PTR pr2
EndPaint equ <_imp__EndPaint@8>

externdef _imp__EnumChildWindows@12:PTR pr3
EnumChildWindows equ <_imp__EnumChildWindows@12>

externdef _imp__EnumClipboardFormats@4:PTR pr1
EnumClipboardFormats equ <_imp__EnumClipboardFormats@4>

externdef _imp__EnumDesktopWindows@12:PTR pr3
EnumDesktopWindows equ <_imp__EnumDesktopWindows@12>

externdef _imp__EnumDesktopsA@12:PTR pr3
EnumDesktops equ <_imp__EnumDesktopsA@12>

externdef _imp__EnumDisplayMonitors@16:PTR pr4
EnumDisplayMonitors equ <_imp__EnumDisplayMonitors@16>

externdef _imp__EnumDisplaySettingsA@12:PTR pr3
EnumDisplaySettings equ <_imp__EnumDisplaySettingsA@12>

externdef _imp__EnumDisplaySettingsExA@16:PTR pr4
EnumDisplaySettingsEx equ <_imp__EnumDisplaySettingsExA@16>

externdef _imp__EnumPropsA@8:PTR pr2
EnumProps equ <_imp__EnumPropsA@8>

externdef _imp__EnumPropsExA@12:PTR pr3
EnumPropsEx equ <_imp__EnumPropsExA@12>

externdef _imp__EnumThreadWindows@12:PTR pr3
EnumThreadWindows equ <_imp__EnumThreadWindows@12>

externdef _imp__EnumWindowStationsA@8:PTR pr2
EnumWindowStations equ <_imp__EnumWindowStationsA@8>

externdef _imp__EnumWindows@8:PTR pr2
EnumWindows equ <_imp__EnumWindows@8>

externdef _imp__EqualRect@8:PTR pr2
EqualRect equ <_imp__EqualRect@8>

externdef _imp__ExcludeUpdateRgn@8:PTR pr2
ExcludeUpdateRgn equ <_imp__ExcludeUpdateRgn@8>

externdef _imp__ExitWindowsEx@8:PTR pr2
ExitWindowsEx equ <_imp__ExitWindowsEx@8>

externdef _imp__FillRect@12:PTR pr3
FillRect equ <_imp__FillRect@12>

externdef _imp__FindWindowA@8:PTR pr2
FindWindow equ <_imp__FindWindowA@8>

externdef _imp__FindWindowExA@16:PTR pr4
FindWindowEx equ <_imp__FindWindowExA@16>

externdef _imp__FlashWindow@8:PTR pr2
FlashWindow equ <_imp__FlashWindow@8>

externdef _imp__FrameRect@12:PTR pr3
FrameRect equ <_imp__FrameRect@12>

externdef _imp__FreeDDElParam@8:PTR pr2
FreeDDElParam equ <_imp__FreeDDElParam@8>

externdef _imp__GetActiveWindow@0:PTR pr0
GetActiveWindow equ <_imp__GetActiveWindow@0>

externdef _imp__GetAltTabInfoA@20:PTR pr5
GetAltTabInfo equ <_imp__GetAltTabInfoA@20>

externdef _imp__GetAncestor@8:PTR pr2
GetAncestor equ <_imp__GetAncestor@8>

externdef _imp__GetAsyncKeyState@4:PTR pr1
GetAsyncKeyState equ <_imp__GetAsyncKeyState@4>

externdef _imp__GetCapture@0:PTR pr0
GetCapture equ <_imp__GetCapture@0>

externdef _imp__GetCaretBlinkTime@0:PTR pr0
GetCaretBlinkTime equ <_imp__GetCaretBlinkTime@0>

externdef _imp__GetCaretPos@4:PTR pr1
GetCaretPos equ <_imp__GetCaretPos@4>

externdef _imp__GetClassInfoA@12:PTR pr3
GetClassInfo equ <_imp__GetClassInfoA@12>

externdef _imp__GetClassInfoExA@12:PTR pr3
GetClassInfoEx equ <_imp__GetClassInfoExA@12>

externdef _imp__GetClassLongA@8:PTR pr2
GetClassLong equ <_imp__GetClassLongA@8>

externdef _imp__GetClassNameA@12:PTR pr3
GetClassName equ <_imp__GetClassNameA@12>

externdef _imp__GetClassWord@8:PTR pr2
GetClassWord equ <_imp__GetClassWord@8>

externdef _imp__GetClientRect@8:PTR pr2
GetClientRect equ <_imp__GetClientRect@8>

externdef _imp__GetClipCursor@4:PTR pr1
GetClipCursor equ <_imp__GetClipCursor@4>

externdef _imp__GetClipboardData@4:PTR pr1
GetClipboardData equ <_imp__GetClipboardData@4>

externdef _imp__GetClipboardFormatNameA@12:PTR pr3
GetClipboardFormatName equ <_imp__GetClipboardFormatNameA@12>

externdef _imp__GetClipboardOwner@0:PTR pr0
GetClipboardOwner equ <_imp__GetClipboardOwner@0>

externdef _imp__GetClipboardSequenceNumber@0:PTR pr0
GetClipboardSequenceNumber equ <_imp__GetClipboardSequenceNumber@0>

externdef _imp__GetClipboardViewer@0:PTR pr0
GetClipboardViewer equ <_imp__GetClipboardViewer@0>

externdef _imp__GetComboBoxInfo@8:PTR pr2
GetComboBoxInfo equ <_imp__GetComboBoxInfo@8>

externdef _imp__GetCursor@0:PTR pr0
GetCursor equ <_imp__GetCursor@0>

externdef _imp__GetCursorInfo@4:PTR pr1
GetCursorInfo equ <_imp__GetCursorInfo@4>

externdef _imp__GetCursorPos@4:PTR pr1
GetCursorPos equ <_imp__GetCursorPos@4>

externdef _imp__GetDC@4:PTR pr1
GetDC equ <_imp__GetDC@4>

externdef _imp__GetDCEx@12:PTR pr3
GetDCEx equ <_imp__GetDCEx@12>

externdef _imp__GetDesktopWindow@0:PTR pr0
GetDesktopWindow equ <_imp__GetDesktopWindow@0>

externdef _imp__GetDialogBaseUnits@0:PTR pr0
GetDialogBaseUnits equ <_imp__GetDialogBaseUnits@0>

externdef _imp__GetDlgCtrlID@4:PTR pr1
GetDlgCtrlID equ <_imp__GetDlgCtrlID@4>

externdef _imp__GetDlgItem@8:PTR pr2
GetDlgItem equ <_imp__GetDlgItem@8>

externdef _imp__GetDlgItemInt@16:PTR pr4
GetDlgItemInt equ <_imp__GetDlgItemInt@16>

externdef _imp__GetDlgItemTextA@16:PTR pr4
GetDlgItemText equ <_imp__GetDlgItemTextA@16>

externdef _imp__GetDoubleClickTime@0:PTR pr0
GetDoubleClickTime equ <_imp__GetDoubleClickTime@0>

externdef _imp__GetFocus@0:PTR pr0
GetFocus equ <_imp__GetFocus@0>

externdef _imp__GetForegroundWindow@0:PTR pr0
GetForegroundWindow equ <_imp__GetForegroundWindow@0>

externdef _imp__GetGUIThreadInfo@8:PTR pr2
GetGUIThreadInfo equ <_imp__GetGUIThreadInfo@8>

externdef _imp__GetGuiResources@8:PTR pr2
GetGuiResources equ <_imp__GetGuiResources@8>

externdef _imp__GetIconInfo@8:PTR pr2
GetIconInfo equ <_imp__GetIconInfo@8>

externdef _imp__GetInputDesktop@0:PTR pr0
GetInputDesktop equ <_imp__GetInputDesktop@0>

externdef _imp__GetInputState@0:PTR pr0
GetInputState equ <_imp__GetInputState@0>

externdef _imp__GetKBCodePage@0:PTR pr0
GetKBCodePage equ <_imp__GetKBCodePage@0>

externdef _imp__GetKeyNameTextA@12:PTR pr3
GetKeyNameText equ <_imp__GetKeyNameTextA@12>

externdef _imp__GetKeyState@4:PTR pr1
GetKeyState equ <_imp__GetKeyState@4>

externdef _imp__GetKeyboardLayout@4:PTR pr1
GetKeyboardLayout equ <_imp__GetKeyboardLayout@4>

externdef _imp__GetKeyboardLayoutList@8:PTR pr2
GetKeyboardLayoutList equ <_imp__GetKeyboardLayoutList@8>

externdef _imp__GetKeyboardLayoutNameA@4:PTR pr1
GetKeyboardLayoutName equ <_imp__GetKeyboardLayoutNameA@4>

externdef _imp__GetKeyboardState@4:PTR pr1
GetKeyboardState equ <_imp__GetKeyboardState@4>

externdef _imp__GetKeyboardType@4:PTR pr1
GetKeyboardType equ <_imp__GetKeyboardType@4>

externdef _imp__GetLastActivePopup@4:PTR pr1
GetLastActivePopup equ <_imp__GetLastActivePopup@4>

externdef _imp__GetLastInputInfo@4:PTR pr1
GetLastInputInfo equ <_imp__GetLastInputInfo@4>

externdef _imp__GetListBoxInfo@4:PTR pr1
GetListBoxInfo equ <_imp__GetListBoxInfo@4>

externdef _imp__GetMenu@4:PTR pr1
GetMenu equ <_imp__GetMenu@4>

externdef _imp__GetMenuBarInfo@16:PTR pr4
GetMenuBarInfo equ <_imp__GetMenuBarInfo@16>

externdef _imp__GetMenuCheckMarkDimensions@0:PTR pr0
GetMenuCheckMarkDimensions equ <_imp__GetMenuCheckMarkDimensions@0>

externdef _imp__GetMenuContextHelpId@4:PTR pr1
GetMenuContextHelpId equ <_imp__GetMenuContextHelpId@4>

externdef _imp__GetMenuDefaultItem@12:PTR pr3
GetMenuDefaultItem equ <_imp__GetMenuDefaultItem@12>

externdef _imp__GetMenuInfo@8:PTR pr2
GetMenuInfo equ <_imp__GetMenuInfo@8>

externdef _imp__GetMenuItemCount@4:PTR pr1
GetMenuItemCount equ <_imp__GetMenuItemCount@4>

externdef _imp__GetMenuItemID@8:PTR pr2
GetMenuItemID equ <_imp__GetMenuItemID@8>

externdef _imp__GetMenuItemInfoA@16:PTR pr4
GetMenuItemInfo equ <_imp__GetMenuItemInfoA@16>

externdef _imp__GetMenuItemRect@16:PTR pr4
GetMenuItemRect equ <_imp__GetMenuItemRect@16>

externdef _imp__GetMenuState@12:PTR pr3
GetMenuState equ <_imp__GetMenuState@12>

externdef _imp__GetMenuStringA@20:PTR pr5
GetMenuString equ <_imp__GetMenuStringA@20>

externdef _imp__GetMessageA@16:PTR pr4
GetMessage equ <_imp__GetMessageA@16>

externdef _imp__GetMessageExtraInfo@0:PTR pr0
GetMessageExtraInfo equ <_imp__GetMessageExtraInfo@0>

externdef _imp__GetMessagePos@0:PTR pr0
GetMessagePos equ <_imp__GetMessagePos@0>

externdef _imp__GetMessageTime@0:PTR pr0
GetMessageTime equ <_imp__GetMessageTime@0>

externdef _imp__GetMonitorInfoA@8:PTR pr2
GetMonitorInfo equ <_imp__GetMonitorInfoA@8>

externdef _imp__GetMouseMovePoints@20:PTR pr5
GetMouseMovePoints equ <_imp__GetMouseMovePoints@20>

externdef _imp__GetNextDlgGroupItem@12:PTR pr3
GetNextDlgGroupItem equ <_imp__GetNextDlgGroupItem@12>

externdef _imp__GetNextDlgTabItem@12:PTR pr3
GetNextDlgTabItem equ <_imp__GetNextDlgTabItem@12>

externdef _imp__GetOpenClipboardWindow@0:PTR pr0
GetOpenClipboardWindow equ <_imp__GetOpenClipboardWindow@0>

externdef _imp__GetParent@4:PTR pr1
GetParent equ <_imp__GetParent@4>

externdef _imp__GetPriorityClipboardFormat@8:PTR pr2
GetPriorityClipboardFormat equ <_imp__GetPriorityClipboardFormat@8>

externdef _imp__GetProcessWindowStation@0:PTR pr0
GetProcessWindowStation equ <_imp__GetProcessWindowStation@0>

externdef _imp__GetPropA@8:PTR pr2
GetProp equ <_imp__GetPropA@8>

externdef _imp__GetQueueStatus@4:PTR pr1
GetQueueStatus equ <_imp__GetQueueStatus@4>

externdef _imp__GetScrollBarInfo@12:PTR pr3
GetScrollBarInfo equ <_imp__GetScrollBarInfo@12>

externdef _imp__GetScrollInfo@12:PTR pr3
GetScrollInfo equ <_imp__GetScrollInfo@12>

externdef _imp__GetScrollPos@8:PTR pr2
GetScrollPos equ <_imp__GetScrollPos@8>

externdef _imp__GetScrollRange@16:PTR pr4
GetScrollRange equ <_imp__GetScrollRange@16>

externdef _imp__GetShellWindow@0:PTR pr0
GetShellWindow equ <_imp__GetShellWindow@0>

externdef _imp__GetSubMenu@8:PTR pr2
GetSubMenu equ <_imp__GetSubMenu@8>

externdef _imp__GetSysColor@4:PTR pr1
GetSysColor equ <_imp__GetSysColor@4>

externdef _imp__GetSysColorBrush@4:PTR pr1
GetSysColorBrush equ <_imp__GetSysColorBrush@4>

externdef _imp__GetSystemMenu@8:PTR pr2
GetSystemMenu equ <_imp__GetSystemMenu@8>

externdef _imp__GetSystemMetrics@4:PTR pr1
GetSystemMetrics equ <_imp__GetSystemMetrics@4>

externdef _imp__GetTabbedTextExtentA@20:PTR pr5
GetTabbedTextExtent equ <_imp__GetTabbedTextExtentA@20>

externdef _imp__GetThreadDesktop@4:PTR pr1
GetThreadDesktop equ <_imp__GetThreadDesktop@4>

externdef _imp__GetTitleBarInfo@8:PTR pr2
GetTitleBarInfo equ <_imp__GetTitleBarInfo@8>

externdef _imp__GetTopWindow@4:PTR pr1
GetTopWindow equ <_imp__GetTopWindow@4>

externdef _imp__GetUpdateRect@12:PTR pr3
GetUpdateRect equ <_imp__GetUpdateRect@12>

externdef _imp__GetUpdateRgn@12:PTR pr3
GetUpdateRgn equ <_imp__GetUpdateRgn@12>

externdef _imp__GetUserObjectInformationA@20:PTR pr5
GetUserObjectInformation equ <_imp__GetUserObjectInformationA@20>

externdef _imp__GetUserObjectSecurity@20:PTR pr5
GetUserObjectSecurity equ <_imp__GetUserObjectSecurity@20>

externdef _imp__GetWindow@8:PTR pr2
GetWindow equ <_imp__GetWindow@8>

externdef _imp__GetWindowContextHelpId@4:PTR pr1
GetWindowContextHelpId equ <_imp__GetWindowContextHelpId@4>

externdef _imp__GetWindowDC@4:PTR pr1
GetWindowDC equ <_imp__GetWindowDC@4>

externdef _imp__GetWindowInfo@8:PTR pr2
GetWindowInfo equ <_imp__GetWindowInfo@8>

externdef _imp__GetWindowLongA@8:PTR pr2
GetWindowLong equ <_imp__GetWindowLongA@8>

externdef _imp__GetWindowModuleFileNameA@12:PTR pr3
GetWindowModuleFileName equ <_imp__GetWindowModuleFileNameA@12>

externdef _imp__GetWindowPlacement@8:PTR pr2
GetWindowPlacement equ <_imp__GetWindowPlacement@8>

externdef _imp__GetWindowRect@8:PTR pr2
GetWindowRect equ <_imp__GetWindowRect@8>

externdef _imp__GetWindowRgn@8:PTR pr2
GetWindowRgn equ <_imp__GetWindowRgn@8>

externdef _imp__GetWindowTextA@12:PTR pr3
GetWindowText equ <_imp__GetWindowTextA@12>

externdef _imp__GetWindowTextLengthA@4:PTR pr1
GetWindowTextLength equ <_imp__GetWindowTextLengthA@4>

externdef _imp__GetWindowThreadProcessId@8:PTR pr2
GetWindowThreadProcessId equ <_imp__GetWindowThreadProcessId@8>

externdef _imp__GetWindowWord@8:PTR pr2
GetWindowWord equ <_imp__GetWindowWord@8>

externdef _imp__GrayStringA@36:PTR pr9
GrayString equ <_imp__GrayStringA@36>

externdef _imp__HideCaret@4:PTR pr1
HideCaret equ <_imp__HideCaret@4>

externdef _imp__HiliteMenuItem@16:PTR pr4
HiliteMenuItem equ <_imp__HiliteMenuItem@16>

externdef _imp__IMPGetIMEA@8:PTR pr2
IMPGetIME equ <_imp__IMPGetIMEA@8>

externdef _imp__IMPQueryIMEA@4:PTR pr1
IMPQueryIME equ <_imp__IMPQueryIMEA@4>

externdef _imp__IMPSetIMEA@8:PTR pr2
IMPSetIME equ <_imp__IMPSetIMEA@8>

externdef _imp__ImpersonateDdeClientWindow@8:PTR pr2
ImpersonateDdeClientWindow equ <_imp__ImpersonateDdeClientWindow@8>

externdef _imp__InSendMessage@0:PTR pr0
InSendMessage equ <_imp__InSendMessage@0>

externdef _imp__InSendMessageEx@4:PTR pr1
InSendMessageEx equ <_imp__InSendMessageEx@4>

externdef _imp__InflateRect@12:PTR pr3
InflateRect equ <_imp__InflateRect@12>

externdef _imp__InsertMenuA@20:PTR pr5
InsertMenu equ <_imp__InsertMenuA@20>

externdef _imp__InsertMenuItemA@16:PTR pr4
InsertMenuItem equ <_imp__InsertMenuItemA@16>

externdef _imp__IntersectRect@12:PTR pr3
IntersectRect equ <_imp__IntersectRect@12>

externdef _imp__InvalidateRect@12:PTR pr3
InvalidateRect equ <_imp__InvalidateRect@12>

externdef _imp__InvalidateRgn@12:PTR pr3
InvalidateRgn equ <_imp__InvalidateRgn@12>

externdef _imp__InvertRect@8:PTR pr2
InvertRect equ <_imp__InvertRect@8>

externdef _imp__IsCharAlphaA@4:PTR pr1
IsCharAlpha equ <_imp__IsCharAlphaA@4>

externdef _imp__IsCharAlphaNumericA@4:PTR pr1
IsCharAlphaNumeric equ <_imp__IsCharAlphaNumericA@4>

externdef _imp__IsCharLowerA@4:PTR pr1
IsCharLower equ <_imp__IsCharLowerA@4>

externdef _imp__IsCharUpperA@4:PTR pr1
IsCharUpper equ <_imp__IsCharUpperA@4>

externdef _imp__IsChild@8:PTR pr2
IsChild equ <_imp__IsChild@8>

externdef _imp__IsClipboardFormatAvailable@4:PTR pr1
IsClipboardFormatAvailable equ <_imp__IsClipboardFormatAvailable@4>

externdef _imp__IsDialogMessageA@8:PTR pr2
IsDialogMessage equ <_imp__IsDialogMessageA@8>

externdef _imp__IsDlgButtonChecked@8:PTR pr2
IsDlgButtonChecked equ <_imp__IsDlgButtonChecked@8>

externdef _imp__IsIconic@4:PTR pr1
IsIconic equ <_imp__IsIconic@4>

externdef _imp__IsMenu@4:PTR pr1
IsMenu equ <_imp__IsMenu@4>

externdef _imp__IsRectEmpty@4:PTR pr1
IsRectEmpty equ <_imp__IsRectEmpty@4>

externdef _imp__IsWindow@4:PTR pr1
IsWindow equ <_imp__IsWindow@4>

externdef _imp__IsWindowEnabled@4:PTR pr1
IsWindowEnabled equ <_imp__IsWindowEnabled@4>

externdef _imp__IsWindowUnicode@4:PTR pr1
IsWindowUnicode equ <_imp__IsWindowUnicode@4>

externdef _imp__IsWindowVisible@4:PTR pr1
IsWindowVisible equ <_imp__IsWindowVisible@4>

externdef _imp__IsZoomed@4:PTR pr1
IsZoomed equ <_imp__IsZoomed@4>

externdef _imp__KillSystemTimer@8:PTR pr2
KillSystemTimer equ <_imp__KillSystemTimer@8>

externdef _imp__KillTimer@8:PTR pr2
KillTimer equ <_imp__KillTimer@8>

externdef _imp__LoadAcceleratorsA@8:PTR pr2
LoadAccelerators equ <_imp__LoadAcceleratorsA@8>

externdef _imp__LoadBitmapA@8:PTR pr2
LoadBitmap equ <_imp__LoadBitmapA@8>

externdef _imp__LoadCursorA@8:PTR pr2
LoadCursor equ <_imp__LoadCursorA@8>

externdef _imp__LoadCursorFromFileA@4:PTR pr1
LoadCursorFromFile equ <_imp__LoadCursorFromFileA@4>

externdef _imp__LoadIconA@8:PTR pr2
LoadIcon equ <_imp__LoadIconA@8>

externdef _imp__LoadImageA@24:PTR pr6
LoadImage equ <_imp__LoadImageA@24>

externdef _imp__LoadKeyboardLayoutA@8:PTR pr2
LoadKeyboardLayout equ <_imp__LoadKeyboardLayoutA@8>

externdef _imp__LoadMenuA@8:PTR pr2
LoadMenu equ <_imp__LoadMenuA@8>

externdef _imp__LoadMenuIndirectA@4:PTR pr1
LoadMenuIndirect equ <_imp__LoadMenuIndirectA@4>

externdef _imp__LoadStringA@16:PTR pr4
LoadString equ <_imp__LoadStringA@16>

externdef _imp__LockWindowUpdate@4:PTR pr1
LockWindowUpdate equ <_imp__LockWindowUpdate@4>

externdef _imp__LockWorkStation@0:PTR pr0
LockWorkStation equ <_imp__LockWorkStation@0>

externdef _imp__LookupIconIdFromDirectory@8:PTR pr2
LookupIconIdFromDirectory equ <_imp__LookupIconIdFromDirectory@8>

externdef _imp__LookupIconIdFromDirectoryEx@20:PTR pr5
LookupIconIdFromDirectoryEx equ <_imp__LookupIconIdFromDirectoryEx@20>

externdef _imp__MapDialogRect@8:PTR pr2
MapDialogRect equ <_imp__MapDialogRect@8>

externdef _imp__MapVirtualKeyA@8:PTR pr2
MapVirtualKey equ <_imp__MapVirtualKeyA@8>

externdef _imp__MapVirtualKeyExA@12:PTR pr3
MapVirtualKeyEx equ <_imp__MapVirtualKeyExA@12>

externdef _imp__MapWindowPoints@16:PTR pr4
MapWindowPoints equ <_imp__MapWindowPoints@16>

externdef _imp__MenuItemFromPoint@16:PTR pr4
MenuItemFromPoint equ <_imp__MenuItemFromPoint@16>

externdef _imp__MessageBeep@4:PTR pr1
MessageBeep equ <_imp__MessageBeep@4>

externdef _imp__MessageBoxA@16:PTR pr4
MessageBox equ <_imp__MessageBoxA@16>

externdef _imp__MessageBoxExA@20:PTR pr5
MessageBoxEx equ <_imp__MessageBoxExA@20>

externdef _imp__MessageBoxIndirectA@4:PTR pr1
MessageBoxIndirect equ <_imp__MessageBoxIndirectA@4>

externdef _imp__ModifyMenuA@20:PTR pr5
ModifyMenu equ <_imp__ModifyMenuA@20>

externdef _imp__MonitorFromPoint@12:PTR pr3
MonitorFromPoint equ <_imp__MonitorFromPoint@12>

externdef _imp__MonitorFromRect@8:PTR pr2
MonitorFromRect equ <_imp__MonitorFromRect@8>

externdef _imp__MonitorFromWindow@8:PTR pr2
MonitorFromWindow equ <_imp__MonitorFromWindow@8>

externdef _imp__MoveWindow@24:PTR pr6
MoveWindow equ <_imp__MoveWindow@24>

externdef _imp__MsgWaitForMultipleObjects@20:PTR pr5
MsgWaitForMultipleObjects equ <_imp__MsgWaitForMultipleObjects@20>

externdef _imp__MsgWaitForMultipleObjectsEx@20:PTR pr5
MsgWaitForMultipleObjectsEx equ <_imp__MsgWaitForMultipleObjectsEx@20>

externdef _imp__NotifyWinEvent@16:PTR pr4
NotifyWinEvent equ <_imp__NotifyWinEvent@16>

externdef _imp__OemKeyScan@4:PTR pr1
OemKeyScan equ <_imp__OemKeyScan@4>

externdef _imp__OemToCharA@8:PTR pr2
OemToChar equ <_imp__OemToCharA@8>

externdef _imp__OemToCharBuffA@12:PTR pr3
OemToCharBuff equ <_imp__OemToCharBuffA@12>

externdef _imp__OffsetRect@12:PTR pr3
OffsetRect equ <_imp__OffsetRect@12>

externdef _imp__OpenClipboard@4:PTR pr1
OpenClipboard equ <_imp__OpenClipboard@4>

externdef _imp__OpenDesktopA@16:PTR pr4
OpenDesktop equ <_imp__OpenDesktopA@16>

externdef _imp__OpenIcon@4:PTR pr1
OpenIcon equ <_imp__OpenIcon@4>

externdef _imp__OpenInputDesktop@12:PTR pr3
OpenInputDesktop equ <_imp__OpenInputDesktop@12>

externdef _imp__OpenWindowStationA@12:PTR pr3
OpenWindowStation equ <_imp__OpenWindowStationA@12>

externdef _imp__PackDDElParam@12:PTR pr3
PackDDElParam equ <_imp__PackDDElParam@12>

externdef _imp__PaintDesktop@4:PTR pr1
PaintDesktop equ <_imp__PaintDesktop@4>

externdef _imp__PeekMessageA@20:PTR pr5
PeekMessage equ <_imp__PeekMessageA@20>

externdef _imp__PostMessageA@16:PTR pr4
PostMessage equ <_imp__PostMessageA@16>

externdef _imp__PostQuitMessage@4:PTR pr1
PostQuitMessage equ <_imp__PostQuitMessage@4>

externdef _imp__PostThreadMessageA@16:PTR pr4
PostThreadMessage equ <_imp__PostThreadMessageA@16>

externdef _imp__PtInRect@12:PTR pr3
PtInRect equ <_imp__PtInRect@12>

externdef _imp__RealChildWindowFromPoint@12:PTR pr3
RealChildWindowFromPoint equ <_imp__RealChildWindowFromPoint@12>

externdef _imp__RealGetWindowClassA@12:PTR pr3
RealGetWindowClass equ <_imp__RealGetWindowClassA@12>

externdef _imp__RedrawWindow@16:PTR pr4
RedrawWindow equ <_imp__RedrawWindow@16>

externdef _imp__RegisterClassA@4:PTR pr1
RegisterClass equ <_imp__RegisterClassA@4>

externdef _imp__RegisterClassExA@4:PTR pr1
RegisterClassEx equ <_imp__RegisterClassExA@4>

externdef _imp__RegisterClipboardFormatA@4:PTR pr1
RegisterClipboardFormat equ <_imp__RegisterClipboardFormatA@4>

externdef _imp__RegisterDeviceNotificationA@12:PTR pr3
RegisterDeviceNotification equ <_imp__RegisterDeviceNotificationA@12>

externdef _imp__RegisterHotKey@16:PTR pr4
RegisterHotKey equ <_imp__RegisterHotKey@16>

externdef _imp__RegisterWindowMessageA@4:PTR pr1
RegisterWindowMessage equ <_imp__RegisterWindowMessageA@4>

externdef _imp__ReleaseCapture@0:PTR pr0
ReleaseCapture equ <_imp__ReleaseCapture@0>

externdef _imp__ReleaseDC@8:PTR pr2
ReleaseDC equ <_imp__ReleaseDC@8>

externdef _imp__RemoveMenu@12:PTR pr3
RemoveMenu equ <_imp__RemoveMenu@12>

externdef _imp__RemovePropA@8:PTR pr2
RemoveProp equ <_imp__RemovePropA@8>

externdef _imp__ReplyMessage@4:PTR pr1
ReplyMessage equ <_imp__ReplyMessage@4>

externdef _imp__ReuseDDElParam@20:PTR pr5
ReuseDDElParam equ <_imp__ReuseDDElParam@20>

externdef _imp__ScreenToClient@8:PTR pr2
ScreenToClient equ <_imp__ScreenToClient@8>

externdef _imp__ScrollChildren@12:PTR pr3
ScrollChildren equ <_imp__ScrollChildren@12>

externdef _imp__ScrollDC@28:PTR pr7
ScrollDC equ <_imp__ScrollDC@28>

externdef _imp__ScrollWindow@20:PTR pr5
ScrollWindow equ <_imp__ScrollWindow@20>

externdef _imp__ScrollWindowEx@32:PTR pr8
ScrollWindowEx equ <_imp__ScrollWindowEx@32>

externdef _imp__SendDlgItemMessageA@20:PTR pr5
SendDlgItemMessage equ <_imp__SendDlgItemMessageA@20>

externdef _imp__SendIMEMessageExA@8:PTR pr2
SendIMEMessageEx equ <_imp__SendIMEMessageExA@8>

externdef _imp__SendInput@12:PTR pr3
SendInput equ <_imp__SendInput@12>

externdef _imp__SendMessageA@16:PTR pr4
SendMessage equ <_imp__SendMessageA@16>

externdef _imp__SendMessageCallbackA@24:PTR pr6
SendMessageCallback equ <_imp__SendMessageCallbackA@24>

externdef _imp__SendMessageTimeoutA@28:PTR pr7
SendMessageTimeout equ <_imp__SendMessageTimeoutA@28>

externdef _imp__SendNotifyMessageA@16:PTR pr4
SendNotifyMessage equ <_imp__SendNotifyMessageA@16>

externdef _imp__SetActiveWindow@4:PTR pr1
SetActiveWindow equ <_imp__SetActiveWindow@4>

externdef _imp__SetCapture@4:PTR pr1
SetCapture equ <_imp__SetCapture@4>

externdef _imp__SetCaretBlinkTime@4:PTR pr1
SetCaretBlinkTime equ <_imp__SetCaretBlinkTime@4>

externdef _imp__SetCaretPos@8:PTR pr2
SetCaretPos equ <_imp__SetCaretPos@8>

externdef _imp__SetClassLongA@12:PTR pr3
SetClassLong equ <_imp__SetClassLongA@12>

externdef _imp__SetClassWord@12:PTR pr3
SetClassWord equ <_imp__SetClassWord@12>

externdef _imp__SetClipboardData@8:PTR pr2
SetClipboardData equ <_imp__SetClipboardData@8>

externdef _imp__SetClipboardViewer@4:PTR pr1
SetClipboardViewer equ <_imp__SetClipboardViewer@4>

externdef _imp__SetCursor@4:PTR pr1
SetCursor equ <_imp__SetCursor@4>

externdef _imp__SetCursorPos@8:PTR pr2
SetCursorPos equ <_imp__SetCursorPos@8>

externdef _imp__SetDebugErrorLevel@4:PTR pr1
SetDebugErrorLevel equ <_imp__SetDebugErrorLevel@4>

externdef _imp__SetDeskWallpaper@4:PTR pr1
SetDeskWallpaper equ <_imp__SetDeskWallpaper@4>

externdef _imp__SetDlgItemInt@16:PTR pr4
SetDlgItemInt equ <_imp__SetDlgItemInt@16>

externdef _imp__SetDlgItemTextA@12:PTR pr3
SetDlgItemText equ <_imp__SetDlgItemTextA@12>

externdef _imp__SetDoubleClickTime@4:PTR pr1
SetDoubleClickTime equ <_imp__SetDoubleClickTime@4>

externdef _imp__SetFocus@4:PTR pr1
SetFocus equ <_imp__SetFocus@4>

externdef _imp__SetForegroundWindow@4:PTR pr1
SetForegroundWindow equ <_imp__SetForegroundWindow@4>

externdef _imp__SetKeyboardState@4:PTR pr1
SetKeyboardState equ <_imp__SetKeyboardState@4>

externdef _imp__SetLastErrorEx@8:PTR pr2
SetLastErrorEx equ <_imp__SetLastErrorEx@8>

externdef _imp__SetMenu@8:PTR pr2
SetMenu equ <_imp__SetMenu@8>

externdef _imp__SetMenuContextHelpId@8:PTR pr2
SetMenuContextHelpId equ <_imp__SetMenuContextHelpId@8>

externdef _imp__SetMenuDefaultItem@12:PTR pr3
SetMenuDefaultItem equ <_imp__SetMenuDefaultItem@12>

externdef _imp__SetMenuInfo@8:PTR pr2
SetMenuInfo equ <_imp__SetMenuInfo@8>

externdef _imp__SetMenuItemBitmaps@20:PTR pr5
SetMenuItemBitmaps equ <_imp__SetMenuItemBitmaps@20>

externdef _imp__SetMenuItemInfoA@16:PTR pr4
SetMenuItemInfo equ <_imp__SetMenuItemInfoA@16>

externdef _imp__SetMessageExtraInfo@4:PTR pr1
SetMessageExtraInfo equ <_imp__SetMessageExtraInfo@4>

externdef _imp__SetMessageQueue@4:PTR pr1
SetMessageQueue equ <_imp__SetMessageQueue@4>

externdef _imp__SetParent@8:PTR pr2
SetParent equ <_imp__SetParent@8>

externdef _imp__SetProcessWindowStation@4:PTR pr1
SetProcessWindowStation equ <_imp__SetProcessWindowStation@4>

externdef _imp__SetPropA@12:PTR pr3
SetProp equ <_imp__SetPropA@12>

externdef _imp__SetRect@20:PTR pr5
SetRect equ <_imp__SetRect@20>

externdef _imp__SetRectEmpty@4:PTR pr1
SetRectEmpty equ <_imp__SetRectEmpty@4>

externdef _imp__SetScrollInfo@16:PTR pr4
SetScrollInfo equ <_imp__SetScrollInfo@16>

externdef _imp__SetScrollPos@16:PTR pr4
SetScrollPos equ <_imp__SetScrollPos@16>

externdef _imp__SetScrollRange@20:PTR pr5
SetScrollRange equ <_imp__SetScrollRange@20>

externdef _imp__SetShellWindow@4:PTR pr1
SetShellWindow equ <_imp__SetShellWindow@4>

externdef _imp__SetSysColors@12:PTR pr3
SetSysColors equ <_imp__SetSysColors@12>

externdef _imp__SetSystemCursor@8:PTR pr2
SetSystemCursor equ <_imp__SetSystemCursor@8>

externdef _imp__SetSystemMenu@8:PTR pr2
SetSystemMenu equ <_imp__SetSystemMenu@8>

externdef _imp__SetSystemTimer@16:PTR pr4
SetSystemTimer equ <_imp__SetSystemTimer@16>

externdef _imp__SetThreadDesktop@4:PTR pr1
SetThreadDesktop equ <_imp__SetThreadDesktop@4>

externdef _imp__SetTimer@16:PTR pr4
SetTimer equ <_imp__SetTimer@16>

externdef _imp__SetUserObjectInformationA@16:PTR pr4
SetUserObjectInformation equ <_imp__SetUserObjectInformationA@16>

externdef _imp__SetUserObjectSecurity@12:PTR pr3
SetUserObjectSecurity equ <_imp__SetUserObjectSecurity@12>

externdef _imp__SetWinEventHook@28:PTR pr7
SetWinEventHook equ <_imp__SetWinEventHook@28>

externdef _imp__SetWindowContextHelpId@8:PTR pr2
SetWindowContextHelpId equ <_imp__SetWindowContextHelpId@8>

externdef _imp__SetWindowLongA@12:PTR pr3
SetWindowLong equ <_imp__SetWindowLongA@12>

externdef _imp__SetWindowPlacement@8:PTR pr2
SetWindowPlacement equ <_imp__SetWindowPlacement@8>

externdef _imp__SetWindowPos@28:PTR pr7
SetWindowPos equ <_imp__SetWindowPos@28>

externdef _imp__SetWindowRgn@12:PTR pr3
SetWindowRgn equ <_imp__SetWindowRgn@12>

externdef _imp__SetWindowTextA@8:PTR pr2
SetWindowText equ <_imp__SetWindowTextA@8>

externdef _imp__SetWindowWord@12:PTR pr3
SetWindowWord equ <_imp__SetWindowWord@12>

externdef _imp__SetWindowsHookA@8:PTR pr2
SetWindowsHook equ <_imp__SetWindowsHookA@8>

externdef _imp__SetWindowsHookExA@16:PTR pr4
SetWindowsHookEx equ <_imp__SetWindowsHookExA@16>

externdef _imp__ShowCaret@4:PTR pr1
ShowCaret equ <_imp__ShowCaret@4>

externdef _imp__ShowCursor@4:PTR pr1
ShowCursor equ <_imp__ShowCursor@4>

externdef _imp__ShowOwnedPopups@8:PTR pr2
ShowOwnedPopups equ <_imp__ShowOwnedPopups@8>

externdef _imp__ShowScrollBar@12:PTR pr3
ShowScrollBar equ <_imp__ShowScrollBar@12>

externdef _imp__ShowWindow@8:PTR pr2
ShowWindow equ <_imp__ShowWindow@8>

externdef _imp__ShowWindowAsync@8:PTR pr2
ShowWindowAsync equ <_imp__ShowWindowAsync@8>

externdef _imp__SubtractRect@12:PTR pr3
SubtractRect equ <_imp__SubtractRect@12>

externdef _imp__SwapMouseButton@4:PTR pr1
SwapMouseButton equ <_imp__SwapMouseButton@4>

externdef _imp__SwitchDesktop@4:PTR pr1
SwitchDesktop equ <_imp__SwitchDesktop@4>

externdef _imp__SystemParametersInfoA@16:PTR pr4
SystemParametersInfo equ <_imp__SystemParametersInfoA@16>

externdef _imp__TabbedTextOutA@32:PTR pr8
TabbedTextOut equ <_imp__TabbedTextOutA@32>

externdef _imp__TileChildWindows@8:PTR pr2
TileChildWindows equ <_imp__TileChildWindows@8>

externdef _imp__TileWindows@20:PTR pr5
TileWindows equ <_imp__TileWindows@20>

externdef _imp__ToAscii@20:PTR pr5
ToAscii equ <_imp__ToAscii@20>

externdef _imp__ToAsciiEx@24:PTR pr6
ToAsciiEx equ <_imp__ToAsciiEx@24>

externdef _imp__ToUnicode@24:PTR pr6
ToUnicode equ <_imp__ToUnicode@24>

externdef _imp__ToUnicodeEx@28:PTR pr7
ToUnicodeEx equ <_imp__ToUnicodeEx@28>

externdef _imp__TrackMouseEvent@4:PTR pr1
TrackMouseEvent equ <_imp__TrackMouseEvent@4>

externdef _imp__TrackPopupMenu@28:PTR pr7
TrackPopupMenu equ <_imp__TrackPopupMenu@28>

externdef _imp__TrackPopupMenuEx@24:PTR pr6
TrackPopupMenuEx equ <_imp__TrackPopupMenuEx@24>

externdef _imp__TranslateAcceleratorA@12:PTR pr3
TranslateAccelerator equ <_imp__TranslateAcceleratorA@12>

externdef _imp__TranslateMDISysAccel@8:PTR pr2
TranslateMDISysAccel equ <_imp__TranslateMDISysAccel@8>

externdef _imp__TranslateMessage@4:PTR pr1
TranslateMessage equ <_imp__TranslateMessage@4>

externdef _imp__UnhookWinEvent@4:PTR pr1
UnhookWinEvent equ <_imp__UnhookWinEvent@4>

externdef _imp__UnhookWindowsHook@8:PTR pr2
UnhookWindowsHook equ <_imp__UnhookWindowsHook@8>

externdef _imp__UnhookWindowsHookEx@4:PTR pr1
UnhookWindowsHookEx equ <_imp__UnhookWindowsHookEx@4>

externdef _imp__UnionRect@12:PTR pr3
UnionRect equ <_imp__UnionRect@12>

externdef _imp__UnloadKeyboardLayout@4:PTR pr1
UnloadKeyboardLayout equ <_imp__UnloadKeyboardLayout@4>

externdef _imp__UnpackDDElParam@16:PTR pr4
UnpackDDElParam equ <_imp__UnpackDDElParam@16>

externdef _imp__UnregisterClassA@8:PTR pr2
UnregisterClass equ <_imp__UnregisterClassA@8>

externdef _imp__UnregisterDeviceNotification@4:PTR pr1
UnregisterDeviceNotification equ <_imp__UnregisterDeviceNotification@4>

externdef _imp__UnregisterHotKey@8:PTR pr2
UnregisterHotKey equ <_imp__UnregisterHotKey@8>

externdef _imp__UpdateWindow@4:PTR pr1
UpdateWindow equ <_imp__UpdateWindow@4>

externdef _imp__UserHandleGrantAccess@8:PTR pr2
UserHandleGrantAccess equ <_imp__UserHandleGrantAccess@8>

externdef _imp__ValidateRect@8:PTR pr2
ValidateRect equ <_imp__ValidateRect@8>

externdef _imp__ValidateRgn@8:PTR pr2
ValidateRgn equ <_imp__ValidateRgn@8>

externdef _imp__VkKeyScanA@4:PTR pr1
VkKeyScan equ <_imp__VkKeyScanA@4>

externdef _imp__VkKeyScanExA@8:PTR pr2
VkKeyScanEx equ <_imp__VkKeyScanExA@8>

externdef _imp__WINNLSEnableIME@8:PTR pr2
WINNLSEnableIME equ <_imp__WINNLSEnableIME@8>

externdef _imp__WINNLSGetEnableStatus@4:PTR pr1
WINNLSGetEnableStatus equ <_imp__WINNLSGetEnableStatus@4>

externdef _imp__WINNLSGetIMEHotkey@4:PTR pr1
WINNLSGetIMEHotkey equ <_imp__WINNLSGetIMEHotkey@4>

externdef _imp__WaitForInputIdle@8:PTR pr2
WaitForInputIdle equ <_imp__WaitForInputIdle@8>

externdef _imp__WaitMessage@0:PTR pr0
WaitMessage equ <_imp__WaitMessage@0>

externdef _imp__WinHelpA@16:PTR pr4
WinHelp equ <_imp__WinHelpA@16>

externdef _imp__WindowFromDC@4:PTR pr1
WindowFromDC equ <_imp__WindowFromDC@4>

externdef _imp__WindowFromPoint@8:PTR pr2
WindowFromPoint equ <_imp__WindowFromPoint@8>

externdef _imp__keybd_event@16:PTR pr4
keybd_event equ <_imp__keybd_event@16>

externdef _imp__mouse_event@20:PTR pr5
mouse_event equ <_imp__mouse_event@20>

externdef _imp__wvsprintfA@12:PTR pr3
wvsprintf equ <_imp__wvsprintfA@12>

