[40m[2J[2;1H[9C[0;1;34mÜÜ    Ü   Þ Þ Ü ÜÜ  ÜÜÜÜ Þ    Ü   ÜÜ   ÜÜÜ[3;1H[s
[u[6C[0mÚÄ[1;34mÞÛ ß[0mÄÄ[1;34mÞÝÝ[0mÄÄ[1;34mÛÝÞÝÞÞÛ ß[0mÄ[1;34mÛÜ[s
[u ÞÝÞ[0mÄÄÄ[1;34mÞÝÝ[0mÄ[1;34mÞÛ[0mÄ[1;34mÝ[0mÄ[1;34mÞÛ ß[0mÄÄ¿
[4;1H[1mÚÄÄÄÄÄ´  [34mßß±[0;34mÜ [1m²ß²  ±ÞÝ±  ßß±[0;34mÜÞ[1m²ßß ²   ²[s
[uß² ±± [0;34mÜÜÞ[1m²ßß  [37mÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿[5;1H³[5C[0mÀÄ[s
[u[34mßÛÜ²²Þ[1m°[0mÄ[1;34m±°[0;34mÞ[1m°[0mÄÄ[1;34m°[0;34mÝßÛÜ²²Þ[s
[u[1m°[0;34mÝ[37mÄÄ[34mÞÜÛÞ[1m°[0mÄ[1;34m±°[0;34mÞ[1m°°[0;34mÛÝ[s
[u[37mÄ[1;34m±[0;34mÜÜÛ[1mß[0mÙ[1;30ma T.F.A.[15C[0m³[6;1H[1m³[s
[u[9C[0;34mßß    ßßßß  ßß  ßß ßßß   ßß   ßß ßßß    ßß    [1;30mGRouND Ze[s
[uRo BoaRD    [0m³[7;1H[1m³[76C[0m³[8;1H³[6CoNLiNe SCeNe STuFF oNLy [s
[uSo THaT IS aMiGa aND PC aND PCe uTiLs[9C[1;30m³[9;1H[0m³[5CSo STaRT [s
[uPuMPiNG YouR oWN MaDe DeMo'S uTiLS MoDuLeS eTC eTC eTC[8C[1;30m³[10;1H[s
[u[0m³[11;1H[1;30m³[21C[0mNeW WoRLD oRDeR MaGaZiNe CeNTeR[24C[1;30m³
[12;1H[18C[0m   DiST SiTeS FRoM D.S. aND PRoGReSS    [19C³[13;1H[1;30m[s
[u³[76C[0m³[14;1H³[28CSPeeD 14K4 No HST[31C³[15;1H³[76C[1m³[16;1H³[s
[u[12C[0mRuNNiNG uNDeR PC eXPReSS 0.9974 STiLL THe BeST oNe[14C[1m³
[17;1H³[76C³[18;1HÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[s
[u[0m´FRieND SHiP RuLeZÃ[1mÄÄÄÄÄÙ[19;1H[0m
