@  @  @  @  @r @e @k @l @a @m @s @u @x @x @: @) @  @  @  @  @  @  @  @
@ C h e c k   o u t   d a   u p c o m i n g   D - s k m a g          @
@                         +++++++++                   +++            @
@         +   +  +++     ++  +++      +      +   +   +               @
@         ++ +  +   +  +++   +  +    + +     ++ ++   ++              @
@         + ++  +   +   +    +++   + +++ +  ++ + + + +   +           @
@        +   +   +++  ++     +  +   +   +   ++   ++  ++++      by    @
@      ++++++++++++++++                                      SpARTas @
@[100_percent_asm, svga, short, low_req, feel_da_luxury, noncensored]@
@  @  @  @  @  @  @  @  @  @  @  @  @  @  @  @  @  @  @  @  @  @  @  @












Checkout2: DangbirD/SpARTas^Priority
If U haven't got a musician recently, and wanna some zax under one of your
productions, just contact me. I am a 'rentable musician', I make zax 4 any
groups/coders desiring it. (Just try and see if my zak is c00l.)
Contact: at the Spartas BBS
or search for the tables of SpARTas on any of the quality (rulez) parties.
Remark: I don't feel anyway the necessity of being a member in your team,
unless it is a really high qualified group. :)
Dudez from foreign countries can request some music, too!


Checkout3: My secondary team, Priority searches for a talented coder who
is interested in having a full membership at Priority.
If U wanna join us, mailto:
 ake@freemail.c3.hu             (ake/priority)
or search for the tables of SpARTas on any of the quality (rulez) parties.
