--------------------------CARDRIVE (1 Kb-os j t‚k)-----------------------------


  1. Rendszerk”vetelm‚nyek
  2. Mi van a k‚perny“n?
  3. Hogy ir ny¡tsd?

1. Rendszerk”vetelm‚nyek

    Processzor: 386SX
    Monitor: VGA
    Szabad hely: 1 Kilobyte
    Mem¢ria: n‚h ny kilobyte

2. Mi van a k‚perny“n?

    A k‚perny“ fels“ r‚sz‚n l that¢ , (na micsoda?), az ‚g. Ebben a "k‚ks‚gben"
    l that¢  egy  cs¡k,  ahol  feh‚r  pontok  futkoznak. Ezek a feh‚r pontok az
    aut¢k.  A cs¡k fels“ r‚sz‚n a bal s v l that¢, az als¢ r‚sz‚n pedig, £gysem
    tal lod  ki,  a  jobb  s v l that¢. A cs¡kok kezdet‚n(a k‚perny“ bal fel‚n)
    a  pirossal  befestett r‚sz jelzi a mi aut¢nkat (m rha Szuzuki). A k‚perny“
    als¢ r‚sz‚n van az £t. Itt mennek az aut¢k.

3. Hogy ir ny¡tsd?

    Billenty–k: Bal ny¡l ‚s jobb ny¡l: Balra ‚s jobbra korm nyozza az aut¢t
                Felfel‚ ‚s lefel‚ ny¡l: Gyors¡tja illetve lass¡tja az aut¢t
                Escape: kil‚p

 J¢ sz¢rakoz st k¡v n:  Paunch (P¢cza Kriszti n)