/*
  config.h - fxmp config
  Copyright (C) 1999-2001, Bekir Osman Keskin <spectre@portent.net>

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

#ifndef __CONFIG_H__
#define __CONFIG_H__

#define HAVE_ULTRASOUND_H

#define LOOP 1
#define TINY 1 /* removes most printfs */

/*** don't play with these :D ***/
/* #define AMIGAPERIODS 1 */
/* #define EIGHTBITS 1 */
/* #define THREADS */
#define VERBOSE -1

#endif /* __CONFIG_H__ */
