@echo off
rename porrfilm.st1 porrfilm.exe
rename porrfilm.st2 hsc.exe
rename porrfilm.st3 music.hsc
hsc.exe music.hsc
porrfilm.exe
hsc
@echo off
rename porrfilm.exe porrfilm.st1
rename hsc.exe porrfilm.st2
rename music.hsc porrfilm.st3
echo code: monGo und cybhawolf
echo gfx: monGo
echo music: some 3rd party member?!...
echo onani: big phat jama mama
echo Heavy runme.bat code by monGo!
echo greets:fuck you party remedy.
